BEGIN;

-- v4 Bible expansion, part 4: 122 further events, taking the work to 136.
-- Narrative sequence is renumbered so the new events interleave with the v3.1
-- ones instead of being appended. Every event keeps a coarse year range, an
-- explicit reality label and an explicit confidence label; nothing is sharpened
-- into a date the sources do not support, and the primeval era carries no
-- historical years at all.

-- Step 1: park the existing sequences out of the way (UNIQUE is not enforced on
-- events.sequence, but overlapping numbers would still break narrative order).
UPDATE events SET sequence = sequence + 1000 WHERE work_id='10000000-0000-4000-8000-000000000005';

INSERT INTO events(id,work_id,slug,sequence,reality,event_type,time_type,calendar_system,historical_start_year,historical_end_year,confidence,chapter_id)
SELECT ('62000000-0000-4000-8000-'||lpad(v.n::text,12,'0'))::uuid,'10000000-0000-4000-8000-000000000005',v.slug,v.seq,
       v.reality::event_reality,v.etype::literary_event_type,v.ttype::event_time_type,'unknown'::calendar_system,
       v.y1,v.y2,v.conf::confidence_level,ch.id
FROM (VALUES
(1,'flood-narrative-ends-at-ararat',1,'legendary_or_mythic','other','unknown',NULL::integer,NULL::integer,'low','primeval'),
(2,'covenant-after-the-flood',2,'legendary_or_mythic','religious','unknown',NULL,NULL,'low','primeval'),
(3,'dispersal-at-babel',3,'legendary_or_mythic','migration','unknown',NULL,NULL,'low','primeval'),
(4,'abram-at-shechem',5,'reported_historical','migration','range',-2100,-1900,'low','patriarchs'),
(5,'lot-settles-near-sodom',6,'reported_historical','migration','range',-2100,-1900,'low','patriarchs'),
(6,'hagar-and-ishmael-in-the-wilderness',7,'reported_historical','escape','range',-2050,-1900,'low','patriarchs'),
(7,'destruction-of-the-sodom-cities',9,'legendary_or_mythic','other','range',-2050,-1900,'low','patriarchs'),
(8,'binding-of-isaac',10,'reported_historical','religious','range',-2000,-1850,'low','patriarchs'),
(9,'sarah-buried-at-hebron',11,'reported_historical','death','range',-2000,-1850,'low','patriarchs'),
(10,'rebekah-brought-from-harran',12,'reported_historical','marriage','range',-2000,-1850,'low','patriarchs'),
(11,'jacob-takes-the-blessing',13,'reported_historical','betrayal','range',-1950,-1800,'low','patriarchs'),
(12,'jacobs-dream-at-bethel',14,'reported_historical','religious','range',-1950,-1800,'low','patriarchs'),
(13,'jacob-marries-leah-and-rachel',15,'reported_historical','marriage','range',-1940,-1780,'low','patriarchs'),
(14,'jacob-and-esau-reconcile',17,'reported_historical','meeting','range',-1900,-1750,'low','patriarchs'),
(15,'joseph-sold-into-egypt',18,'reported_historical','betrayal','range',-1900,-1720,'low','patriarchs'),
(16,'joseph-rises-in-egypt',19,'reported_historical','political','range',-1890,-1700,'low','patriarchs'),
(17,'brothers-reunite-in-egypt',20,'reported_historical','meeting','range',-1880,-1700,'low','patriarchs'),
(18,'household-settles-in-goshen',21,'reported_historical','migration','range',-1880,-1700,'low','patriarchs'),
(19,'rachel-buried-near-bethlehem',22,'reported_historical','death','range',-1900,-1750,'low','patriarchs'),
(20,'birth-of-moses-in-goshen',23,'reported_historical','birth','range',-1400,-1250,'low','exodus-and-sinai'),
(21,'moses-flees-to-midian',24,'reported_historical','escape','range',-1380,-1250,'low','exodus-and-sinai'),
(22,'call-at-the-burning-bush',25,'legendary_or_mythic','religious','range',-1350,-1230,'low','exodus-and-sinai'),
(23,'confrontation-with-pharaoh',26,'contested','political','range',-1320,-1210,'low','exodus-and-sinai'),
(24,'crossing-of-the-sea',28,'legendary_or_mythic','journey','range',-1300,-1200,'low','exodus-and-sinai'),
(25,'song-at-the-sea',29,'reported_historical','religious','range',-1300,-1200,'low','exodus-and-sinai'),
(26,'golden-calf-episode',31,'reported_historical','religious','range',-1300,-1200,'low','exodus-and-sinai'),
(27,'jethro-advises-a-court-system',32,'reported_historical','social','range',-1300,-1200,'low','exodus-and-sinai'),
(28,'scouts-sent-from-kadesh',33,'reported_historical','discovery','range',-1280,-1190,'low','wilderness-and-conquest'),
(29,'long-stay-at-kadesh',34,'reported_historical','social','range',-1280,-1180,'low','wilderness-and-conquest'),
(30,'death-of-aaron',35,'reported_historical','death','range',-1260,-1170,'low','wilderness-and-conquest'),
(31,'moses-views-canaan-from-nebo',36,'reported_historical','death','range',-1250,-1160,'low','wilderness-and-conquest'),
(32,'scouts-sheltered-by-rahab',37,'reported_historical','escape','range',-1250,-1160,'low','wilderness-and-conquest'),
(33,'crossing-the-jordan',38,'reported_historical','journey','range',-1250,-1160,'low','wilderness-and-conquest'),
(34,'fall-of-jericho',39,'contested','battle','range',-1250,-1150,'low','wilderness-and-conquest'),
(35,'shrine-set-up-at-shiloh',40,'reported_historical','religious','range',-1220,-1120,'low','wilderness-and-conquest'),
(36,'deborah-and-barak-muster-at-tabor',41,'reported_historical','meeting','range',-1150,-1080,'low','judges'),
(37,'battle-near-megiddo',42,'reported_historical','battle','range',-1150,-1080,'low','judges'),
(38,'gideon-reduces-his-force',43,'reported_historical','battle','range',-1140,-1060,'low','judges'),
(39,'samson-among-the-philistine-cities',44,'reported_historical','social','range',-1120,-1050,'low','judges'),
(40,'samson-and-delilah',45,'reported_historical','betrayal','range',-1110,-1050,'low','judges'),
(41,'samson-at-gaza',46,'reported_historical','death','range',-1110,-1050,'low','judges'),
(42,'naomi-and-ruth-reach-bethlehem',47,'reported_historical','migration','range',-1100,-1040,'low','judges'),
(43,'ruth-and-boaz-at-the-threshing-floor',48,'reported_historical','marriage','range',-1100,-1040,'low','judges'),
(44,'samuel-serves-at-shiloh',49,'reported_historical','religious','range',-1080,-1040,'low','judges'),
(45,'samuel-anoints-saul',50,'reported_historical','political','range',-1050,-1020,'medium','united-monarchy'),
(46,'saul-rejected-at-ramah',51,'reported_historical','political','range',-1040,-1015,'low','united-monarchy'),
(47,'samuel-anoints-david-at-bethlehem',52,'reported_historical','political','range',-1030,-1015,'medium','united-monarchy'),
(48,'david-and-goliath-in-the-valley-of-elah',53,'reported_historical','battle','range',-1030,-1010,'low','united-monarchy'),
(49,'jonathan-and-david-make-a-covenant',54,'reported_historical','meeting','range',-1025,-1010,'low','united-monarchy'),
(50,'david-a-fugitive-in-the-south',55,'reported_historical','escape','range',-1020,-1010,'medium','united-monarchy'),
(51,'abigail-intercedes',56,'reported_historical','meeting','range',-1020,-1010,'low','united-monarchy'),
(52,'saul-and-jonathan-die-on-gilboa',57,'reported_historical','battle','range',-1010,-1005,'medium','united-monarchy'),
(53,'bathsheba-and-nathans-rebuke',60,'reported_historical','betrayal','range',-995,-985,'low','united-monarchy'),
(54,'absaloms-revolt',61,'reported_historical','political','range',-985,-975,'medium','united-monarchy'),
(55,'death-of-absalom',62,'reported_historical','death','range',-980,-975,'medium','united-monarchy'),
(56,'solomon-succeeds-david',63,'reported_historical','political','range',-975,-965,'medium','united-monarchy'),
(57,'rehoboam-refuses-relief',65,'reported_historical','political','range',-935,-925,'medium','divided-kingdoms'),
(58,'kingdom-divides',66,'reported_historical','political','range',-935,-925,'medium','divided-kingdoms'),
(59,'jeroboam-establishes-northern-shrines',67,'reported_historical','religious','range',-930,-910,'medium','divided-kingdoms'),
(60,'ahab-and-jezebel-marry',68,'reported_historical','marriage','range',-880,-870,'medium','divided-kingdoms'),
(61,'contest-on-mount-carmel',69,'legendary_or_mythic','religious','range',-870,-850,'low','divided-kingdoms'),
(62,'elijah-withdraws-to-horeb',70,'reported_historical','escape','range',-870,-850,'low','divided-kingdoms'),
(63,'elijah-passes-the-mantle',71,'reported_historical','meeting','range',-860,-845,'low','divided-kingdoms'),
(64,'naboths-vineyard',72,'reported_historical','betrayal','range',-865,-850,'low','divided-kingdoms'),
(65,'death-of-jezebel',73,'reported_historical','death','range',-845,-835,'low','divided-kingdoms'),
(66,'fall-of-samaria',74,'verified_historical','battle','range',-724,-720,'high','divided-kingdoms'),
(67,'jonah-sails-from-joppa',75,'legendary_or_mythic','journey','range',-800,-700,'low','prophetic-narrative'),
(68,'jonah-heads-for-tarshish',76,'legendary_or_mythic','journey','range',-800,-700,'low','prophetic-narrative'),
(69,'jonah-outside-nineveh',78,'legendary_or_mythic','social','range',-800,-700,'low','prophetic-narrative'),
(70,'isaiah-called-in-the-temple',79,'reported_historical','religious','range',-745,-735,'low','prophetic-narrative'),
(71,'isaiah-counsels-hezekiah',80,'reported_historical','political','range',-705,-698,'medium','judah-and-exile'),
(72,'assyrian-siege-of-lachish',81,'verified_historical','battle','range',-702,-700,'high','judah-and-exile'),
(73,'sennacherib-besieges-jerusalem',82,'verified_historical','battle','range',-702,-700,'high','judah-and-exile'),
(74,'hezekiahs-water-tunnel',83,'verified_historical','discovery','range',-705,-695,'high','judah-and-exile'),
(75,'jeremiah-called',84,'reported_historical','religious','range',-627,-620,'medium','judah-and-exile'),
(76,'first-deportation-to-babylon',85,'verified_historical','migration','range',-605,-597,'high','judah-and-exile'),
(77,'daniel-in-the-babylonian-court',86,'contested','political','range',-600,-540,'low','judah-and-exile'),
(78,'ezekiels-vision-by-the-canal',87,'reported_historical','religious','range',-593,-590,'medium','judah-and-exile'),
(79,'jerusalem-falls',88,'verified_historical','battle','range',-587,-586,'high','judah-and-exile'),
(80,'temple-destroyed',89,'verified_historical','other','range',-587,-586,'high','judah-and-exile'),
(81,'jeremiah-taken-to-egypt',90,'reported_historical','migration','range',-586,-580,'medium','judah-and-exile'),
(82,'belshazzars-feast',91,'contested','political','range',-540,-539,'low','judah-and-exile'),
(83,'daniel-in-the-lions-den',92,'legendary_or_mythic','imprisonment','range',-540,-530,'low','judah-and-exile'),
(84,'cyrus-permits-return',93,'verified_historical','political','range',-539,-538,'high','return-and-restoration'),
(85,'first-returnees-reach-jerusalem',94,'reported_historical','migration','range',-538,-530,'medium','return-and-restoration'),
(86,'second-temple-rebuilt',95,'reported_historical','other','range',-520,-515,'medium','return-and-restoration'),
(87,'esther-becomes-queen-at-susa',96,'contested','marriage','range',-483,-478,'low','return-and-restoration'),
(88,'mordecai-refuses-to-bow',97,'contested','social','range',-478,-474,'low','return-and-restoration'),
(89,'esther-intervenes-at-court',98,'contested','trial','range',-474,-473,'low','return-and-restoration'),
(90,'nehemiah-rebuilds-the-wall',99,'reported_historical','other','range',-445,-432,'medium','return-and-restoration'),
(91,'annunciation-at-nazareth',100,'reported_historical','religious','range',-7,-5,'low','gospels'),
(92,'flight-to-egypt',102,'reported_historical','escape','range',-5,-3,'low','gospels'),
(93,'return-to-nazareth',103,'reported_historical','migration','range',-4,1,'low','gospels'),
(94,'baptism-at-the-jordan',104,'reported_historical','religious','range',26,29,'medium','gospels'),
(95,'first-sign-at-cana',105,'legendary_or_mythic','social','range',27,30,'low','gospels'),
(96,'calling-of-the-first-disciples',106,'reported_historical','meeting','range',27,30,'medium','gospels'),
(97,'conversation-at-jacobs-well',108,'reported_historical','meeting','range',27,31,'low','gospels'),
(98,'transfiguration-on-tabor',109,'legendary_or_mythic','religious','range',28,32,'low','gospels'),
(99,'raising-of-lazarus',110,'legendary_or_mythic','other','range',29,33,'low','gospels'),
(100,'entry-into-jerusalem',111,'reported_historical','journey','range',30,33,'medium','gospels'),
(101,'last-supper',112,'reported_historical','meeting','range',30,33,'medium','gospels'),
(102,'arrest-on-the-mount-of-olives',113,'reported_historical','betrayal','range',30,33,'medium','gospels'),
(103,'trial-before-pilate',114,'reported_historical','trial','range',30,33,'medium','gospels'),
(104,'empty-tomb',116,'contested','other','range',30,33,'low','gospels'),
(105,'road-to-emmaus',117,'contested','meeting','range',30,33,'low','gospels'),
(106,'pentecost-in-jerusalem',118,'reported_historical','religious','range',30,33,'medium','acts'),
(107,'stephen-is-killed',119,'reported_historical','death','range',33,36,'medium','acts'),
(108,'peters-vision-at-joppa',120,'reported_historical','religious','range',37,44,'low','acts'),
(109,'peter-and-cornelius-at-caesarea',121,'reported_historical','meeting','range',37,44,'medium','acts'),
(110,'barnabas-brings-paul-to-antioch',123,'reported_historical','meeting','range',42,46,'medium','acts'),
(111,'first-journey-begins-at-cyprus',124,'reported_historical','journey','range',46,48,'medium','pauline-mission'),
(112,'jerusalem-council',125,'reported_historical','meeting','range',48,50,'medium','pauline-mission'),
(113,'crossing-into-macedonia',126,'reported_historical','journey','range',49,51,'medium','pauline-mission'),
(114,'lydia-hosts-at-philippi',127,'reported_historical','meeting','range',49,51,'medium','pauline-mission'),
(115,'paul-and-silas-detained-at-philippi',128,'reported_historical','imprisonment','range',49,51,'medium','pauline-mission'),
(116,'debate-at-athens',129,'reported_historical','social','range',50,52,'medium','pauline-mission'),
(117,'long-stay-at-corinth',130,'reported_historical','social','range',50,52,'medium','pauline-mission'),
(118,'years-at-ephesus',131,'reported_historical','social','range',52,55,'medium','pauline-mission'),
(119,'arrest-in-jerusalem',132,'reported_historical','imprisonment','range',57,59,'medium','pauline-mission'),
(120,'hearing-at-caesarea',133,'reported_historical','trial','range',57,59,'medium','pauline-mission'),
(121,'shipwreck-at-malta',134,'reported_historical','journey','range',59,60,'medium','pauline-mission'),
(122,'patmos-vision',136,'contested','religious','range',81,96,'low','pauline-mission')
) AS v(n,slug,seq,reality,etype,ttype,y1,y2,conf,chapter_slug)
JOIN chapters ch ON ch.slug=v.chapter_slug AND ch.work_id='10000000-0000-4000-8000-000000000005';

-- Step 2: give the v3.1 events their place in the merged narrative order and
-- correct one chapter assignment that the wider structure now makes possible.
UPDATE events e SET sequence=v.seq FROM (VALUES
  ('abraham-leaves-ur',4),('birth-of-isaac',8),('jacob-named-israel',16),('exodus-from-egypt',27),
  ('sinai-covenant',30),('david-becomes-king',58),('jerusalem-royal-capital',59),('first-temple-built',64),
  ('jonah-to-nineveh',77),('birth-of-jesus',101),('galilean-ministry',107),('crucifixion-in-jerusalem',115),
  ('paul-conversion-damascus',122),('paul-arrives-rome',135)
) AS v(slug,seq) WHERE e.work_id='10000000-0000-4000-8000-000000000005' AND e.slug=v.slug;

UPDATE events e SET chapter_id=ch.id FROM chapters ch
WHERE e.work_id='10000000-0000-4000-8000-000000000005' AND e.slug='paul-arrives-rome'
  AND ch.slug='pauline-mission' AND ch.work_id=e.work_id;

INSERT INTO event_translations(event_id,locale,title,summary,status,detail,significance,time_label)
SELECT e.id,v.locale::locale_code,v.title,v.summary,'published','','','' FROM events e JOIN (VALUES
('flood-narrative-ends-at-ararat','zh-CN','方舟停于亚拉腊山地','洪水叙事以方舟停靠山地区域收束。'),('flood-narrative-ends-at-ararat','en','The ark rests in the mountains of Ararat','The flood narrative closes as the ark comes to rest in a highland region.'),
('covenant-after-the-flood','zh-CN','洪水之后的立约','灾难之后重新确立人与世界关系的叙事段落。'),('covenant-after-the-flood','en','Covenant after the flood','A narrative section re-establishing the relation between people and world after catastrophe.'),
('dispersal-at-babel','zh-CN','巴别的语言分散','建塔叙事以语言分歧与族群分散作结。'),('dispersal-at-babel','en','Dispersal at Babel','The tower narrative ends in divergence of language and the scattering of peoples.'),
('abram-at-shechem','zh-CN','亚伯兰到示剑','迁徙队伍抵达迦南地区的第一个停留点。'),('abram-at-shechem','en','Abram at Shechem','The migrating household reaches its first stopping place in Canaan.'),
('lot-settles-near-sodom','zh-CN','罗得迁往所多玛一带','叔侄分开牧地，罗得选择约旦河谷南部。'),('lot-settles-near-sodom','en','Lot settles near Sodom','Uncle and nephew separate their pasture; Lot chooses the southern Jordan valley.'),
('hagar-and-ishmael-in-the-wilderness','zh-CN','夏甲与以实玛利在旷野','家族内部冲突导致母子被逐至南部旷野。'),('hagar-and-ishmael-in-the-wilderness','en','Hagar and Ishmael in the wilderness','Household conflict sends mother and son into the southern wilderness.'),
('destruction-of-the-sodom-cities','zh-CN','所多玛诸城被毁','审判叙事以城邑被毁与罗得一家离开作结。'),('destruction-of-the-sodom-cities','en','Destruction of the Sodom cities','A judgement narrative ending in the ruin of the cities and Lot’s departure.'),
('binding-of-isaac','zh-CN','以撒被献的叙事','族长叙事中张力最强的一段考验。'),('binding-of-isaac','en','The binding of Isaac','The most severe test in the patriarchal narrative.'),
('sarah-buried-at-hebron','zh-CN','撒拉葬于希伯仑','家族购地立墓，首次在迦南取得产业。'),('sarah-buried-at-hebron','en','Sarah is buried at Hebron','The household buys a burial plot, its first holding in Canaan.'),
('rebekah-brought-from-harran','zh-CN','利百加自哈兰而来','为以撒寻找配偶的行程叙事。'),('rebekah-brought-from-harran','en','Rebekah is brought from Harran','A journey narrative to find a wife for Isaac.'),
('jacob-takes-the-blessing','zh-CN','雅各取得祝福','继承权冲突以欺瞒手段展开。'),('jacob-takes-the-blessing','en','Jacob takes the blessing','The inheritance conflict unfolds through deception.'),
('jacobs-dream-at-bethel','zh-CN','雅各在伯特利的梦','逃亡途中的异象叙事。'),('jacobs-dream-at-bethel','en','Jacob’s dream at Bethel','A vision narrative during flight.'),
('jacob-marries-leah-and-rachel','zh-CN','雅各娶利亚与拉结','以劳动换取婚约的家族契约叙事。'),('jacob-marries-leah-and-rachel','en','Jacob marries Leah and Rachel','A household-contract narrative exchanging labour for marriage.'),
('jacob-and-esau-reconcile','zh-CN','雅各与以扫和解','兄弟冲突在渡口之后收束。'),('jacob-and-esau-reconcile','en','Jacob and Esau reconcile','The sibling conflict resolves after the river crossing.'),
('joseph-sold-into-egypt','zh-CN','约瑟被卖到埃及','兄弟冲突把叙事推向埃及。'),('joseph-sold-into-egypt','en','Joseph is sold into Egypt','Sibling conflict moves the narrative to Egypt.'),
('joseph-rises-in-egypt','zh-CN','约瑟在埃及执政','从囚徒到行政职位的转变。'),('joseph-rises-in-egypt','en','Joseph rises to office in Egypt','A turn from prisoner to administrator.'),
('brothers-reunite-in-egypt','zh-CN','兄弟在埃及重逢','认亲叙事结束家族分裂。'),('brothers-reunite-in-egypt','en','The brothers are reunited in Egypt','A recognition narrative ends the household’s split.'),
('household-settles-in-goshen','zh-CN','雅各家定居歌珊','族长叙事与出埃及叙事的接点。'),('household-settles-in-goshen','en','The household settles in Goshen','The joint between the patriarchal and Exodus narratives.'),
('rachel-buried-near-bethlehem','zh-CN','拉结葬于伯利恒附近','迁徙途中的死亡叙事。'),('rachel-buried-near-bethlehem','en','Rachel is buried near Bethlehem','A death narrative on the road.'),
('birth-of-moses-in-goshen','zh-CN','摩西在歌珊出生','在压迫政策背景下的出生叙事。'),('birth-of-moses-in-goshen','en','Moses is born in Goshen','A birth narrative set against a policy of oppression.'),
('moses-flees-to-midian','zh-CN','摩西逃往米甸','杀人事件后离开埃及。'),('moses-flees-to-midian','en','Moses flees to Midian','Departure from Egypt after a killing.'),
('call-at-the-burning-bush','zh-CN','荆棘中的呼召','旷野中的委任叙事。'),('call-at-the-burning-bush','en','The call at the burning bush','A commissioning narrative in the wilderness.'),
('confrontation-with-pharaoh','zh-CN','与法老的交涉','一系列谈判与灾害叙事。'),('confrontation-with-pharaoh','en','Confrontation with Pharaoh','A sequence of negotiation and plague narratives.'),
('crossing-of-the-sea','zh-CN','渡海','出埃及叙事的核心转折。'),('crossing-of-the-sea','en','The sea crossing','The central turning point of the Exodus narrative.'),
('song-at-the-sea','zh-CN','海边之歌','以诗歌形式记述的胜利叙事。'),('song-at-the-sea','en','The song at the sea','A victory narrative preserved as poetry.'),
('golden-calf-episode','zh-CN','金牛犊事件','盟约叙事中的内部危机。'),('golden-calf-episode','en','The golden calf episode','An internal crisis within the covenant narrative.'),
('jethro-advises-a-court-system','zh-CN','叶忒罗建议分层审判','群体治理制度的建立。'),('jethro-advises-a-court-system','en','Jethro advises a tiered court','The establishment of a governance structure.'),
('scouts-sent-from-kadesh','zh-CN','从加低斯派出探子','侦察与评估分歧的叙事。'),('scouts-sent-from-kadesh','en','Scouts are sent from Kadesh','A reconnaissance narrative and a split in assessment.'),
('long-stay-at-kadesh','zh-CN','在加低斯的长期停留','旷野漂流的主要阶段。'),('long-stay-at-kadesh','en','The long stay at Kadesh','The main phase of the wilderness wandering.'),
('death-of-aaron','zh-CN','亚伦去世','祭司职分的交接。'),('death-of-aaron','en','The death of Aaron','The handover of the priestly office.'),
('moses-views-canaan-from-nebo','zh-CN','摩西在尼波山远望','律法者叙事的收束。'),('moses-views-canaan-from-nebo','en','Moses views Canaan from Nebo','The close of the lawgiver narrative.'),
('scouts-sheltered-by-rahab','zh-CN','喇合收留探子','本地人协助外来者的叙事。'),('scouts-sheltered-by-rahab','en','Rahab shelters the scouts','A local resident assists outsiders.'),
('crossing-the-jordan','zh-CN','渡过约旦河','进入定居阶段的界线。'),('crossing-the-jordan','en','Crossing the Jordan','The boundary into the settlement phase.'),
('fall-of-jericho','zh-CN','耶利哥城陷落','征战叙事的开端，考古证据存在争议。'),('fall-of-jericho','en','The fall of Jericho','The opening of the conquest narrative; the archaeology is disputed.'),
('shrine-set-up-at-shiloh','zh-CN','在示罗设立圣所','中央祭祀地点的确立。'),('shrine-set-up-at-shiloh','en','The shrine is set up at Shiloh','The establishment of a central cultic site.'),
('deborah-and-barak-muster-at-tabor','zh-CN','底波拉与巴拉在他泊山集结','士师叙事中的联合行动。'),('deborah-and-barak-muster-at-tabor','en','Deborah and Barak muster at Tabor','A joint action in the judges narrative.'),
('battle-near-megiddo','zh-CN','米吉多附近的战役','以诗歌与散文两种版本保存的战事。'),('battle-near-megiddo','en','The battle near Megiddo','A battle preserved in both prose and poetic versions.'),
('gideon-reduces-his-force','zh-CN','基甸削减队伍','以少胜多叙事的核心安排。'),('gideon-reduces-his-force','en','Gideon reduces his force','The core device of a few-against-many narrative.'),
('samson-among-the-philistine-cities','zh-CN','参孙在非利士诸城','个人冲突升级为群体冲突。'),('samson-among-the-philistine-cities','en','Samson among the Philistine cities','Personal conflict escalates into collective conflict.'),
('samson-and-delilah','zh-CN','参孙与大利拉','背叛叙事的经典段落。'),('samson-and-delilah','en','Samson and Delilah','A classic betrayal section.'),
('samson-at-gaza','zh-CN','参孙在迦萨','士师叙事的收束事件。'),('samson-at-gaza','en','Samson at Gaza','The closing event of the Samson narrative.'),
('naomi-and-ruth-reach-bethlehem','zh-CN','拿俄米与路得回到伯利恒','外族女性进入以色列社群的叙事起点。'),('naomi-and-ruth-reach-bethlehem','en','Naomi and Ruth reach Bethlehem','The start of a foreign woman’s entry into the community.'),
('ruth-and-boaz-at-the-threshing-floor','zh-CN','路得与波阿斯在禾场','以赎回制度推进的关系叙事。'),('ruth-and-boaz-at-the-threshing-floor','en','Ruth and Boaz at the threshing floor','A relationship narrative advanced through the redemption custom.'),
('samuel-serves-at-shiloh','zh-CN','撒母耳在示罗事奉','士师时代向王国时代过渡的人物起点。'),('samuel-serves-at-shiloh','en','Samuel serves at Shiloh','The starting point of the figure who bridges two eras.'),
('samuel-anoints-saul','zh-CN','撒母耳膏立扫罗','王制建立的开端。'),('samuel-anoints-saul','en','Samuel anoints Saul','The beginning of the monarchy.'),
('saul-rejected-at-ramah','zh-CN','扫罗在拉玛被弃','先知与王权的第一次决裂。'),('saul-rejected-at-ramah','en','Saul is rejected at Ramah','The first rupture between prophet and crown.'),
('samuel-anoints-david-at-bethlehem','zh-CN','撒母耳在伯利恒膏立大卫','王权转移叙事的伏笔。'),('samuel-anoints-david-at-bethlehem','en','Samuel anoints David at Bethlehem','The setup for the transfer of kingship.'),
('david-and-goliath-in-the-valley-of-elah','zh-CN','以拉谷的对峙','个人对决决定群体胜负的叙事。'),('david-and-goliath-in-the-valley-of-elah','en','The confrontation in the Valley of Elah','A single combat that decides a collective outcome.'),
('jonathan-and-david-make-a-covenant','zh-CN','约拿单与大卫立约','忠诚冲突的核心关系。'),('jonathan-and-david-make-a-covenant','en','Jonathan and David make a covenant','The relationship at the centre of a loyalty conflict.'),
('david-a-fugitive-in-the-south','zh-CN','大卫在南方逃亡','长期流亡阶段。'),('david-a-fugitive-in-the-south','en','David a fugitive in the south','An extended period of flight.'),
('abigail-intercedes','zh-CN','亚比该出面交涉','以谈判取代报复的段落。'),('abigail-intercedes','en','Abigail intercedes','A section in which negotiation replaces reprisal.'),
('saul-and-jonathan-die-on-gilboa','zh-CN','扫罗与约拿单死于基利波','第一王朝的终结。'),('saul-and-jonathan-die-on-gilboa','en','Saul and Jonathan die on Gilboa','The end of the first dynasty.'),
('bathsheba-and-nathans-rebuke','zh-CN','拔示巴事件与拿单的责备','王权叙事中的道德危机。'),('bathsheba-and-nathans-rebuke','en','Bathsheba and Nathan’s rebuke','A moral crisis inside the royal narrative.'),
('absaloms-revolt','zh-CN','押沙龙叛乱','家族冲突升级为政权危机。'),('absaloms-revolt','en','Absalom’s revolt','A household conflict becomes a crisis of rule.'),
('death-of-absalom','zh-CN','押沙龙之死','叛乱平息与父子叙事的终点。'),('death-of-absalom','en','The death of Absalom','The revolt ends and the father-son thread closes.'),
('solomon-succeeds-david','zh-CN','所罗门继位','宫廷继承斗争的结果。'),('solomon-succeeds-david','en','Solomon succeeds David','The outcome of a court succession struggle.'),
('rehoboam-refuses-relief','zh-CN','罗波安拒绝减轻负担','分裂的直接触发点。'),('rehoboam-refuses-relief','en','Rehoboam refuses relief','The immediate trigger of the division.'),
('kingdom-divides','zh-CN','王国分裂','南北两国并立的开始。'),('kingdom-divides','en','The kingdom divides','The beginning of two parallel kingdoms.'),
('jeroboam-establishes-northern-shrines','zh-CN','耶罗波安设立北方祭祀中心','政治分裂延伸到宗教制度。'),('jeroboam-establishes-northern-shrines','en','Jeroboam establishes northern shrines','Political division extends into religious institutions.'),
('ahab-and-jezebel-marry','zh-CN','亚哈与耶洗别联姻','外交联姻带来宗教冲突。'),('ahab-and-jezebel-marry','en','Ahab and Jezebel marry','A diplomatic marriage brings religious conflict.'),
('contest-on-mount-carmel','zh-CN','迦密山的对峙','先知叙事中最公开的冲突场面。'),('contest-on-mount-carmel','en','The contest on Mount Carmel','The most public confrontation in the prophetic narrative.'),
('elijah-withdraws-to-horeb','zh-CN','以利亚退往何烈山','公开对抗之后的退隐段落。'),('elijah-withdraws-to-horeb','en','Elijah withdraws to Horeb','A withdrawal section following public confrontation.'),
('elijah-passes-the-mantle','zh-CN','以利亚传承给以利沙','先知职分的交接。'),('elijah-passes-the-mantle','en','Elijah passes the mantle','The handover of the prophetic office.'),
('naboths-vineyard','zh-CN','拿伯的葡萄园','王权侵占土地引发的控告。'),('naboths-vineyard','en','Naboth’s vineyard','A royal seizure of land and the accusation that follows.'),
('death-of-jezebel','zh-CN','耶洗别之死','北国宫廷叙事的转折。'),('death-of-jezebel','en','The death of Jezebel','A turning point in the northern court narrative.'),
('fall-of-samaria','zh-CN','撒玛利亚陷落','北国终结，亚述铭文提供外部对照。'),('fall-of-samaria','en','The fall of Samaria','The end of the northern kingdom; Assyrian inscriptions give external comparison.'),
('jonah-sails-from-joppa','zh-CN','约拿从约帕登船','拒绝使命的行程起点。'),('jonah-sails-from-joppa','en','Jonah sails from Joppa','The start of a journey away from a commission.'),
('jonah-heads-for-tarshish','zh-CN','约拿驶向他施','以地理方向表达逃避主题。'),('jonah-heads-for-tarshish','en','Jonah heads for Tarshish','Geographic direction expresses the theme of avoidance.'),
('jonah-outside-nineveh','zh-CN','约拿在城外','叙事以未解的争论收束。'),('jonah-outside-nineveh','en','Jonah outside the city','The narrative closes on an unresolved argument.'),
('isaiah-called-in-the-temple','zh-CN','以赛亚在圣殿的呼召','先知职分的开端叙事。'),('isaiah-called-in-the-temple','en','Isaiah’s call in the temple','The opening narrative of a prophetic commission.'),
('isaiah-counsels-hezekiah','zh-CN','以赛亚向希西家进言','国际危机中的政治宗教建议。'),('isaiah-counsels-hezekiah','en','Isaiah counsels Hezekiah','Political and religious advice during an international crisis.'),
('assyrian-siege-of-lachish','zh-CN','亚述围攻拉吉','亚述浮雕提供图像旁证。'),('assyrian-siege-of-lachish','en','The Assyrian siege of Lachish','Assyrian reliefs provide pictorial corroboration.'),
('sennacherib-besieges-jerusalem','zh-CN','西拿基立围困耶路撒冷','双方记述结果不同的事件。'),('sennacherib-besieges-jerusalem','en','Sennacherib besieges Jerusalem','An event whose outcome the two sides record differently.'),
('hezekiahs-water-tunnel','zh-CN','希西家水道工程','围城准备的工程证据。'),('hezekiahs-water-tunnel','en','Hezekiah’s water tunnel','Engineering evidence of siege preparation.'),
('jeremiah-called','zh-CN','耶利米受召','危机前夕的先知起点。'),('jeremiah-called','en','Jeremiah is called','A prophetic beginning on the eve of crisis.'),
('first-deportation-to-babylon','zh-CN','首批被掳往巴比伦','流散叙事的开始。'),('first-deportation-to-babylon','en','The first deportation to Babylon','The beginning of the exile narrative.'),
('daniel-in-the-babylonian-court','zh-CN','但以理在巴比伦宫廷','异邦宫廷中的身份叙事。'),('daniel-in-the-babylonian-court','en','Daniel in the Babylonian court','An identity narrative inside a foreign court.'),
('ezekiels-vision-by-the-canal','zh-CN','以西结在河边的异象','流散群体的异象文本起点。'),('ezekiels-vision-by-the-canal','en','Ezekiel’s vision by the canal','The opening vision of a displaced community’s text.'),
('jerusalem-falls','zh-CN','耶路撒冷陷落','王国叙事的终点。'),('jerusalem-falls','en','Jerusalem falls','The end of the monarchic narrative.'),
('temple-destroyed','zh-CN','圣殿被毁','宗教中心的丧失。'),('temple-destroyed','en','The temple is destroyed','The loss of the religious centre.'),
('jeremiah-taken-to-egypt','zh-CN','耶利米被带往埃及','先知叙事的最后阶段。'),('jeremiah-taken-to-egypt','en','Jeremiah is taken to Egypt','The final phase of the prophetic narrative.'),
('belshazzars-feast','zh-CN','伯沙撒的筵席','政权更替前夜的宫廷场面。'),('belshazzars-feast','en','Belshazzar’s feast','A court scene on the eve of a change of power.'),
('daniel-in-the-lions-den','zh-CN','但以理在狮子坑','忠诚与制度冲突的叙事。'),('daniel-in-the-lions-den','en','Daniel in the lions’ den','A narrative of loyalty against institutional pressure.'),
('cyrus-permits-return','zh-CN','居鲁士准许归回','帝国政策改变群体命运。'),('cyrus-permits-return','en','Cyrus permits the return','Imperial policy changes a community’s course.'),
('first-returnees-reach-jerusalem','zh-CN','首批归回者抵达耶路撒冷','重建阶段的开端。'),('first-returnees-reach-jerusalem','en','The first returnees reach Jerusalem','The start of the rebuilding phase.'),
('second-temple-rebuilt','zh-CN','第二圣殿重建','宗教中心的恢复。'),('second-temple-rebuilt','en','The second temple is rebuilt','The restoration of the religious centre.'),
('esther-becomes-queen-at-susa','zh-CN','以斯帖在书珊成为王后','宫廷叙事的起点。'),('esther-becomes-queen-at-susa','en','Esther becomes queen at Susa','The opening of the court narrative.'),
('mordecai-refuses-to-bow','zh-CN','末底改拒绝行礼','冲突的触发点。'),('mordecai-refuses-to-bow','en','Mordecai refuses to bow','The trigger of the conflict.'),
('esther-intervenes-at-court','zh-CN','以斯帖在宫廷介入','以程序而非武力改变结果。'),('esther-intervenes-at-court','en','Esther intervenes at court','An outcome changed by procedure rather than force.'),
('nehemiah-rebuilds-the-wall','zh-CN','尼希米重建城墙','有政治阻力的公共工程。'),('nehemiah-rebuilds-the-wall','en','Nehemiah rebuilds the wall','A public work carried out against political resistance.'),
('annunciation-at-nazareth','zh-CN','拿撒勒的宣告','诞生叙事的开端。'),('annunciation-at-nazareth','en','The annunciation at Nazareth','The opening of the birth narrative.'),
('flight-to-egypt','zh-CN','逃往埃及','危险中的迁徙叙事。'),('flight-to-egypt','en','The flight to Egypt','A migration narrative under threat.'),
('return-to-nazareth','zh-CN','回到拿撒勒','成长阶段的定居地。'),('return-to-nazareth','en','The return to Nazareth','The settled location of the upbringing phase.'),
('baptism-at-the-jordan','zh-CN','约旦河的洗礼','公开阶段的起点。'),('baptism-at-the-jordan','en','The baptism at the Jordan','The start of the public phase.'),
('first-sign-at-cana','zh-CN','迦拿的第一个神迹','约翰福音叙事的开场。'),('first-sign-at-cana','en','The first sign at Cana','The opening scene of the Johannine narrative.'),
('calling-of-the-first-disciples','zh-CN','呼召最初的门徒','群体形成的起点。'),('calling-of-the-first-disciples','en','The calling of the first disciples','The start of the group’s formation.'),
('conversation-at-jacobs-well','zh-CN','雅各井旁的对话','跨越族群界线的对话叙事。'),('conversation-at-jacobs-well','en','The conversation at Jacob’s well','A dialogue narrative across an ethnic boundary.'),
('transfiguration-on-tabor','zh-CN','他泊山的变貌','门徒叙事中的异象段落。'),('transfiguration-on-tabor','en','The transfiguration on Tabor','A vision section within the disciple narrative.'),
('raising-of-lazarus','zh-CN','拉撒路复活叙事','约翰福音的转折事件。'),('raising-of-lazarus','en','The raising of Lazarus','The turning point of the Johannine narrative.'),
('entry-into-jerusalem','zh-CN','进入耶路撒冷','最后一周的开端。'),('entry-into-jerusalem','en','The entry into Jerusalem','The opening of the final week.'),
('last-supper','zh-CN','最后的晚餐','群体内部的最后聚集。'),('last-supper','en','The last supper','The group’s final gathering.'),
('arrest-on-the-mount-of-olives','zh-CN','橄榄山的逮捕','受难叙事的开始。'),('arrest-on-the-mount-of-olives','en','The arrest on the Mount of Olives','The beginning of the passion narrative.'),
('trial-before-pilate','zh-CN','在彼拉多前受审','宗教冲突进入罗马司法程序。'),('trial-before-pilate','en','The trial before Pilate','A religious conflict enters Roman judicial procedure.'),
('empty-tomb','zh-CN','空坟墓','复活叙事的起点，各福音书记述不一。'),('empty-tomb','en','The empty tomb','The start of the resurrection narrative; the Gospels differ in detail.'),
('road-to-emmaus','zh-CN','以马忤斯路上','以行走承载认出主题的段落。'),('road-to-emmaus','en','The road to Emmaus','A section carrying recognition through the act of walking.'),
('pentecost-in-jerusalem','zh-CN','耶路撒冷的五旬节','群体公开活动的开端。'),('pentecost-in-jerusalem','en','Pentecost in Jerusalem','The start of the group’s public activity.'),
('stephen-is-killed','zh-CN','司提反被处死','引发向外扩散的事件。'),('stephen-is-killed','en','Stephen is killed','The event that triggers dispersal outward.'),
('peters-vision-at-joppa','zh-CN','彼得在约帕的异象','群体边界问题的转折。'),('peters-vision-at-joppa','en','Peter’s vision at Joppa','A turning point on the question of the group’s boundary.'),
('peter-and-cornelius-at-caesarea','zh-CN','彼得与哥尼流在该撒利亚','非犹太人加入群体的关键叙事。'),('peter-and-cornelius-at-caesarea','en','Peter and Cornelius at Caesarea','The key narrative of non-Jewish entry into the community.'),
('barnabas-brings-paul-to-antioch','zh-CN','巴拿巴带保罗到安提阿','宣教行程的组织起点。'),('barnabas-brings-paul-to-antioch','en','Barnabas brings Paul to Antioch','The organisational starting point of the missions.'),
('first-journey-begins-at-cyprus','zh-CN','第一次旅程自塞浦路斯开始','行程叙事离开大陆。'),('first-journey-begins-at-cyprus','en','The first journey begins at Cyprus','The itinerary narrative leaves the mainland.'),
('jerusalem-council','zh-CN','耶路撒冷会议','群体规则的公开裁定。'),('jerusalem-council','en','The Jerusalem council','A public ruling on the community’s rules.'),
('crossing-into-macedonia','zh-CN','进入马其顿','行程叙事进入欧洲。'),('crossing-into-macedonia','en','Crossing into Macedonia','The itinerary narrative enters Europe.'),
('lydia-hosts-at-philippi','zh-CN','吕底亚在腓立比接待','欧洲首个记名接待者。'),('lydia-hosts-at-philippi','en','Lydia hosts at Philippi','The first named host in Europe.'),
('paul-and-silas-detained-at-philippi','zh-CN','保罗与西拉在腓立比被拘','公民身份成为叙事焦点。'),('paul-and-silas-detained-at-philippi','en','Paul and Silas are detained at Philippi','Civic status becomes the focus of the narrative.'),
('debate-at-athens','zh-CN','雅典的辩论','与希腊哲学传统的正面接触。'),('debate-at-athens','en','The debate at Athens','A direct encounter with the Greek philosophical tradition.'),
('long-stay-at-corinth','zh-CN','在哥林多的长期停留','书信文本的重要背景。'),('long-stay-at-corinth','en','The long stay at Corinth','An important setting behind the letter texts.'),
('years-at-ephesus','zh-CN','以弗所的数年','行程叙事中停留最久的城市。'),('years-at-ephesus','en','The years at Ephesus','The longest urban stay in the itinerary.'),
('arrest-in-jerusalem','zh-CN','在耶路撒冷被捕','最后阶段的开端。'),('arrest-in-jerusalem','en','Arrest in Jerusalem','The beginning of the final phase.'),
('hearing-at-caesarea','zh-CN','在该撒利亚受审','行省司法程序中的辩护。'),('hearing-at-caesarea','en','The hearing at Caesarea','A defence within provincial judicial procedure.'),
('shipwreck-at-malta','zh-CN','马耳他船难','航程中断与延续的节点。'),('shipwreck-at-malta','en','The shipwreck at Malta','The break-and-continue node of the voyage.'),
('patmos-vision','zh-CN','拔摩岛的异象','启示文本的自述写作场景。'),('patmos-vision','en','The Patmos vision','The stated writing setting of the Revelation text.')
) AS v(slug,locale,title,summary) ON e.slug=v.slug AND e.work_id='10000000-0000-4000-8000-000000000005';

INSERT INTO event_locations(event_id,location_id,role,position)
SELECT e.id,l.id,'primary',0 FROM events e JOIN (VALUES
('flood-narrative-ends-at-ararat','ararat-mountains'),('covenant-after-the-flood','ararat-mountains'),('dispersal-at-babel','babylon'),
('abram-at-shechem','canaan-shechem'),('lot-settles-near-sodom','sodom-region'),('hagar-and-ishmael-in-the-wilderness','beersheba'),
('destruction-of-the-sodom-cities','sodom-region'),('binding-of-isaac','jerusalem'),('sarah-buried-at-hebron','hebron'),
('rebekah-brought-from-harran','harran'),('jacob-takes-the-blessing','beersheba'),('jacobs-dream-at-bethel','bethel'),
('jacob-marries-leah-and-rachel','harran'),('jacob-and-esau-reconcile','peniel-jabbok'),('joseph-sold-into-egypt','canaan-shechem'),
('joseph-rises-in-egypt','nile-delta'),('brothers-reunite-in-egypt','nile-delta'),('household-settles-in-goshen','goshen'),
('rachel-buried-near-bethlehem','bethlehem'),
('birth-of-moses-in-goshen','goshen'),('moses-flees-to-midian','mount-sinai-traditional'),('call-at-the-burning-bush','mount-sinai-traditional'),
('confrontation-with-pharaoh','nile-delta'),('crossing-of-the-sea','reed-sea-crossing'),('song-at-the-sea','reed-sea-crossing'),
('golden-calf-episode','mount-sinai-traditional'),('jethro-advises-a-court-system','mount-sinai-traditional'),
('scouts-sent-from-kadesh','kadesh-barnea'),('long-stay-at-kadesh','kadesh-barnea'),('death-of-aaron','kadesh-barnea'),
('moses-views-canaan-from-nebo','mount-nebo'),('scouts-sheltered-by-rahab','jericho'),('crossing-the-jordan','jordan-river-bethany'),
('fall-of-jericho','jericho'),('shrine-set-up-at-shiloh','shiloh'),
('deborah-and-barak-muster-at-tabor','mount-tabor'),('battle-near-megiddo','megiddo'),('gideon-reduces-his-force','megiddo'),
('samson-among-the-philistine-cities','gaza'),('samson-and-delilah','gaza'),('samson-at-gaza','gaza'),
('naomi-and-ruth-reach-bethlehem','bethlehem'),('ruth-and-boaz-at-the-threshing-floor','bethlehem'),('samuel-serves-at-shiloh','shiloh'),
('samuel-anoints-saul','ramah'),('saul-rejected-at-ramah','ramah'),('samuel-anoints-david-at-bethlehem','bethlehem'),
('david-and-goliath-in-the-valley-of-elah','valley-of-elah'),('jonathan-and-david-make-a-covenant','ramah'),
('david-a-fugitive-in-the-south','beersheba'),('abigail-intercedes','hebron'),('saul-and-jonathan-die-on-gilboa','mount-gilboa'),
('bathsheba-and-nathans-rebuke','jerusalem'),('absaloms-revolt','jerusalem'),('death-of-absalom','jerusalem'),('solomon-succeeds-david','jerusalem'),
('rehoboam-refuses-relief','jerusalem'),('kingdom-divides','samaria-sebaste'),('jeroboam-establishes-northern-shrines','bethel'),
('ahab-and-jezebel-marry','samaria-sebaste'),('contest-on-mount-carmel','mount-carmel'),('elijah-withdraws-to-horeb','mount-sinai-traditional'),
('elijah-passes-the-mantle','samaria-sebaste'),('naboths-vineyard','samaria-sebaste'),('death-of-jezebel','samaria-sebaste'),('fall-of-samaria','samaria-sebaste'),
('jonah-sails-from-joppa','joppa'),('jonah-heads-for-tarshish','tarshish-reference'),('jonah-outside-nineveh','nineveh'),
('isaiah-called-in-the-temple','jerusalem'),('isaiah-counsels-hezekiah','jerusalem'),
('assyrian-siege-of-lachish','lachish'),('sennacherib-besieges-jerusalem','jerusalem'),('hezekiahs-water-tunnel','jerusalem'),
('jeremiah-called','jerusalem'),('first-deportation-to-babylon','babylon'),('daniel-in-the-babylonian-court','babylon'),
('ezekiels-vision-by-the-canal','babylon'),('jerusalem-falls','jerusalem'),('temple-destroyed','jerusalem'),
('jeremiah-taken-to-egypt','nile-delta'),('belshazzars-feast','babylon'),('daniel-in-the-lions-den','babylon'),
('cyrus-permits-return','babylon'),('first-returnees-reach-jerusalem','jerusalem'),('second-temple-rebuilt','jerusalem'),
('esther-becomes-queen-at-susa','susa'),('mordecai-refuses-to-bow','susa'),('esther-intervenes-at-court','susa'),('nehemiah-rebuilds-the-wall','jerusalem'),
('annunciation-at-nazareth','nazareth'),('flight-to-egypt','nile-delta'),('return-to-nazareth','nazareth'),
('baptism-at-the-jordan','jordan-river-bethany'),('first-sign-at-cana','cana'),('calling-of-the-first-disciples','sea-of-galilee'),
('conversation-at-jacobs-well','sychar-jacobs-well'),('transfiguration-on-tabor','mount-tabor'),('raising-of-lazarus','bethany-near-jerusalem'),
('entry-into-jerusalem','mount-of-olives'),('last-supper','jerusalem'),('arrest-on-the-mount-of-olives','mount-of-olives'),
('trial-before-pilate','jerusalem'),('empty-tomb','golgotha-traditional'),('road-to-emmaus','emmaus-reference'),
('pentecost-in-jerusalem','jerusalem'),('stephen-is-killed','jerusalem'),('peters-vision-at-joppa','joppa'),
('peter-and-cornelius-at-caesarea','caesarea-maritima'),('barnabas-brings-paul-to-antioch','antioch-orontes'),
('first-journey-begins-at-cyprus','cyprus-salamis'),('jerusalem-council','jerusalem'),('crossing-into-macedonia','philippi'),
('lydia-hosts-at-philippi','philippi'),('paul-and-silas-detained-at-philippi','philippi'),('debate-at-athens','athens'),
('long-stay-at-corinth','corinth'),('years-at-ephesus','ephesus'),('arrest-in-jerusalem','jerusalem'),
('hearing-at-caesarea','caesarea-maritima'),('shipwreck-at-malta','malta'),('patmos-vision','patmos')
) AS v(event_slug,location_slug) ON e.slug=v.event_slug AND e.work_id='10000000-0000-4000-8000-000000000005'
JOIN locations l ON l.slug=v.location_slug AND l.work_id=e.work_id
ON CONFLICT DO NOTHING;

INSERT INTO event_characters(event_id,character_id,role,participant_order,is_primary)
SELECT e.id,c.id,CASE WHEN v.ord=0 THEN 'primary' ELSE 'participant' END,v.ord,v.ord=0 FROM events e JOIN (VALUES
('flood-narrative-ends-at-ararat','noah',0),('covenant-after-the-flood','noah',0),('dispersal-at-babel','noah',0),
('abram-at-shechem','abraham',0),('abram-at-shechem','sarah',1),('abram-at-shechem','lot',2),
('lot-settles-near-sodom','lot',0),('lot-settles-near-sodom','abraham',1),
('hagar-and-ishmael-in-the-wilderness','hagar',0),('hagar-and-ishmael-in-the-wilderness','ishmael',1),('hagar-and-ishmael-in-the-wilderness','sarah',2),
('destruction-of-the-sodom-cities','lot',0),('destruction-of-the-sodom-cities','abraham',1),
('binding-of-isaac','abraham',0),('binding-of-isaac','isaac',1),
('sarah-buried-at-hebron','sarah',0),('sarah-buried-at-hebron','abraham',1),
('rebekah-brought-from-harran','rebekah',0),('rebekah-brought-from-harran','isaac',1),
('jacob-takes-the-blessing','jacob',0),('jacob-takes-the-blessing','esau',1),('jacob-takes-the-blessing','rebekah',2),('jacob-takes-the-blessing','isaac',3),
('jacobs-dream-at-bethel','jacob',0),
('jacob-marries-leah-and-rachel','jacob',0),('jacob-marries-leah-and-rachel','leah',1),('jacob-marries-leah-and-rachel','rachel',2),
('jacob-and-esau-reconcile','jacob',0),('jacob-and-esau-reconcile','esau',1),
('joseph-sold-into-egypt','joseph-son-of-jacob',0),('joseph-sold-into-egypt','judah-son-of-jacob',1),
('joseph-rises-in-egypt','joseph-son-of-jacob',0),
('brothers-reunite-in-egypt','joseph-son-of-jacob',0),('brothers-reunite-in-egypt','benjamin',1),('brothers-reunite-in-egypt','judah-son-of-jacob',2),
('household-settles-in-goshen','jacob',0),('household-settles-in-goshen','joseph-son-of-jacob',1),
('rachel-buried-near-bethlehem','rachel',0),('rachel-buried-near-bethlehem','jacob',1),
('birth-of-moses-in-goshen','moses',0),('birth-of-moses-in-goshen','miriam',1),
('moses-flees-to-midian','moses',0),('moses-flees-to-midian','jethro',1),
('call-at-the-burning-bush','moses',0),
('confrontation-with-pharaoh','moses',0),('confrontation-with-pharaoh','aaron',1),('confrontation-with-pharaoh','pharaoh-of-the-exodus',2),
('crossing-of-the-sea','moses',0),('crossing-of-the-sea','pharaoh-of-the-exodus',1),
('song-at-the-sea','miriam',0),('song-at-the-sea','moses',1),
('golden-calf-episode','aaron',0),('golden-calf-episode','moses',1),
('jethro-advises-a-court-system','jethro',0),('jethro-advises-a-court-system','moses',1),
('scouts-sent-from-kadesh','joshua',0),('scouts-sent-from-kadesh','caleb',1),('scouts-sent-from-kadesh','moses',2),
('long-stay-at-kadesh','moses',0),('long-stay-at-kadesh','aaron',1),('long-stay-at-kadesh','miriam',2),
('death-of-aaron','aaron',0),('death-of-aaron','moses',1),
('moses-views-canaan-from-nebo','moses',0),('moses-views-canaan-from-nebo','joshua',1),
('scouts-sheltered-by-rahab','rahab',0),('scouts-sheltered-by-rahab','joshua',1),
('crossing-the-jordan','joshua',0),('fall-of-jericho','joshua',0),('fall-of-jericho','rahab',1),
('shrine-set-up-at-shiloh','joshua',0),
('deborah-and-barak-muster-at-tabor','deborah',0),('deborah-and-barak-muster-at-tabor','barak',1),
('battle-near-megiddo','deborah',0),('battle-near-megiddo','barak',1),
('gideon-reduces-his-force','gideon',0),
('samson-among-the-philistine-cities','samson',0),('samson-and-delilah','samson',0),('samson-and-delilah','delilah',1),
('samson-at-gaza','samson',0),
('naomi-and-ruth-reach-bethlehem','ruth',0),('ruth-and-boaz-at-the-threshing-floor','ruth',0),('ruth-and-boaz-at-the-threshing-floor','boaz',1),
('samuel-serves-at-shiloh','samuel',0),
('samuel-anoints-saul','samuel',0),('samuel-anoints-saul','saul',1),
('saul-rejected-at-ramah','samuel',0),('saul-rejected-at-ramah','saul',1),
('samuel-anoints-david-at-bethlehem','samuel',0),('samuel-anoints-david-at-bethlehem','david',1),
('david-and-goliath-in-the-valley-of-elah','david',0),('david-and-goliath-in-the-valley-of-elah','goliath',1),('david-and-goliath-in-the-valley-of-elah','saul',2),
('jonathan-and-david-make-a-covenant','jonathan',0),('jonathan-and-david-make-a-covenant','david',1),
('david-a-fugitive-in-the-south','david',0),('david-a-fugitive-in-the-south','saul',1),
('abigail-intercedes','abigail',0),('abigail-intercedes','david',1),
('saul-and-jonathan-die-on-gilboa','saul',0),('saul-and-jonathan-die-on-gilboa','jonathan',1),
('bathsheba-and-nathans-rebuke','david',0),('bathsheba-and-nathans-rebuke','bathsheba',1),('bathsheba-and-nathans-rebuke','nathan',2),
('absaloms-revolt','absalom',0),('absaloms-revolt','david',1),('absaloms-revolt','joab',2),
('death-of-absalom','absalom',0),('death-of-absalom','joab',1),
('solomon-succeeds-david','solomon',0),('solomon-succeeds-david','bathsheba',1),('solomon-succeeds-david','david',2),
('rehoboam-refuses-relief','rehoboam',0),('kingdom-divides','jeroboam',0),('kingdom-divides','rehoboam',1),
('jeroboam-establishes-northern-shrines','jeroboam',0),
('ahab-and-jezebel-marry','ahab',0),('ahab-and-jezebel-marry','jezebel',1),
('contest-on-mount-carmel','elijah',0),('contest-on-mount-carmel','ahab',1),('contest-on-mount-carmel','jezebel',2),
('elijah-withdraws-to-horeb','elijah',0),
('elijah-passes-the-mantle','elijah',0),('elijah-passes-the-mantle','elisha',1),
('naboths-vineyard','ahab',0),('naboths-vineyard','jezebel',1),('naboths-vineyard','elijah',2),
('death-of-jezebel','jezebel',0),('fall-of-samaria','isaiah',0),
('jonah-sails-from-joppa','jonah',0),('jonah-heads-for-tarshish','jonah',0),('jonah-outside-nineveh','jonah',0),
('isaiah-called-in-the-temple','isaiah',0),
('isaiah-counsels-hezekiah','isaiah',0),('isaiah-counsels-hezekiah','hezekiah',1),
('assyrian-siege-of-lachish','hezekiah',0),('sennacherib-besieges-jerusalem','hezekiah',0),('sennacherib-besieges-jerusalem','isaiah',1),
('hezekiahs-water-tunnel','hezekiah',0),('jeremiah-called','jeremiah',0),
('first-deportation-to-babylon','nebuchadnezzar',0),('first-deportation-to-babylon','daniel',1),
('daniel-in-the-babylonian-court','daniel',0),('daniel-in-the-babylonian-court','nebuchadnezzar',1),
('ezekiels-vision-by-the-canal','ezekiel',0),
('jerusalem-falls','nebuchadnezzar',0),('jerusalem-falls','jeremiah',1),
('temple-destroyed','nebuchadnezzar',0),('jeremiah-taken-to-egypt','jeremiah',0),
('belshazzars-feast','daniel',0),('daniel-in-the-lions-den','daniel',0),
('cyrus-permits-return','cyrus',0),('first-returnees-reach-jerusalem','cyrus',0),('second-temple-rebuilt','cyrus',0),
('esther-becomes-queen-at-susa','esther',0),('esther-becomes-queen-at-susa','mordecai',1),
('mordecai-refuses-to-bow','mordecai',0),('esther-intervenes-at-court','esther',0),('esther-intervenes-at-court','mordecai',1),
('nehemiah-rebuilds-the-wall','nehemiah',0),
('annunciation-at-nazareth','mary',0),('flight-to-egypt','herod-the-great',0),('flight-to-egypt','mary',1),('flight-to-egypt','joseph-of-nazareth',2),('flight-to-egypt','jesus',3),
('return-to-nazareth','jesus',0),('return-to-nazareth','mary',1),('return-to-nazareth','joseph-of-nazareth',2),
('baptism-at-the-jordan','john-the-baptist',0),('baptism-at-the-jordan','jesus',1),
('first-sign-at-cana','jesus',0),('first-sign-at-cana','mary',1),
('calling-of-the-first-disciples','peter',0),('calling-of-the-first-disciples','andrew',1),('calling-of-the-first-disciples','john-son-of-zebedee',2),('calling-of-the-first-disciples','jesus',3),
('conversation-at-jacobs-well','jesus',0),
('transfiguration-on-tabor','jesus',0),('transfiguration-on-tabor','peter',1),('transfiguration-on-tabor','john-son-of-zebedee',2),
('raising-of-lazarus','lazarus',0),('raising-of-lazarus','martha',1),('raising-of-lazarus','jesus',2),
('entry-into-jerusalem','jesus',0),
('last-supper','jesus',0),('last-supper','peter',1),('last-supper','judas-iscariot',2),('last-supper','john-son-of-zebedee',3),
('arrest-on-the-mount-of-olives','jesus',0),('arrest-on-the-mount-of-olives','judas-iscariot',1),('arrest-on-the-mount-of-olives','peter',2),
('trial-before-pilate','jesus',0),('trial-before-pilate','pontius-pilate',1),
('empty-tomb','mary-magdalene',0),('empty-tomb','peter',1),('empty-tomb','john-son-of-zebedee',2),
('road-to-emmaus','jesus',0),
('pentecost-in-jerusalem','peter',0),('pentecost-in-jerusalem','john-son-of-zebedee',1),
('stephen-is-killed','stephen',0),('stephen-is-killed','paul',1),
('peters-vision-at-joppa','peter',0),('peter-and-cornelius-at-caesarea','peter',0),('peter-and-cornelius-at-caesarea','cornelius',1),
('barnabas-brings-paul-to-antioch','barnabas',0),('barnabas-brings-paul-to-antioch','paul',1),
('first-journey-begins-at-cyprus','paul',0),('first-journey-begins-at-cyprus','barnabas',1),
('jerusalem-council','paul',0),('jerusalem-council','barnabas',1),('jerusalem-council','peter',2),
('crossing-into-macedonia','paul',0),('crossing-into-macedonia','silas',1),('crossing-into-macedonia','luke',2),
('lydia-hosts-at-philippi','lydia',0),('lydia-hosts-at-philippi','paul',1),
('paul-and-silas-detained-at-philippi','paul',0),('paul-and-silas-detained-at-philippi','silas',1),
('debate-at-athens','paul',0),
('long-stay-at-corinth','paul',0),('long-stay-at-corinth','timothy',1),
('years-at-ephesus','paul',0),('years-at-ephesus','timothy',1),
('arrest-in-jerusalem','paul',0),('hearing-at-caesarea','paul',0),
('shipwreck-at-malta','paul',0),('shipwreck-at-malta','luke',1),
('patmos-vision','john-son-of-zebedee',0)
) AS v(event_slug,character_slug,ord) ON e.slug=v.event_slug AND e.work_id='10000000-0000-4000-8000-000000000005'
JOIN characters c ON c.slug=v.character_slug AND c.work_id=e.work_id
ON CONFLICT DO NOTHING;

-- Each new event gets at least one primary-text citation, keyed by the era it sits in.
INSERT INTO event_sources(event_id,source_id)
SELECT e.id,s.id FROM events e
JOIN chapters ch ON ch.id=e.chapter_id
JOIN (VALUES
  ('primeval','Genesis'),('patriarchs','Genesis'),('exodus-and-sinai','Exodus'),
  ('wilderness-and-conquest','Numbers'),('wilderness-and-conquest','Joshua'),
  ('judges','Judges'),('judges','Ruth'),
  ('united-monarchy','Samuel'),('divided-kingdoms','Kings'),
  ('prophetic-narrative','Jonah'),('prophetic-narrative','Isaiah'),
  ('judah-and-exile','Kings'),('judah-and-exile','Jeremiah'),('judah-and-exile','Daniel'),
  ('return-and-restoration','Ezra'),('return-and-restoration','Esther'),('return-and-restoration','Nehemiah'),
  ('gospels','Gospel according to Luke'),('gospels','Gospel according to Mark'),
  ('acts','Acts of the Apostles'),('pauline-mission','Acts of the Apostles')
) AS v(chapter_slug,source_title) ON v.chapter_slug=ch.slug
JOIN sources s ON s.title=v.source_title AND s.work_id=e.work_id
WHERE e.work_id='10000000-0000-4000-8000-000000000005' AND e.id::text LIKE '62000000%'
ON CONFLICT DO NOTHING;

-- Journeys: the map draws these as directed trajectories with event anchors.
INSERT INTO routes(id,work_id,slug,layer,certainty,sort_order) VALUES
('b2000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000005','joseph-into-egypt','real','text_explicit',4),
('b2000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000005','wilderness-to-jordan','real','inferred',5),
('b2000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000005','jonah-flight-and-mission','real','text_explicit',6),
('b2000000-0000-4000-8000-000000000004','10000000-0000-4000-8000-000000000005','deportation-to-babylon','real','documented',7),
('b2000000-0000-4000-8000-000000000005','10000000-0000-4000-8000-000000000005','nativity-and-return','real','text_explicit',8),
('b2000000-0000-4000-8000-000000000006','10000000-0000-4000-8000-000000000005','second-missionary-journey','real','text_explicit',9),
('b2000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000005','voyage-to-rome','real','text_explicit',10);

INSERT INTO route_translations(route_id,locale,name,summary,status)
SELECT r.id,v.locale::locale_code,v.name,v.summary,'published' FROM routes r JOIN (VALUES
('joseph-into-egypt','zh-CN','约瑟入埃及','从迦南到尼罗河三角洲的路线。'),('joseph-into-egypt','en','Joseph into Egypt','The route from Canaan to the Nile delta.'),
('wilderness-to-jordan','zh-CN','旷野到约旦河','西奈、加低斯、尼波山到渡河点的推定路线。'),('wilderness-to-jordan','en','Wilderness to the Jordan','The inferred route from Sinai through Kadesh and Nebo to the crossing.'),
('jonah-flight-and-mission','zh-CN','约拿的逃避与使命','约帕、他施方向与尼尼微构成的反向行程。'),('jonah-flight-and-mission','en','Jonah’s flight and mission','Joppa, the Tarshish direction, and Nineveh form a reversed itinerary.'),
('deportation-to-babylon','zh-CN','被掳往巴比伦','耶路撒冷到巴比伦的流放路线。'),('deportation-to-babylon','en','Deportation to Babylon','The route of deportation from Jerusalem to Babylon.'),
('nativity-and-return','zh-CN','诞生叙事的行程','拿撒勒、伯利恒、埃及与返回拿撒勒。'),('nativity-and-return','en','Nativity itinerary','Nazareth, Bethlehem, Egypt, and the return to Nazareth.'),
('second-missionary-journey','zh-CN','第二次宣教旅程','安提阿出发，经腓立比、雅典到哥林多。'),('second-missionary-journey','en','Second missionary journey','From Antioch through Philippi and Athens to Corinth.'),
('voyage-to-rome','zh-CN','前往罗马的航程','该撒利亚、马耳他到罗马的海路。'),('voyage-to-rome','en','Voyage to Rome','The sea route from Caesarea via Malta to Rome.')
) AS v(slug,locale,name,summary) ON r.slug=v.slug AND r.work_id='10000000-0000-4000-8000-000000000005';

INSERT INTO route_waypoints(route_id,location_id,position,event_id)
SELECT r.id,l.id,v.position,e.id FROM routes r JOIN (VALUES
('joseph-into-egypt','canaan-shechem',0,'joseph-sold-into-egypt'),
('joseph-into-egypt','nile-delta',1,'joseph-rises-in-egypt'),
('joseph-into-egypt','goshen',2,'household-settles-in-goshen'),
('wilderness-to-jordan','mount-sinai-traditional',0,'sinai-covenant'),
('wilderness-to-jordan','kadesh-barnea',1,'long-stay-at-kadesh'),
('wilderness-to-jordan','mount-nebo',2,'moses-views-canaan-from-nebo'),
('wilderness-to-jordan','jordan-river-bethany',3,'crossing-the-jordan'),
('wilderness-to-jordan','jericho',4,'fall-of-jericho'),
('jonah-flight-and-mission','joppa',0,'jonah-sails-from-joppa'),
('jonah-flight-and-mission','tarshish-reference',1,'jonah-heads-for-tarshish'),
('jonah-flight-and-mission','nineveh',2,'jonah-to-nineveh'),
('deportation-to-babylon','jerusalem',0,'jerusalem-falls'),
('deportation-to-babylon','harran',1,NULL),
('deportation-to-babylon','babylon',2,'first-deportation-to-babylon'),
('nativity-and-return','nazareth',0,'annunciation-at-nazareth'),
('nativity-and-return','bethlehem',1,'birth-of-jesus'),
('nativity-and-return','nile-delta',2,'flight-to-egypt'),
('nativity-and-return','nazareth',3,'return-to-nazareth'),
('second-missionary-journey','antioch-orontes',0,'barnabas-brings-paul-to-antioch'),
('second-missionary-journey','philippi',1,'crossing-into-macedonia'),
('second-missionary-journey','thessalonica',2,NULL),
('second-missionary-journey','athens',3,'debate-at-athens'),
('second-missionary-journey','corinth',4,'long-stay-at-corinth'),
('second-missionary-journey','ephesus',5,'years-at-ephesus'),
('voyage-to-rome','caesarea-maritima',0,'hearing-at-caesarea'),
('voyage-to-rome','malta',1,'shipwreck-at-malta'),
('voyage-to-rome','rome',2,'paul-arrives-rome')
) AS v(route_slug,location_slug,position,event_slug) ON r.slug=v.route_slug AND r.work_id='10000000-0000-4000-8000-000000000005'
JOIN locations l ON l.slug=v.location_slug AND l.work_id=r.work_id
LEFT JOIN events e ON e.slug=v.event_slug AND e.work_id=r.work_id
ON CONFLICT DO NOTHING;

COMMIT;
