-- 026_relation_labels_refine.sql
-- 圣经作品(work 10000000-0000-4000-8000-000000000005)人物关系标签精修:
-- 将 183 条泛型标签(亲属/配偶/兄弟姐妹/同盟/对立/师承/相关)升级为具体双语标签与一句摘要。
-- 每批约 40 条关系(zh-CN + en 各一行)。摘要口吻为「经文记载」,不作信仰断言。

BEGIN;

-- ============ 批次 1(条目 1–40)============
UPDATE relation_translations t SET label = v.label, summary = v.summary
FROM character_relations r
JOIN characters fc ON fc.id = r.from_character_id
JOIN characters tc ON tc.id = r.to_character_id,
(VALUES
  ('aaron','eleazar-son-of-aaron','family','zh-CN','父子','以利亚撒是亚伦的三子,继任大祭司。'),
  ('aaron','eleazar-son-of-aaron','family','en','Father and son','Eleazar was Aaron’s third son and succeeded him as high priest.'),
  ('aaron','phinehas-son-of-eleazar','family','zh-CN','祖孙','非尼哈是亚伦之孙、以利亚撒之子。'),
  ('aaron','phinehas-son-of-eleazar','family','en','Grandfather and grandson','Phinehas was Aaron’s grandson, the son of Eleazar.'),
  ('aaron','pharaoh-of-the-exodus','adversary','zh-CN','使者与王','亚伦同摩西面见法老,行神迹求容百姓离去。'),
  ('aaron','pharaoh-of-the-exodus','adversary','en','Messenger and king','Aaron confronted Pharaoh with Moses, performing signs to demand Israel’s release.'),
  ('abiathar','adonijah','ally','zh-CN','拥立者','祭司亚比亚他附从亚多尼雅谋夺王位。'),
  ('abiathar','adonijah','ally','en','Supporter','The priest Abiathar backed Adonijah’s bid for the throne.'),
  ('abiram','moses','adversary','zh-CN','叛逆者','亚比兰随可拉抗拒摩西,被地开口吞灭。'),
  ('abiram','moses','adversary','en','Rebel','Abiram joined Korah’s revolt against Moses and was swallowed by the earth.'),
  ('abner','ish-bosheth','ally','zh-CN','元帅与王','押尼珥立伊施波设为王,后与他反目。'),
  ('abner','ish-bosheth','ally','en','Commander and king','Abner made Ish-bosheth king, then broke with him.'),
  ('absalom','amnon','sibling','zh-CN','异母兄弟','暗嫩玷辱他玛后,押沙龙设计杀了他。'),
  ('absalom','amnon','sibling','en','Half brothers','Absalom had Amnon killed for violating Tamar.'),
  ('absalom','tamar-daughter-of-david','sibling','zh-CN','兄妹','他玛受辱后,押沙龙接妹妹到自己家中。'),
  ('absalom','tamar-daughter-of-david','sibling','en','Brother and sister','Absalom took his sister Tamar into his house after her disgrace.'),
  ('achan','joshua','adversary','zh-CN','犯禁者','亚干私取当灭之物,被约书亚在亚割谷处死。'),
  ('achan','joshua','adversary','en','Transgressor','Achan took devoted things and was executed under Joshua in the Valley of Achor.'),
  ('adam','abel','family','zh-CN','父子','亚伯是亚当的次子,牧羊为业。'),
  ('adam','abel','family','en','Father and son','Abel was Adam’s second son, a keeper of sheep.'),
  ('adam','cain','family','zh-CN','父子','该隐是亚当的长子,种地为业。'),
  ('adam','cain','family','en','Father and son','Cain was Adam’s firstborn, a tiller of the ground.'),
  ('adam','eve','spouse','zh-CN','夫妻','受造叙事中的第一对夫妻。'),
  ('adam','eve','spouse','en','Husband and wife','The first couple of the creation narrative.'),
  ('adam','seth','family','zh-CN','父子','塞特是亚当在亚伯死后所生的儿子。'),
  ('adam','seth','family','en','Father and son','Seth was born to Adam after Abel’s death.'),
  ('adonijah','solomon','adversary','zh-CN','争位的兄弟','亚多尼雅自立为王失败,后被所罗门处死。'),
  ('adonijah','solomon','adversary','en','Rival brothers','Adonijah’s bid for the throne failed, and Solomon had him executed.'),
  ('ahab','micaiah','adversary','zh-CN','王与先知','米该雅预言亚哈败亡,被他下在监里。'),
  ('ahab','micaiah','adversary','en','King and prophet','Micaiah foretold Ahab’s defeat and was imprisoned by him.'),
  ('ahab','elisha','adversary','zh-CN','王与先知','以利沙在亚哈年间蒙召,承续以利亚面对王室。'),
  ('ahab','elisha','adversary','en','King and prophet','Elisha was called in Ahab’s reign, continuing Elijah’s stand against the royal house.'),
  ('ahasuerus','esther','spouse','zh-CN','王与王后','以斯帖被立为后,冒死进谏救本族。'),
  ('ahasuerus','esther','spouse','en','King and queen','Esther became queen and risked death to save her people.'),
  ('ahasuerus','haman','ally','zh-CN','王与宠臣','亚哈随鲁高抬哈曼,后因其阴谋将他处死。'),
  ('ahasuerus','haman','ally','en','King and favorite','Ahasuerus exalted Haman, then hanged him when his plot was exposed.'),
  ('ahasuerus','vashti','spouse','zh-CN','王与王后','瓦实提抗命不至,被废去王后之位。'),
  ('ahasuerus','vashti','spouse','en','King and queen','Vashti refused the king’s summons and was deposed.'),
  ('ahaz','hezekiah','family','zh-CN','父子','希西家继承亚哈斯王位,除去父所容的偶像。'),
  ('ahaz','hezekiah','family','en','Father and son','Hezekiah succeeded Ahaz and removed the idolatry his father tolerated.'),
  ('ahithophel','david','ally','zh-CN','谋士与王','亚希多弗曾作大卫的谋士,后随押沙龙背叛。'),
  ('ahithophel','david','ally','en','Counselor and king','Ahithophel was David’s counselor before defecting to Absalom.'),
  ('ahithophel','absalom','ally','zh-CN','谋士','亚希多弗为押沙龙出谋,计不被用便自缢。'),
  ('ahithophel','absalom','ally','en','Counselor','Ahithophel advised Absalom and hanged himself when his counsel was rejected.'),
  ('amnon','tamar-daughter-of-david','sibling','zh-CN','异母兄妹','暗嫩强暴同父异母的妹妹他玛。'),
  ('amnon','tamar-daughter-of-david','sibling','en','Half siblings','Amnon violated his half sister Tamar.'),
  ('amos','amaziah-priest-of-bethel','adversary','zh-CN','先知与祭司','亚玛谢驱逐阿摩司,阿摩司预言他家败落。'),
  ('amos','amaziah-priest-of-bethel','adversary','en','Prophet and priest','Amaziah expelled Amos, who prophesied his household’s ruin.'),
  ('ananias-of-damascus','paul','mentor','zh-CN','施洗者','亚拿尼亚奉差按手使扫罗复明,并为他施洗。'),
  ('ananias-of-damascus','paul','mentor','en','Baptizer','Ananias was sent to restore Saul’s sight and baptize him.'),
  ('ananias-of-jerusalem','sapphira','spouse','zh-CN','夫妻','二人同谋私留卖地价银,先后仆倒而死。'),
  ('ananias-of-jerusalem','sapphira','spouse','en','Husband and wife','The two conspired to withhold proceeds of a sale, and each fell dead.'),
  ('annas','caiaphas','family','zh-CN','岳父与女婿','亚那是该亚法的岳父,先后任大祭司。'),
  ('annas','caiaphas','family','en','Father- and son-in-law','Annas was Caiaphas’ father-in-law; both held the high priesthood.'),
  ('aquila','paul','ally','zh-CN','同工','亚居拉与保罗同以制帐棚为业,一同事奉。'),
  ('aquila','paul','ally','en','Fellow workers','Aquila shared Paul’s tentmaking trade and labored with him.'),
  ('aquila','apollos','mentor','zh-CN','教导者','亚居拉夫妇将神的道给亚波罗讲解更详细。'),
  ('aquila','apollos','mentor','en','Teacher','Aquila and his wife explained the way of God to Apollos more fully.'),
  ('aquila','priscilla','spouse','zh-CN','夫妻','夫妻同工,接待保罗又指教亚波罗。'),
  ('aquila','priscilla','spouse','en','Husband and wife','A married team who hosted Paul and instructed Apollos.'),
  ('artaxerxes','ezra','ally','zh-CN','王与文士','亚达薛西降旨,准以斯拉率民回耶路撒冷。'),
  ('artaxerxes','ezra','ally','en','King and scribe','Artaxerxes decreed Ezra’s return to Jerusalem with his people.'),
  ('artaxerxes','nehemiah','ally','zh-CN','王与酒政','亚达薛西准酒政尼希米回国重建城墙。'),
  ('artaxerxes','nehemiah','ally','en','King and cupbearer','Artaxerxes permitted his cupbearer Nehemiah to rebuild Jerusalem’s walls.'),
  ('athaliah','joash-of-judah','family','zh-CN','祖母与孙','亚她利雅剿灭王室,约阿施被藏匿得存。'),
  ('athaliah','joash-of-judah','family','en','Grandmother and grandson','Athaliah destroyed the royal line, but Joash was hidden and survived.'),
  ('balak','balaam','ally','zh-CN','王与先知','巴勒重金请巴兰咒诅以色列,巴兰却祝福。'),
  ('balak','balaam','ally','en','King and diviner','Balak hired Balaam to curse Israel, but he blessed instead.'),
  ('barak','sisera','adversary','zh-CN','交战的元帅','巴拉率军击溃西西拉的铁车军队。'),
  ('barak','sisera','adversary','en','Opposing commanders','Barak routed Sisera’s chariot army.'),
  ('ben-hadad','ahab','adversary','zh-CN','交战之王','便哈达围攻撒玛利亚,两度败于亚哈。'),
  ('ben-hadad','ahab','adversary','en','Warring kings','Ben-hadad besieged Samaria and was twice defeated by Ahab.'),
  ('caiaphas','jesus','adversary','zh-CN','主审的大祭司','该亚法主持公会审问耶稣,定他说僭妄的话。'),
  ('caiaphas','jesus','adversary','en','Presiding high priest','Caiaphas presided over the council that condemned Jesus for blasphemy.'),
  ('cain','abel','sibling','zh-CN','兄弟','该隐因嫉妒在田间杀了弟弟亚伯。'),
  ('cain','abel','sibling','en','Brothers','Cain killed his brother Abel in the field out of jealousy.'),
  ('daniel','shadrach','ally','zh-CN','患难同伴','二人同被掳到巴比伦,同侍王廷不失所守。'),
  ('daniel','shadrach','ally','en','Companions in exile','Fellow exiles in Babylon who served the court without compromise.'),
  ('darius-the-mede','daniel','ally','zh-CN','王与宠臣','大流士重用但以理,狮坑获救后更敬重他。'),
  ('darius-the-mede','daniel','ally','en','King and favored official','Darius promoted Daniel and honored him more after the lions’ den.')
) AS v(fslug, tslug, rtype, locale, label, summary)
WHERE t.relation_id = r.id AND t.locale = v.locale::locale_code
  AND fc.slug = v.fslug AND tc.slug = v.tslug AND r.relation_type = v.rtype
  AND r.work_id = '10000000-0000-4000-8000-000000000005';

-- ============ 批次 2(条目 41–80)============
UPDATE relation_translations t SET label = v.label, summary = v.summary
FROM character_relations r
JOIN characters fc ON fc.id = r.from_character_id
JOIN characters tc ON tc.id = r.to_character_id,
(VALUES
  ('dathan','moses','adversary','zh-CN','叛逆者','大坍随可拉抗拒摩西,被地开口吞灭。'),
  ('dathan','moses','adversary','en','Rebel','Dathan joined Korah’s revolt against Moses and perished when the earth opened.'),
  ('dathan','abiram','sibling','zh-CN','兄弟','二人同为以利押之子,一同背叛摩西。'),
  ('dathan','abiram','sibling','en','Brothers','Sons of Eliab who rebelled against Moses together.'),
  ('david','tamar-daughter-of-david','family','zh-CN','父女','他玛是大卫的女儿,受辱后住押沙龙家。'),
  ('david','tamar-daughter-of-david','family','en','Father and daughter','Tamar was David’s daughter; after her disgrace she lived with Absalom.'),
  ('david','michal','spouse','zh-CN','夫妻','米甲曾爱大卫,后因他在约柜前跳舞轻视他。'),
  ('david','michal','spouse','en','Husband and wife','Michal loved David, yet later despised him for dancing before the ark.'),
  ('david','mephibosheth','ally','zh-CN','恩主与受恩者','大卫因约拿单恩待米非波设,使他同席吃饭。'),
  ('david','mephibosheth','ally','en','Benefactor and ward','For Jonathan’s sake David gave Mephibosheth a place at his table.'),
  ('david','adonijah','family','zh-CN','父子','亚多尼雅是大卫之子,趁父年迈自立为王。'),
  ('david','adonijah','family','en','Father and son','Adonijah, David’s son, made himself king in his father’s old age.'),
  ('david','uriah','other','zh-CN','王与勇士','大卫夺乌利亚之妻,又借敌刀害死他。'),
  ('david','uriah','other','en','King and soldier','David took Uriah’s wife and had him killed by enemy hands.'),
  ('david','amnon','family','zh-CN','父子','暗嫩是大卫长子,行恶事后被押沙龙杀。'),
  ('david','amnon','family','en','Father and son','Amnon was David’s firstborn, slain by Absalom for his crime.'),
  ('deborah','barak','ally','zh-CN','先知与元帅','底波拉召巴拉出战西西拉,并与他同往。'),
  ('deborah','barak','ally','en','Prophetess and commander','Deborah summoned Barak to battle Sisera and went with him.'),
  ('demetrius-the-silversmith','paul','adversary','zh-CN','煽动者','底米丢因银龛生意受损,煽动众人抵挡保罗。'),
  ('demetrius-the-silversmith','paul','adversary','en','Instigator','Demetrius stirred up Ephesus against Paul over his silver-shrine trade.'),
  ('ebed-melech','jeremiah','ally','zh-CN','营救者','以伯米勒求王开恩,把耶利米从淤泥坑救出。'),
  ('ebed-melech','jeremiah','ally','en','Rescuer','Ebed-melech won the king’s leave to draw Jeremiah from the miry pit.'),
  ('ehud','eglon','adversary','zh-CN','刺杀者与王','以笏假献贡物,用左手剑刺杀摩押王。'),
  ('ehud','eglon','adversary','en','Assassin and king','Ehud brought tribute, then killed the Moabite king with a left-handed thrust.'),
  ('eli','samuel','mentor','zh-CN','师徒','撒母耳自幼在以利面前学习事奉耶和华。'),
  ('eli','samuel','mentor','en','Mentor and pupil','Samuel ministered before the LORD under Eli from childhood.'),
  ('elijah','widow-of-zarephath','ally','zh-CN','先知与寡妇','寡妇供养以利亚,以利亚使她儿子复活。'),
  ('elijah','widow-of-zarephath','ally','en','Prophet and widow','The widow fed Elijah, and he restored her son to life.'),
  ('elijah','jezebel','adversary','zh-CN','先知与王后','耶洗别追杀以利亚,以利亚预言她的结局。'),
  ('elijah','jezebel','adversary','en','Prophet and queen','Jezebel sought Elijah’s life, and he foretold her end.'),
  ('elijah','elisha','mentor','zh-CN','师徒','以利沙接续以利亚,求得感动他的灵加倍。'),
  ('elijah','elisha','mentor','en','Mentor and successor','Elisha succeeded Elijah, asking a double portion of his spirit.'),
  ('elisha','shunammite-woman','ally','zh-CN','先知与款待者','书念妇人接待以利沙,以利沙使她儿子复活。'),
  ('elisha','shunammite-woman','ally','en','Prophet and hostess','The Shunammite housed Elisha, and he raised her son.'),
  ('elisha','gehazi','mentor','zh-CN','先知与仆人','基哈西服事以利沙,因贪财受咒长大麻风。'),
  ('elisha','gehazi','mentor','en','Prophet and servant','Gehazi served Elisha but was struck with leprosy for his greed.'),
  ('elisha','jehu','other','zh-CN','膏立者与王','以利沙差门徒膏耶户为以色列王。'),
  ('elisha','jehu','other','en','Anointer and king','Elisha sent a disciple to anoint Jehu king of Israel.'),
  ('elkanah','hannah','spouse','zh-CN','夫妻','以利加拿爱哈拿,每年同上示罗敬拜。'),
  ('elkanah','hannah','spouse','en','Husband and wife','Elkanah loved Hannah and went up with her yearly to Shiloh.'),
  ('elkanah','samuel','family','zh-CN','父子','撒母耳是以利加拿与哈拿祷告所得之子。'),
  ('elkanah','samuel','family','en','Father and son','Samuel was born to Elkanah and Hannah in answer to prayer.'),
  ('enoch','methuselah','family','zh-CN','父子','玛土撒拉是以诺之子,活了九百六十九岁。'),
  ('enoch','methuselah','family','en','Father and son','Methuselah, Enoch’s son, lived 969 years.'),
  ('eve','seth','family','zh-CN','母子','夏娃生塞特,说神另给她立了一个后裔。'),
  ('eve','seth','family','en','Mother and son','Eve bore Seth, saying God had appointed another offspring.'),
  ('eve','abel','family','zh-CN','母子','亚伯是夏娃的次子,被兄该隐所杀。'),
  ('eve','abel','family','en','Mother and son','Abel, Eve’s second son, was slain by his brother Cain.'),
  ('eve','cain','family','zh-CN','母子','夏娃生该隐,说耶和华使她得了一个男子。'),
  ('eve','cain','family','en','Mother and son','Eve bore Cain, saying she had gotten a man with the LORD’s help.'),
  ('ezra','nehemiah','ally','zh-CN','同工','二人同在耶路撒冷推动重建与宣读律法。'),
  ('ezra','nehemiah','ally','en','Fellow workers','Together in Jerusalem they led rebuilding and the reading of the Law.'),
  ('felix','paul','other','zh-CN','巡抚与囚犯','腓力斯多次听保罗讲论,却把他留在监里。'),
  ('felix','paul','other','en','Governor and prisoner','Felix often heard Paul speak yet left him in custody.'),
  ('festus','paul','other','zh-CN','巡抚与囚犯','非斯都审理保罗的案件,准他上告凯撒。'),
  ('festus','paul','other','en','Governor and prisoner','Festus heard Paul’s case and granted his appeal to Caesar.'),
  ('gallio','paul','other','zh-CN','方伯与被告','犹太人向迦流控告保罗,迦流不予受理。'),
  ('gallio','paul','other','en','Proconsul and accused','Gallio dismissed the charges brought against Paul.'),
  ('gamaliel','paul','mentor','zh-CN','师徒','保罗自述在迦玛列门下按律法受教。'),
  ('gamaliel','paul','mentor','en','Teacher and student','Paul said he was trained in the Law at Gamaliel’s feet.'),
  ('gedaliah','jeremiah','ally','zh-CN','省长与先知','城陷后,耶利米蒙准住在基大利那里。'),
  ('gedaliah','jeremiah','ally','en','Governor and prophet','After the fall of Jerusalem, Jeremiah was entrusted to Gedaliah’s care.'),
  ('haggai','zerubbabel','mentor','zh-CN','先知与省长','哈该传神的话,激励所罗巴伯重建圣殿。'),
  ('haggai','zerubbabel','mentor','en','Prophet and governor','Haggai’s oracles stirred Zerubbabel to rebuild the temple.'),
  ('ham','japheth','sibling','zh-CN','兄弟','二人同为挪亚之子,一同出方舟。'),
  ('ham','japheth','sibling','en','Brothers','Sons of Noah who came out of the ark together.'),
  ('haman','esther','adversary','zh-CN','仇敌与王后','哈曼谋灭犹大人,以斯帖设宴揭发他。'),
  ('haman','esther','adversary','en','Enemy and queen','Haman plotted genocide; Esther exposed him at her banquet.'),
  ('haman','mordecai','adversary','zh-CN','仇敌','末底改不跪拜哈曼,哈曼所立木架反挂自己。'),
  ('haman','mordecai','adversary','en','Arch-enemies','Mordecai would not bow; Haman hung on the gallows he built for him.'),
  ('hannah','samuel','family','zh-CN','母子','哈拿祷告得子,断奶后将撒母耳献于耶和华。'),
  ('hannah','samuel','family','en','Mother and son','Hannah prayed for a son and dedicated Samuel to the LORD.'),
  ('hazael','jehu','adversary','zh-CN','交战之王','耶户年间,哈薛屡败以色列,夺约旦河东地。'),
  ('hazael','jehu','adversary','en','Warring kings','In Jehu’s days Hazael defeated Israel and seized land east of the Jordan.'),
  ('hazael','ben-hadad','adversary','zh-CN','弑主的臣仆','哈薛闷死病中的便哈达,篡了他的王位。'),
  ('hazael','ben-hadad','adversary','en','Usurping servant','Hazael smothered the ailing Ben-hadad and took his throne.'),
  ('herod-agrippa-i','herod-agrippa-ii','family','zh-CN','父子','亚基帕二世是亚基帕一世之子,承袭王权。'),
  ('herod-agrippa-i','herod-agrippa-ii','family','en','Father and son','Agrippa II succeeded his father Agrippa I in rule.'),
  ('herod-agrippa-i','peter','adversary','zh-CN','王与使徒','希律捉拿彼得下监,彼得被天使领出。'),
  ('herod-agrippa-i','peter','adversary','en','King and apostle','Herod jailed Peter, who was led out by an angel.')
) AS v(fslug, tslug, rtype, locale, label, summary)
WHERE t.relation_id = r.id AND t.locale = v.locale::locale_code
  AND fc.slug = v.fslug AND tc.slug = v.tslug AND r.relation_type = v.rtype
  AND r.work_id = '10000000-0000-4000-8000-000000000005';

-- ============ 批次 3(条目 81–120)============
UPDATE relation_translations t SET label = v.label, summary = v.summary
FROM character_relations r
JOIN characters fc ON fc.id = r.from_character_id
JOIN characters tc ON tc.id = r.to_character_id,
(VALUES
  ('herod-agrippa-ii','paul','other','zh-CN','王与囚犯','亚基帕听保罗分诉,说他几乎被劝作基督徒。'),
  ('herod-agrippa-ii','paul','other','en','King and prisoner','Agrippa heard Paul’s defense and said he was almost persuaded.'),
  ('herod-agrippa-ii','bernice','sibling','zh-CN','兄妹','兄妹二人同席听保罗申诉。'),
  ('herod-agrippa-ii','bernice','sibling','en','Brother and sister','The royal siblings sat together at Paul’s hearing.'),
  ('herod-antipas','herodias','spouse','zh-CN','夫妻','安提帕娶兄弟之妻希罗底,受约翰责备。'),
  ('herod-antipas','herodias','spouse','en','Husband and wife','Antipas married his brother’s wife Herodias, drawing John’s rebuke.'),
  ('herod-antipas','john-the-baptist','adversary','zh-CN','王与先知','约翰责备希律娶弟妇,被囚后遭斩首。'),
  ('herod-antipas','john-the-baptist','adversary','en','King and prophet','John rebuked Herod’s marriage and was imprisoned and beheaded.'),
  ('herodias','john-the-baptist','adversary','zh-CN','怀恨者与先知','希罗底怀恨约翰,借女儿之舞求他的头。'),
  ('herodias','john-the-baptist','adversary','en','Grudge-bearer and prophet','Herodias nursed a grudge and claimed John’s head through her daughter’s dance.'),
  ('herod-the-great','herod-agrippa-i','family','zh-CN','祖孙','亚基帕一世是大希律之孙。'),
  ('herod-the-great','herod-agrippa-i','family','en','Grandfather and grandson','Agrippa I was Herod the Great’s grandson.'),
  ('herod-the-great','herod-antipas','family','zh-CN','父子','安提帕是大希律之子,分封管理加利利。'),
  ('herod-the-great','herod-antipas','family','en','Father and son','Antipas, Herod’s son, ruled Galilee as tetrarch.'),
  ('hezekiah','manasseh-king-of-judah','family','zh-CN','父子','玛拿西十二岁继承父亲希西家的王位。'),
  ('hezekiah','manasseh-king-of-judah','family','en','Father and son','Manasseh succeeded his father Hezekiah at age twelve.'),
  ('hiram-of-tyre','david','ally','zh-CN','友邦之王','希兰遣使运香柏木,为大卫建造宫殿。'),
  ('hiram-of-tyre','david','ally','en','Allied kings','Hiram sent cedar and craftsmen to build David a palace.'),
  ('hiram-of-tyre','solomon','ally','zh-CN','友邦之王','希兰供应木料与工匠,助所罗门建圣殿。'),
  ('hiram-of-tyre','solomon','ally','en','Allied kings','Hiram supplied timber and workmen for Solomon’s temple.'),
  ('hosea','gomer','spouse','zh-CN','夫妻','何西阿奉命娶歌篾,婚姻作以色列的表记。'),
  ('hosea','gomer','spouse','en','Husband and wife','Hosea was told to marry Gomer, their marriage a sign for Israel.'),
  ('huldah','josiah','mentor','zh-CN','女先知与王','约西亚差人求问户勒大,她传达神的话。'),
  ('huldah','josiah','mentor','en','Prophetess and king','Josiah sent to inquire of Huldah, who delivered God’s word.'),
  ('hur','moses','ally','zh-CN','扶助者','亚玛力之战中,户珥与亚伦扶住摩西的手。'),
  ('hur','moses','ally','en','Supporter','With Aaron, Hur held up Moses’ hands against Amalek.'),
  ('isaiah','ahaz','other','zh-CN','先知与王','以赛亚劝亚哈斯求兆头,传以马内利之兆。'),
  ('isaiah','ahaz','other','en','Prophet and king','Isaiah urged Ahaz to ask a sign and gave the Immanuel prophecy.'),
  ('isaiah','micah-of-moresheth','other','zh-CN','同代先知','二人同时代在犹大传讲信息。'),
  ('isaiah','micah-of-moresheth','other','en','Contemporary prophets','Both prophesied in Judah in the same era.'),
  ('jabin-of-hazor','joshua','adversary','zh-CN','交战对手','耶宾联合北方诸王攻约书亚,在米伦水边败亡。'),
  ('jabin-of-hazor','joshua','adversary','en','Battlefield foes','Jabin led the northern kings against Joshua and fell at the waters of Merom.'),
  ('jacob','reuben','family','zh-CN','父子','吕便是雅各长子,因污秽父榻失长子名分。'),
  ('jacob','reuben','family','en','Father and son','Reuben, Jacob’s firstborn, forfeited his birthright by defiling his father’s bed.'),
  ('jacob','dinah','family','zh-CN','父女','底拿是雅各与利亚所生的女儿。'),
  ('jacob','dinah','family','en','Father and daughter','Dinah was Jacob’s daughter by Leah.'),
  ('jael','sisera','adversary','zh-CN','击杀者与逃将','西西拉逃入雅亿帐棚,雅亿用橛子钉死他。'),
  ('jael','sisera','adversary','en','Slayer and fugitive','Sisera fled to Jael’s tent, where she killed him with a tent peg.'),
  ('james-son-of-zebedee','john-son-of-zebedee','sibling','zh-CN','兄弟','同为西庇太之子,一同蒙耶稣呼召。'),
  ('james-son-of-zebedee','john-son-of-zebedee','sibling','en','Brothers','Sons of Zebedee, called together by Jesus.'),
  ('jehoiada-the-priest','joash-of-judah','mentor','zh-CN','祭司与幼王','耶何耶大藏匿并立约阿施为王,在世时教导他。'),
  ('jehoiada-the-priest','joash-of-judah','mentor','en','Priest and boy king','Jehoiada hid Joash, crowned him, and taught him while he lived.'),
  ('jehoiakim','zedekiah','sibling','zh-CN','兄弟','二人都是约西亚之子,先后作犹大王。'),
  ('jehoiakim','zedekiah','sibling','en','Brothers','Both sons of Josiah who reigned over Judah in turn.'),
  ('jehoiakim','jeremiah','adversary','zh-CN','王与先知','约雅敬烧毁耶利米的书卷,并追索先知。'),
  ('jehoiakim','jeremiah','adversary','en','King and prophet','Jehoiakim burned Jeremiah’s scroll and sought his arrest.'),
  ('jehoshaphat','ahab','ally','zh-CN','结盟之王','约沙法与亚哈结盟,同往基列的拉末争战。'),
  ('jehoshaphat','ahab','ally','en','Allied kings','Jehoshaphat allied with Ahab and joined him at Ramoth-gilead.'),
  ('jehu','jezebel','adversary','zh-CN','讨伐者与王后','耶户下令把耶洗别从窗户扔下,应验预言。'),
  ('jehu','jezebel','adversary','en','Avenger and queen','Jehu ordered Jezebel thrown from the window, fulfilling prophecy.'),
  ('jeremiah','nebuchadnezzar','adversary','zh-CN','先知与征服者','耶利米预言尼布甲尼撒必攻陷耶路撒冷。'),
  ('jeremiah','nebuchadnezzar','adversary','en','Prophet and conqueror','Jeremiah foretold Nebuchadnezzar’s capture of Jerusalem.'),
  ('jeremiah','baruch','ally','zh-CN','先知与书记','巴录笔录耶利米口授的预言,并代为宣读。'),
  ('jeremiah','baruch','ally','en','Prophet and scribe','Baruch wrote Jeremiah’s dictated prophecies and read them aloud.'),
  ('jesus','james-son-of-zebedee','mentor','zh-CN','师徒','耶稣呼召雅各撇下渔船,立他为使徒。'),
  ('jesus','james-son-of-zebedee','mentor','en','Master and disciple','Jesus called James from his nets and made him an apostle.'),
  ('jesus','philip-the-apostle','mentor','zh-CN','师徒','耶稣呼召腓力跟从他,列在十二使徒中。'),
  ('jesus','philip-the-apostle','mentor','en','Master and disciple','Jesus called Philip to follow him among the Twelve.'),
  ('jesus','matthew-the-tax-collector','mentor','zh-CN','师徒','耶稣呼召税吏马太离开税关跟从他。'),
  ('jesus','matthew-the-tax-collector','mentor','en','Master and disciple','Jesus called Matthew from the tax booth to follow him.'),
  ('jesus','thomas','mentor','zh-CN','师徒','多马疑而后信,耶稣向他显明钉痕。'),
  ('jesus','thomas','mentor','en','Master and disciple','Jesus showed doubting Thomas his wounds, and he believed.'),
  ('jesus','nicodemus','mentor','zh-CN','夫子与求道者','尼哥底母夜里来见耶稣,求问重生之道。'),
  ('jesus','nicodemus','mentor','en','Teacher and seeker','Nicodemus came to Jesus by night to ask about new birth.'),
  ('jesus','zacchaeus','other','zh-CN','夫子与税吏','耶稣住进撒该家,撒该悔改偿还所欺。'),
  ('jesus','zacchaeus','other','en','Teacher and tax collector','Jesus lodged with Zacchaeus, who repented and made restitution.'),
  ('jethro','zipporah','family','zh-CN','父女','西坡拉是米甸祭司叶忒罗的女儿。'),
  ('jethro','zipporah','family','en','Father and daughter','Zipporah was the daughter of Jethro, priest of Midian.'),
  ('joab','absalom','adversary','zh-CN','元帅与王子','押沙龙悬挂树上,约押用短枪刺透他。'),
  ('joab','absalom','adversary','en','Commander and prince','Joab thrust darts through Absalom as he hung in the oak.'),
  ('joab','abner','adversary','zh-CN','敌对元帅','约押为报兄弟之仇,在城门刺杀押尼珥。'),
  ('joab','abner','adversary','en','Rival commanders','Joab murdered Abner at the gate to avenge his brother.'),
  ('jochebed','moses','family','zh-CN','母子','约基别藏婴孩摩西三月,后又为他乳养。'),
  ('jochebed','moses','family','en','Mother and son','Jochebed hid the infant Moses and later nursed him.'),
  ('jonah','jeroboam-ii','other','zh-CN','先知与王','约拿曾预言耶罗波安二世收复以色列边界。'),
  ('jonah','jeroboam-ii','other','en','Prophet and king','Jonah foretold Jeroboam II’s restoration of Israel’s borders.'),
  ('jonah','king-of-nineveh','other','zh-CN','先知与王','尼尼微王听约拿宣告后,下位披麻悔改。'),
  ('jonah','king-of-nineveh','other','en','Prophet and king','At Jonah’s warning the king of Nineveh repented in sackcloth.'),
  ('jonathan','mephibosheth','family','zh-CN','父子','米非波设是约拿单之子,五岁时摔瘸了腿。'),
  ('jonathan','mephibosheth','family','en','Father and son','Mephibosheth, Jonathan’s son, was lamed at age five.')
) AS v(fslug, tslug, rtype, locale, label, summary)
WHERE t.relation_id = r.id AND t.locale = v.locale::locale_code
  AND fc.slug = v.fslug AND tc.slug = v.tslug AND r.relation_type = v.rtype
  AND r.work_id = '10000000-0000-4000-8000-000000000005';

-- ============ 批次 4(条目 121–160)============
UPDATE relation_translations t SET label = v.label, summary = v.summary
FROM character_relations r
JOIN characters fc ON fc.id = r.from_character_id
JOIN characters tc ON tc.id = r.to_character_id,
(VALUES
  ('joseph-of-arimathea','jesus','ally','zh-CN','暗中的门徒','约瑟求得耶稣的身体,安放在自己的新坟墓。'),
  ('joseph-of-arimathea','jesus','ally','en','Secret disciple','Joseph obtained Jesus’ body and laid it in his own new tomb.'),
  ('joshua','rahab','ally','zh-CN','保全者','喇合藏匿探子,约书亚攻城时保全她全家。'),
  ('joshua','rahab','ally','en','Protector','Rahab hid the spies, and Joshua spared her household at Jericho.'),
  ('joshua','caleb','ally','zh-CN','同心探子','二人同窥迦南回报好信,得进应许之地。'),
  ('joshua','caleb','ally','en','Fellow spies','The two spies who brought a good report and entered the land.'),
  ('josiah','zedekiah','family','zh-CN','父子','西底家是约西亚之子,犹大末代的王。'),
  ('josiah','zedekiah','family','en','Father and son','Zedekiah, Josiah’s son, was Judah’s last king.'),
  ('josiah','jehoiakim','family','zh-CN','父子','约雅敬是约西亚之子,由法老立为王。'),
  ('josiah','jehoiakim','family','en','Father and son','Jehoiakim, Josiah’s son, was set on the throne by Pharaoh.'),
  ('julius-the-centurion','paul','ally','zh-CN','押解百夫长','犹流宽待保罗,海难中保全他的性命。'),
  ('julius-the-centurion','paul','ally','en','Escorting centurion','Julius treated Paul kindly and spared his life in the shipwreck.'),
  ('korah','moses','adversary','zh-CN','叛党首领','可拉聚众攻击摩西、亚伦,被地吞灭。'),
  ('korah','moses','adversary','en','Rebellion leader','Korah gathered a faction against Moses and Aaron and was swallowed by the earth.'),
  ('laban','rachel','family','zh-CN','父女','拉结是拉班的小女儿,雅各为她服事七年。'),
  ('laban','rachel','family','en','Father and daughter','Rachel was Laban’s younger daughter, for whom Jacob served seven years.'),
  ('laban','leah','family','zh-CN','父女','拉班以长女利亚先嫁雅各,顶替拉结。'),
  ('laban','leah','family','en','Father and daughter','Laban gave his elder daughter Leah to Jacob in Rachel’s place.'),
  ('laban','jacob','family','zh-CN','舅父与外甥','拉班是雅各的舅父,后又将两女嫁他为妻。'),
  ('laban','jacob','family','en','Uncle and nephew','Laban was Jacob’s uncle and later his father-in-law twice over.'),
  ('lamech-father-of-noah','noah','family','zh-CN','父子','拉麦生挪亚,盼他使人从劳苦中得安慰。'),
  ('lamech-father-of-noah','noah','family','en','Father and son','Lamech named Noah, hoping for comfort from toil.'),
  ('manasseh-king-of-judah','josiah','family','zh-CN','祖孙','约西亚是玛拿西之孙,八岁登基作王。'),
  ('manasseh-king-of-judah','josiah','family','en','Grandfather and grandson','Josiah, Manasseh’s grandson, became king at eight.'),
  ('manoah','samson','family','zh-CN','父子','参孙是玛挪亚之子,自出生归作拿细耳人。'),
  ('manoah','samson','family','en','Father and son','Samson was born to Manoah and set apart as a Nazirite from birth.'),
  ('melchizedek','abraham','ally','zh-CN','祝福者','麦基洗德为亚伯兰祝福,亚伯兰献十分之一。'),
  ('melchizedek','abraham','ally','en','Blessing priest','Melchizedek blessed Abram, who gave him a tenth of all.'),
  ('meshach','abednego','ally','zh-CN','患难同伴','二人同拒拜金像,一同在火窑中蒙保全。'),
  ('meshach','abednego','ally','en','Companions in trial','Together they refused the image and were preserved in the furnace.'),
  ('methuselah','lamech-father-of-noah','family','zh-CN','父子','拉麦是玛土撒拉之子,挪亚之父。'),
  ('methuselah','lamech-father-of-noah','family','en','Father and son','Lamech was Methuselah’s son and Noah’s father.'),
  ('moses','pharaoh-of-the-exodus','adversary','zh-CN','先知与王','摩西屡次要求法老容百姓离去,十灾随之。'),
  ('moses','pharaoh-of-the-exodus','adversary','en','Prophet and king','Moses repeatedly demanded Israel’s release as ten plagues fell.'),
  ('moses','zipporah','spouse','zh-CN','夫妻','摩西在米甸娶西坡拉,生了两个儿子。'),
  ('moses','zipporah','spouse','en','Husband and wife','Moses married Zipporah in Midian and had two sons.'),
  ('moses','gershom','family','zh-CN','父子','革舜是摩西长子,名字纪念寄居异乡。'),
  ('moses','gershom','family','en','Father and son','Gershom, Moses’ firstborn, was named for his father’s sojourning.'),
  ('moses','caleb','ally','zh-CN','领袖与探子','迦勒受摩西差派窥地,摩西应许他得希伯仑。'),
  ('moses','caleb','ally','en','Leader and spy','Moses sent Caleb to spy the land and promised him Hebron.'),
  ('moses','joshua','mentor','zh-CN','师徒','约书亚自幼作摩西帮手,后继任领以色列。'),
  ('moses','joshua','mentor','en','Mentor and successor','Joshua served Moses from youth and succeeded him as leader.'),
  ('naaman','elisha','ally','zh-CN','元帅与先知','乃缦照以利沙的话沐浴约旦河,麻风得洁净。'),
  ('naaman','elisha','ally','en','Commander and prophet','Naaman washed in the Jordan at Elisha’s word and was cleansed.'),
  ('naomi','ruth','family','zh-CN','婆媳','路得随婆婆拿俄米回伯利恒,不离不弃。'),
  ('naomi','ruth','family','en','Mother- and daughter-in-law','Ruth clung to Naomi and returned with her to Bethlehem.'),
  ('nebuchadnezzar','zedekiah','adversary','zh-CN','宗主与藩王','西底家背叛尼布甲尼撒,城破被剜眼掳走。'),
  ('nebuchadnezzar','zedekiah','adversary','en','Overlord and vassal','Zedekiah rebelled and was blinded and carried off when the city fell.'),
  ('nebuchadnezzar','belshazzar','family','zh-CN','先王与后王','但以理书称尼布甲尼撒为伯沙撒之父。'),
  ('nebuchadnezzar','belshazzar','family','en','Predecessor and successor','Daniel calls Nebuchadnezzar the father of Belshazzar.'),
  ('nimrod','ham','family','zh-CN','孙与祖父','宁录是含之孙、古实之子,英勇的猎户。'),
  ('nimrod','ham','family','en','Grandson and grandfather','Nimrod, Ham’s grandson through Cush, was a mighty hunter.'),
  ('noah','shem','family','zh-CN','父子','闪是挪亚之子,得父亲的祝福。'),
  ('noah','shem','family','en','Father and son','Shem, Noah’s son, received his father’s blessing.'),
  ('noah','ham','family','zh-CN','父子','含见父赤身外传,挪亚醒后咒诅其子迦南。'),
  ('noah','ham','family','en','Father and son','Ham told of his father’s nakedness; Noah cursed his son Canaan.'),
  ('noah','japheth','family','zh-CN','父子','雅弗与闪遮盖父亲,同得祝福。'),
  ('noah','japheth','family','en','Father and son','Japheth covered his father with Shem and shared the blessing.'),
  ('og-king-of-bashan','moses','adversary','zh-CN','交战对手','巴珊王噩出来迎战,被以色列人击杀。'),
  ('og-king-of-bashan','moses','adversary','en','Battlefield foes','Og of Bashan marched out to battle and was struck down by Israel.'),
  ('omri','ahab','family','zh-CN','父子','亚哈接续父亲暗利作以色列王。'),
  ('omri','ahab','family','en','Father and son','Ahab succeeded his father Omri as king of Israel.'),
  ('paul','eutychus','other','zh-CN','使徒与少年人','犹推古听道坠楼,保罗抱住他,他就活了。'),
  ('paul','eutychus','other','en','Apostle and youth','Eutychus fell from a window; Paul embraced him and he lived.'),
  ('peter','matthias','ally','zh-CN','使徒同列','彼得主持掣签,马提亚补入使徒之列。'),
  ('peter','matthias','ally','en','Fellow apostles','Under Peter’s lead, Matthias was chosen to join the apostles.'),
  ('peter','tabitha','other','zh-CN','使徒与女徒','彼得在约帕祷告,使大比大从死里复活。'),
  ('peter','tabitha','other','en','Apostle and disciple','At Joppa Peter prayed and raised Tabitha from death.'),
  ('peter','cornelius','ally','zh-CN','使徒与百夫长','彼得往哥尼流家传道,圣灵降在外邦人身上。'),
  ('peter','cornelius','ally','en','Apostle and centurion','Peter preached at Cornelius’ house, and the Spirit fell on Gentiles.'),
  ('pharaoh-of-joseph','joseph-son-of-jacob','ally','zh-CN','王与宰相','法老立约瑟治理埃及全地。'),
  ('pharaoh-of-joseph','joseph-son-of-jacob','ally','en','King and vizier','Pharaoh set Joseph over all the land of Egypt.'),
  ('pharaohs-daughter','moses','family','zh-CN','养母与养子','法老的女儿从河中救起摩西,收养为子。'),
  ('pharaohs-daughter','moses','family','en','Adoptive mother and son','Pharaoh’s daughter drew Moses from the river and raised him as her son.'),
  ('philip-the-evangelist','ethiopian-eunuch','mentor','zh-CN','传道与施洗','腓利向太监讲解以赛亚书,并为他施洗。'),
  ('philip-the-evangelist','ethiopian-eunuch','mentor','en','Evangelist and convert','Philip explained Isaiah to the eunuch and baptized him.'),
  ('potiphar','joseph-son-of-jacob','other','zh-CN','主人与仆人','波提乏派约瑟管家,后听妻言将他下监。'),
  ('potiphar','joseph-son-of-jacob','other','en','Master and servant','Potiphar set Joseph over his house, then jailed him on his wife’s word.'),
  ('potiphars-wife','joseph-son-of-jacob','adversary','zh-CN','诬告者','约瑟拒绝引诱,波提乏之妻诬告他下监。'),
  ('potiphars-wife','joseph-son-of-jacob','adversary','en','False accuser','Joseph refused her advances and was imprisoned on her false charge.')
) AS v(fslug, tslug, rtype, locale, label, summary)
WHERE t.relation_id = r.id AND t.locale = v.locale::locale_code
  AND fc.slug = v.fslug AND tc.slug = v.tslug AND r.relation_type = v.rtype
  AND r.work_id = '10000000-0000-4000-8000-000000000005';

-- ============ 批次 5(条目 161–183)============
UPDATE relation_translations t SET label = v.label, summary = v.summary
FROM character_relations r
JOIN characters fc ON fc.id = r.from_character_id
JOIN characters tc ON tc.id = r.to_character_id,
(VALUES
  ('priscilla','paul','ally','zh-CN','同工','百基拉与丈夫接待保罗,一同制帐棚事奉。'),
  ('priscilla','paul','ally','en','Fellow workers','Priscilla and her husband hosted Paul and shared his trade.'),
  ('priscilla','apollos','mentor','zh-CN','教导者','百基拉夫妇将神的道给亚波罗讲解更详细。'),
  ('priscilla','apollos','mentor','en','Teacher','Priscilla and Aquila explained the way of God to Apollos more fully.'),
  ('publius','paul','ally','zh-CN','款待者','部百流接待船难的保罗,保罗医好他父亲。'),
  ('publius','paul','ally','en','Host','Publius hosted the shipwrecked Paul, who healed his father.'),
  ('queen-of-sheba','solomon','other','zh-CN','远来求问者','示巴女王听闻所罗门智慧,远道用难题试他。'),
  ('queen-of-sheba','solomon','other','en','Royal visitor','The queen came from afar to test Solomon with hard questions.'),
  ('sanballat','tobiah','ally','zh-CN','同谋','二人联手讥诮拦阻尼希米重建城墙。'),
  ('sanballat','tobiah','ally','en','Co-conspirators','Together they mocked and opposed Nehemiah’s wall-building.'),
  ('sanballat','nehemiah','adversary','zh-CN','阻挠者','参巴拉讥诮恐吓,企图拦阻重建城墙。'),
  ('sanballat','nehemiah','adversary','en','Obstructor','Sanballat mocked and schemed to halt the wall’s rebuilding.'),
  ('saul','ish-bosheth','family','zh-CN','父子','伊施波设是扫罗之子,父死后被立为王。'),
  ('saul','ish-bosheth','family','en','Father and son','Ish-bosheth, Saul’s son, was made king after his father’s death.'),
  ('saul','michal','family','zh-CN','父女','扫罗将女儿米甲嫁给大卫,意图借此害他。'),
  ('saul','michal','family','en','Father and daughter','Saul gave Michal to David, intending her as a snare.'),
  ('sennacherib','hezekiah','adversary','zh-CN','入侵者与王','西拿基立围困耶路撒冷,其军一夜溃败。'),
  ('sennacherib','hezekiah','adversary','en','Invader and king','Sennacherib besieged Jerusalem, but his army perished overnight.'),
  ('seth','enoch','family','zh-CN','先祖与后裔','以诺出于塞特的谱系,是亚当的七世孙。'),
  ('seth','enoch','family','en','Ancestor and descendant','Enoch came of Seth’s line, seventh from Adam.'),
  ('shadrach','meshach','ally','zh-CN','患难同伴','二人同拒拜金像,同在火窑中蒙保全。'),
  ('shadrach','meshach','ally','en','Companions in trial','They refused the golden image and endured the furnace together.'),
  ('shem','ham','sibling','zh-CN','兄弟','挪亚之子;闪得祝福,含之子迦南受咒。'),
  ('shem','ham','sibling','en','Brothers','Both Noah’s sons; Shem was blessed while Ham’s son Canaan was cursed.'),
  ('shishak','rehoboam','adversary','zh-CN','入侵者与王','示撒攻耶路撒冷,掠去殿和王宫的宝物。'),
  ('shishak','rehoboam','adversary','en','Invader and king','Shishak attacked Jerusalem and carried off the temple treasures.'),
  ('sihon','moses','adversary','zh-CN','交战对手','西宏拒绝借路,出战被以色列人击败。'),
  ('sihon','moses','adversary','en','Battlefield foes','Sihon refused passage, gave battle, and was defeated by Israel.'),
  ('terah','abraham','family','zh-CN','父子','他拉带亚伯兰离吾珥,行到哈兰住下。'),
  ('terah','abraham','family','en','Father and son','Terah took Abram from Ur and settled in Haran.'),
  ('tobiah','nehemiah','adversary','zh-CN','阻挠者','多比雅讥诮拦阻筑墙,后被逐出殿中屋子。'),
  ('tobiah','nehemiah','adversary','en','Obstructor','Tobiah mocked the builders and was later expelled from the temple chamber.'),
  ('uriah','bathsheba','spouse','zh-CN','夫妻','拔示巴本是乌利亚的妻子,后被大卫所夺。'),
  ('uriah','bathsheba','spouse','en','Husband and wife','Bathsheba was Uriah’s wife before David took her.'),
  ('uzziah','ahaz','family','zh-CN','祖孙','亚哈斯是乌西雅之孙、约坦之子。'),
  ('uzziah','ahaz','family','en','Grandfather and grandson','Ahaz was Uzziah’s grandson through Jotham.'),
  ('zadok','solomon','ally','zh-CN','祭司与王','撒督在基训膏立所罗门为王。'),
  ('zadok','solomon','ally','en','Priest and king','Zadok anointed Solomon king at Gihon.'),
  ('zechariah-the-prophet','zerubbabel','mentor','zh-CN','先知与省长','撒迦利亚以异象之言坚固所罗巴伯建殿。'),
  ('zechariah-the-prophet','zerubbabel','mentor','en','Prophet and governor','Zechariah’s visions strengthened Zerubbabel to finish the temple.'),
  ('zedekiah','jeremiah','other','zh-CN','王与先知','西底家私下求问耶利米,却不敢听从。'),
  ('zedekiah','jeremiah','other','en','King and prophet','Zedekiah consulted Jeremiah in secret but dared not obey.'),
  ('zerubbabel','jeshua-the-high-priest','ally','zh-CN','省长与大祭司','二人同率百姓归回,同心筑坛建殿。'),
  ('zerubbabel','jeshua-the-high-priest','ally','en','Governor and high priest','Together they led the return and rebuilt altar and temple.'),
  ('zipporah','gershom','family','zh-CN','母子','革舜是西坡拉在米甸所生的长子。'),
  ('zipporah','gershom','family','en','Mother and son','Gershom was Zipporah’s firstborn, born in Midian.')
) AS v(fslug, tslug, rtype, locale, label, summary)
WHERE t.relation_id = r.id AND t.locale = v.locale::locale_code
  AND fc.slug = v.fslug AND tc.slug = v.tslug AND r.relation_type = v.rtype
  AND r.work_id = '10000000-0000-4000-8000-000000000005';

-- ============ 批次 6(补充:3 条 zh 已精修、en 仍为泛型的关系,仅更新 en)============
UPDATE relation_translations t SET label = v.label, summary = v.summary
FROM character_relations r
JOIN characters fc ON fc.id = r.from_character_id
JOIN characters tc ON tc.id = r.to_character_id,
(VALUES
  ('moses','miriam','sibling','en','Brother and sister','Miriam, Moses’ elder sister, watched over him at the river and led the women in song.'),
  ('aaron','miriam','sibling','en','Brother and sister','Aaron and Miriam, siblings of Moses, served in the wilderness leadership.'),
  ('martha','lazarus','sibling','en','Sister and brother','Martha and Lazarus of Bethany were sister and brother.')
) AS v(fslug, tslug, rtype, locale, label, summary)
WHERE t.relation_id = r.id AND t.locale = v.locale::locale_code
  AND fc.slug = v.fslug AND tc.slug = v.tslug AND r.relation_type = v.rtype
  AND r.work_id = '10000000-0000-4000-8000-000000000005';

-- ============ 覆盖自检(应各返回 0)============
SELECT count(*) AS remaining_generic_zh
FROM relation_translations t
JOIN character_relations r ON r.id = t.relation_id
WHERE r.work_id = '10000000-0000-4000-8000-000000000005'
  AND t.locale = 'zh-CN'
  AND t.label IN ('亲属','配偶','兄弟姐妹','同盟','对立','师承','相关');

SELECT count(*) AS remaining_generic_en
FROM relation_translations t
JOIN character_relations r ON r.id = t.relation_id
WHERE r.work_id = '10000000-0000-4000-8000-000000000005'
  AND t.locale = 'en'
  AND t.label IN ('Family','Spouse','Siblings','Ally','Adversary','Mentor','Related');

COMMIT;
