BEGIN;

-- Bible emblems (plan docs/BIBLE_ART_MUSIC_UPGRADE_PLAN_2026-08-18.md, track A1/D2).
-- Generated by scripts/generate_bible_art_music.ts. Symbolic identity only:
-- no row here claims to record what anyone looked like.

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000005','starfield','rayed','sky','scriptural',1)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000001','zh-CN','众星','创世记 15:5 领他走到外边，数算天上的星；后裔之约以星为记。','取自经文本身的意象，不是人物容貌。','published'),
  ('21000000-0000-4000-8000-000000000001','en','Field of stars','Genesis 15:5 brings him outside to number the stars; the promise of descendants is sealed by them.','Taken from the text''s own image, not from any likeness.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000005','tent','plain','vellum','scriptural',2)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000002','zh-CN','帐棚门口','创世记 18:10 撒拉在帐棚门口听见应许而笑。','以叙事场景为记，不描绘人物形貌。','published'),
  ('21000000-0000-4000-8000-000000000002','en','Tent door','Genesis 18:10 places her at the tent door, overhearing the promise and laughing.','A narrative setting used as a device, not a depiction.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000005','ram','thorned','vellum','scriptural',3)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000003','zh-CN','困在稠密树丛的公羊','创世记 22:13 亚伯拉罕举目观看，见一只公羊两角扣在稠密的小树中。','象征替代与保全，不评断该叙事的神学解释。','published'),
  ('21000000-0000-4000-8000-000000000003','en','Ram in the thicket','Genesis 22:13: a ram caught in a thicket by its horns, offered in his place.','A sign of substitution; the passage''s theology is left to the reader.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000005','10000000-0000-4000-8000-000000000005','pitcher','waved','vellum','scriptural',4)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000005','zh-CN','水瓶','创世记 24:15–20 她肩头上扛着水瓶，为仆人和骆驼打水。','取自认亲场景的关键器物。','published'),
  ('42000000-0000-4000-8000-000000000005','en','Water jar','Genesis 24:15–20: she comes with a jar on her shoulder and draws for the servant and his camels.','The object that identifies her in the betrothal scene.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000004','10000000-0000-4000-8000-000000000005','ladder','rayed','sky','scriptural',5)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000004','zh-CN','天梯','创世记 28:12 梦见一个梯子立在地上，梯子的头顶着天。','同一意象也是 Dufay《Nuper rosarum flores》定旋律的出处。','published'),
  ('21000000-0000-4000-8000-000000000004','en','Ladder','Genesis 28:12: a ladder set on the earth with its top reaching heaven.','The same image supplies the tenor of Dufay''s Nuper rosarum flores.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000005','crook','plain','vellum','scriptural',6)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000007','zh-CN','牧杖','创世记 29:9 拉结同她父亲的羊来了，因为那些羊是她牧放的。','以职分为记。','published'),
  ('42000000-0000-4000-8000-000000000007','en','Shepherd''s crook','Genesis 29:9: she comes with her father''s sheep, for she is the one who keeps them.','An emblem of her role in the narrative.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000009','10000000-0000-4000-8000-000000000005','striped-coat','plain','gold','scriptural',7)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000009','zh-CN','彩衣','创世记 37:3 以色列给约瑟做了一件彩衣。','该词的确切含义在译本间有争议，此处只取其为父亲偏爱之记号。','published'),
  ('42000000-0000-4000-8000-000000000009','en','Long coat','Genesis 37:3: his father makes him a coat of many colours.','The Hebrew term is debated; used here only as the sign of a father''s favour.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000005','10000000-0000-4000-8000-000000000005','tablets','rayed','ink','scriptural',8)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000005','zh-CN','两块法版','出埃及记 34:29 摩西手里拿着两块法版下西奈山。','不采用中世纪艺术中因翻译歧义而生的角状形象。','published'),
  ('21000000-0000-4000-8000-000000000005','en','Two tablets','Exodus 34:29: he comes down from Sinai with the two tablets in his hand.','The horned iconography born of a translation ambiguity is deliberately not used.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000006','10000000-0000-4000-8000-000000000005','budding-rod','braided','gold','scriptural',9)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000006','zh-CN','发芽的杖','民数记 17:8 亚伦的杖已经发了芽，开了花，结了熟杏。','以祭司职分的确认记号为徽。','published'),
  ('21000000-0000-4000-8000-000000000006','en','Budding rod','Numbers 17:8: Aaron''s rod buds, blossoms, and bears almonds.','The sign by which his priestly office is confirmed.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000012','10000000-0000-4000-8000-000000000005','timbrel','waved','vellum','scriptural',10)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000012','zh-CN','手鼓','出埃及记 15:20 米利暗手里拿着鼓，众妇女也跟她出去打鼓跳舞。','本图集中唯一以乐器为记的旧约人物。','published'),
  ('42000000-0000-4000-8000-000000000012','en','Timbrel','Exodus 15:20: she takes a timbrel in her hand and the women follow her with dancing.','The only Hebrew Bible figure in this atlas emblazoned with an instrument.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000015','10000000-0000-4000-8000-000000000005','shofar','plain','ink','scriptural',11)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000015','zh-CN','羊角','约书亚记 6:4 七个祭司要拿七个羊角走在约柜前。','耶利哥叙事的核心器物。','published'),
  ('42000000-0000-4000-8000-000000000015','en','Ram''s horn','Joshua 6:4: seven priests carry seven rams'' horns before the ark.','The instrument at the centre of the Jericho narrative.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000018','10000000-0000-4000-8000-000000000005','palm','plain','vellum','scriptural',12)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000018','zh-CN','底波拉的棕树','士师记 4:5 她住在棕树下，以色列人都上她那里去听判断。','以审判之处为记。','published'),
  ('42000000-0000-4000-8000-000000000018','en','Palm of Deborah','Judges 4:5: she sits under the palm and Israel comes up to her for judgement.','The place of judgement used as the emblem.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000020','10000000-0000-4000-8000-000000000005','fleece','plain','vellum','scriptural',13)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000020','zh-CN','羊毛','士师记 6:37 我把一团羊毛放在禾场上。','求证据的记号，与他反复求问的性格一致。','published'),
  ('42000000-0000-4000-8000-000000000020','en','Fleece','Judges 6:37: he lays a fleece of wool on the threshing floor.','A sign asked for as proof, matching his repeated questioning.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000021','10000000-0000-4000-8000-000000000005','broken-pillars','chained','ink','scriptural',14)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000021','zh-CN','推倒的柱子','士师记 16:29–30 参孙抱住托房的那两根柱子。','锁链环纹对应他被掳的结局。','published'),
  ('42000000-0000-4000-8000-000000000021','en','Broken pillars','Judges 16:29–30: he takes hold of the two pillars on which the house rests.','The chained border answers his captivity.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('43000000-0000-4000-8005-000000000003','10000000-0000-4000-8000-000000000005','tent-peg','plain','vellum','scriptural',15)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('43000000-0000-4000-8005-000000000003','zh-CN','橛子与锤','士师记 4:21 雅亿手拿帐棚的橛子，又手拿锤子。','取自经文所记的器物。她此前在本图集中只以一张杀戮版画存在，没有徽章也没有言论——那不是任何人的编辑决定，而是三条轨各自合理的选择叠加出的结果。','published'),
  ('43000000-0000-4000-8005-000000000003','en','Tent peg and mallet','Judges 4:21: Jael takes a tent peg in her hand and a hammer in the other.','The objects the text names. She had previously existed in this atlas only as an engraving of a killing, with no emblem and no saying — not anyone''s editorial decision, but what three separately reasonable choices added up to.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000039','10000000-0000-4000-8000-000000000005','vineyard','plain','ink','scriptural',16)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000039','zh-CN','拿伯的葡萄园','列王纪上 21 章：耶洗别设计夺取拿伯的葡萄园，是叙事中归给她的核心作为。','不采用「高窗」——列王纪下 9:30 的窗口正是她被推下摔死之处，以此为徽等于给她一枚判决。葡萄园标示她在叙事中的作为，由读者自行判断。','published'),
  ('42000000-0000-4000-8000-000000000039','en','Naboth''s vineyard','1 Kings 21: the seizure of Naboth''s vineyard is the act the narrative lays to her charge.','The high window is deliberately not used: in 2 Kings 9:30 that window is where she is thrown to her death, and an emblem of it would be a verdict. The vineyard marks what the narrative says she did and leaves the judgement to the reader.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000023','10000000-0000-4000-8000-000000000005','sheaf','plain','gold','scriptural',17)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000023','zh-CN','麦穗','路得记 2:2 容我往田间去，在人的身后拾取麦穗。','拾穗之举贯穿全书。','published'),
  ('42000000-0000-4000-8000-000000000023','en','Sheaf of grain','Ruth 2:2: she goes to the field to glean among the ears of grain.','Gleaning runs through the whole book.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000025','10000000-0000-4000-8000-000000000005','horn-of-oil','braided','gold','scriptural',18)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000025','zh-CN','膏油的角','撒母耳记上 16:13 撒母耳就用角里的膏油在他诸兄中膏了他。','他两次膏立君王，故以角为记。','published'),
  ('42000000-0000-4000-8000-000000000025','en','Horn of oil','1 Samuel 16:13: he takes the horn of oil and anoints David among his brothers.','He anoints two kings; the horn stands for both.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000026','10000000-0000-4000-8000-000000000005','spear','plain','ink','scriptural',19)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000026','zh-CN','枪','撒母耳记上 18:10–11 扫罗手里拿着枪，把枪一抡。','同一件器物在他的叙事中反复出现。','published'),
  ('42000000-0000-4000-8000-000000000026','en','Spear','1 Samuel 18:10–11: with a spear in his hand, Saul hurls it.','The same object recurs throughout his story.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000027','10000000-0000-4000-8000-000000000005','bow','plain','vellum','scriptural',20)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000027','zh-CN','弓','撒母耳记下 1:22 约拿单的弓箭非流敌人的血不退缩。','取自大卫为他所作的哀歌。','published'),
  ('42000000-0000-4000-8000-000000000027','en','Bow','2 Samuel 1:22: the bow of Jonathan did not turn back.','From David''s lament over him.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000005','harp','braided','gold','scriptural',21)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000007','zh-CN','琴','撒母耳记上 16:23 大卫就拿琴，用手而弹。','此徽同时是他与欧洲音乐史交叉链接的入口。','published'),
  ('21000000-0000-4000-8000-000000000007','en','Lyre','1 Samuel 16:23: David takes the harp and plays with his hand.','This emblem is also his doorway into the music atlas.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000008','10000000-0000-4000-8000-000000000005','crown','braided','gold','scriptural',22)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000008','zh-CN','冠冕','列王纪上 3:9 求你赐我智慧，可以判断你的民。','冠冕在此代表王的审断之责，不是财富。','published'),
  ('21000000-0000-4000-8000-000000000008','en','Crown','1 Kings 3:9: he asks for an understanding heart to judge the people.','The crown here stands for the duty of judgement, not for wealth.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000036','10000000-0000-4000-8000-000000000005','fire-chariot','rayed','sky','scriptural',23)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000036','zh-CN','火车火马','列王纪下 2:11 忽有火车火马将二人隔开。','以叙事结局为记。','published'),
  ('42000000-0000-4000-8000-000000000036','en','Chariot of fire','2 Kings 2:11: a chariot of fire and horses of fire separate the two of them.','The emblem is his departure.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000037','10000000-0000-4000-8000-000000000005','mantle','plain','vellum','scriptural',24)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000037','zh-CN','以利亚的外衣','列王纪下 2:13 他拾起以利亚身上掉下来的外衣。','承接之记号。','published'),
  ('42000000-0000-4000-8000-000000000037','en','Elijah''s mantle','2 Kings 2:13: he picks up the mantle that fell from Elijah.','The sign of succession.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000041','10000000-0000-4000-8000-000000000005','coal','rayed','ink','scriptural',25)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000041','zh-CN','红炭','以赛亚书 6:6–7 手里拿着红炭，是用火剪从坛上取下来的。','呼召场景的核心意象。','published'),
  ('42000000-0000-4000-8000-000000000041','en','Live coal','Isaiah 6:6–7: a live coal taken from the altar with tongs.','The central image of his call.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000042','10000000-0000-4000-8000-000000000005','yoke','chained','ink','scriptural',26)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000042','zh-CN','轭','耶利米书 27:2 你做绳索与轭，加在自己的颈项上。','先知的象征行动，不是刑具描写；锁链环纹取自他自己戴上的绳索与轭。','published'),
  ('42000000-0000-4000-8000-000000000042','en','Yoke','Jeremiah 27:2: he is told to make bonds and bars and put them on his neck.','A prophetic sign-act, not an instrument of punishment; the chained border is the bonds he puts on himself.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000044','10000000-0000-4000-8000-000000000005','lion','plain','ink','scriptural',27)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000044','zh-CN','狮子','但以理书 6:22 我的神差遣使者，封住狮子的口。','狮口封闭之记，不作现代动物学表述。','published'),
  ('42000000-0000-4000-8000-000000000044','en','Lion','Daniel 6:22: God sends his angel and shuts the lions'' mouths.','The shut lions'' mouths, not a zoological statement.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000047','10000000-0000-4000-8000-000000000005','scepter','braided','gold','scriptural',28)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000047','zh-CN','金杖','以斯帖记 5:2 王向她伸出手中的金杖。','接纳与冒险的双重记号。','published'),
  ('42000000-0000-4000-8000-000000000047','en','Golden scepter','Esther 5:2: the king holds out to her the golden scepter in his hand.','A sign of both acceptance and risk.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000049','10000000-0000-4000-8000-000000000005','trowel','plain','ink','scriptural',29)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000049','zh-CN','泥刀','尼希米记 4:17 一手做工，一手拿兵器。','重建城墙的工具。','published'),
  ('42000000-0000-4000-8000-000000000049','en','Trowel','Nehemiah 4:17: each worked with one hand and held a weapon with the other.','The tool of the wall''s rebuilding.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000009','10000000-0000-4000-8000-000000000005','fish','waved','sky','scriptural',30)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000009','zh-CN','大鱼','约拿书 1:17 耶和华安排一条大鱼吞了约拿。','文本称大鱼，不称鲸。','published'),
  ('21000000-0000-4000-8000-000000000009','en','Great fish','Jonah 1:17: a great fish is appointed to swallow Jonah.','The text says a great fish, not a whale.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000005','ark','waved','sky','scriptural',31)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000001','zh-CN','方舟','创世记 6–8 章洪水叙事的核心器物。','示意性船形，不作船体考据。','published'),
  ('42000000-0000-4000-8000-000000000001','en','Ark','The vessel at the centre of the Genesis 6–8 flood narrative.','A schematic hull, not a reconstruction claim.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('43000000-0000-4000-8001-000000000001','10000000-0000-4000-8000-000000000005','tree','plain','vellum','scriptural',32)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('43000000-0000-4000-8001-000000000001','zh-CN','园中的树','创世记 2:9 园子当中又有生命树和分别善恶的树。','不描绘人物形貌。','published'),
  ('43000000-0000-4000-8001-000000000001','en','Tree of the garden','Genesis 2:9: in the middle of the garden stand the tree of life and the tree of knowledge.','No human likeness is drawn.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('43000000-0000-4000-8001-000000000002','10000000-0000-4000-8000-000000000005','living-branch','braided','vellum','scriptural',33)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('43000000-0000-4000-8001-000000000002','zh-CN','众生之母','创世记 3:20 亚当给他妻子起名叫夏娃，因为她是众生之母。','以经文给她的名号为记。蛇属于伊甸叙事，不是她的身份标识——把女人与蛇焊在一起是后世接受史，不是本文本的说法。','published'),
  ('43000000-0000-4000-8001-000000000002','en','Mother of all living','Genesis 3:20: Adam names his wife Eve, because she is the mother of all living.','Her emblem is the name the text gives her. The serpent belongs to the garden narrative, not to her identity; welding the woman to the snake is later reception, not what this text says.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000005','lily','rayed','sky','iconographic',34)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000010','zh-CN','百合','百合是欧洲报喜图像中固定的属性物，不出自经文。','此为图像学传统，已明确标注为 iconographic。','published'),
  ('21000000-0000-4000-8000-000000000010','en','Lily','The lily is a fixed attribute in European Annunciation imagery; it is not in the text.','An art-historical convention, explicitly marked as iconographic.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000051','10000000-0000-4000-8000-000000000005','reed-cross','thorned','ink','iconographic',35)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000051','zh-CN','苇杖十字','苇杖十字是欧洲艺术中施洗约翰的固定属性物；约翰福音 1:29 供其言语依据。','属性物属图像传统，经文只提供言语。','published'),
  ('42000000-0000-4000-8000-000000000051','en','Reed cross','The reed cross is his standard attribute in European art; John 1:29 supplies his words.','The attribute is traditional; only the saying comes from the text.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000011','10000000-0000-4000-8000-000000000005','chi-rho','rayed','gold','liturgical',36)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000011','zh-CN','基督符号（Chi-Rho）','希腊文 ΧΡΙΣΤΟΣ 的头两个字母，四世纪起为通行的基督符号。','本图集不为耶稣绘制面容：具象描绘在多个传统中属敏感问题，符号是中立表达。','published'),
  ('21000000-0000-4000-8000-000000000011','en','Chi-Rho','The first two letters of ΧΡΙΣΤΟΣ, in use as a Christ monogram since the fourth century.','This atlas draws no face for Jesus; figural depiction is contested in several traditions, and a monogram stays neutral.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000012','10000000-0000-4000-8000-000000000005','keys','braided','gold','scriptural',37)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000012','zh-CN','钥匙','马太福音 16:19 我要把天国的钥匙给你。','此徽在经文与后世图像传统中一致。','published'),
  ('21000000-0000-4000-8000-000000000012','en','Keys','Matthew 16:19: the keys of the kingdom are given to him.','Text and later iconography agree on this one.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('21000000-0000-4000-8000-000000000013','10000000-0000-4000-8000-000000000005','sword-scroll','plain','ink','iconographic',38)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('21000000-0000-4000-8000-000000000013','zh-CN','剑与书卷','书卷代表书信，剑为欧洲艺术中保罗的固定属性物。','剑属图像传统，不指涉暴力。','published'),
  ('21000000-0000-4000-8000-000000000013','en','Sword and scroll','The scroll stands for the letters; the sword is Paul''s fixed attribute in European art.','The sword is iconographic convention, not a reference to violence.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000058','10000000-0000-4000-8000-000000000005','eagle','rayed','sky','iconographic',39)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000058','zh-CN','鹰','四福音书象征体系中约翰配鹰，源自以西结书 1:10 与启示录 4:7 的四活物。','该配对由教父传统确立，不出自福音书自身。','published'),
  ('42000000-0000-4000-8000-000000000058','en','Eagle','In the evangelists'' symbol system John takes the eagle, from the living creatures of Ezekiel 1:10 and Revelation 4:7.','The pairing comes from patristic tradition, not from the Gospel itself.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000052','10000000-0000-4000-8000-000000000005','jar','plain','vellum','scriptural',40)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000052','zh-CN','香膏','马可福音 16:1 抹大拉的马利亚买了香膏，要去膏耶稣的身体。','沿用欧洲艺术为她固定的容器形，但依据取她本人在马可福音 16:1 的携膏之举；不采用把她与路加福音 7 章、约翰福音 12 章的无名妇女合并的后世读法。','published'),
  ('42000000-0000-4000-8000-000000000052','en','Spices for anointing','Mark 16:1: Mary Magdalene buys spices in order to anoint the body of Jesus.','It keeps the vessel European art fixed on her, but rests on her own act in Mark 16:1 — not on the later conflation of her with the unnamed women of Luke 7 and John 12.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000055','10000000-0000-4000-8000-000000000005','coins','plain','ink','scriptural',41)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000055','zh-CN','三十块钱','马太福音 26:15 他们就给了他三十块钱。','取自马太福音的叙事细节。该属性物在中世纪以降的欧洲艺术中与敌犹刻板形象合流，本图集只取经文所记的交易，不承接那套图像。','published'),
  ('42000000-0000-4000-8000-000000000055','en','Thirty pieces of silver','Matthew 26:15: they weigh out to him thirty pieces of silver.','A narrative detail from Matthew. In European art from the Middle Ages on, this attribute merged with antisemitic caricature; the atlas takes only the transaction the text records, not that imagery.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000056','10000000-0000-4000-8000-000000000005','basin','plain','ink','scriptural',42)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000056','zh-CN','洗手的盆','马太福音 27:24 彼拉多拿水在众人面前洗手。','只标注叙事动作。','published'),
  ('42000000-0000-4000-8000-000000000056','en','Basin','Matthew 27:24: Pilate takes water and washes his hands before the crowd.','It marks an action in the narrative and nothing more.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO character_emblems(character_id,work_id,symbol_key,ring_key,ground_key,attestation,sort_order) VALUES
  ('42000000-0000-4000-8000-000000000045','10000000-0000-4000-8000-000000000005','statue','plain','ink','scriptural',43)
ON CONFLICT (character_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,ring_key=EXCLUDED.ring_key,ground_key=EXCLUDED.ground_key,attestation=EXCLUDED.attestation,sort_order=EXCLUDED.sort_order;
INSERT INTO character_emblem_translations(character_id,locale,symbol_name,symbol_meaning,attribution_note,status) VALUES
  ('42000000-0000-4000-8000-000000000045','zh-CN','大像','但以理书 2:31 王啊，你梦见一个大像。','取自但以理书的梦象，不是历史造像考据。','published'),
  ('42000000-0000-4000-8000-000000000045','en','Great image','Daniel 2:31: the king sees a great image in his dream.','From the dream in Daniel, not from archaeology.','published')
ON CONFLICT (character_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,attribution_note=EXCLUDED.attribution_note,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000005','radiance',1)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000001','zh-CN','光','创世叙事以光的分开为起点。','published'),
  ('82000000-0000-4000-8000-000000000001','en','Light','The primeval narrative opens with light divided from darkness.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('81000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000005','starfield',2)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('81000000-0000-4000-8000-000000000001','zh-CN','众星','族长叙事以数算天上的星为约的记号。','published'),
  ('81000000-0000-4000-8000-000000000001','en','Stars','The patriarchal promise is counted out in stars.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('81000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000005','flame',3)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('81000000-0000-4000-8000-000000000002','zh-CN','火柱','出埃及叙事以火柱与云柱领路。','published'),
  ('81000000-0000-4000-8000-000000000002','en','Pillar of fire','Fire and cloud lead the Exodus march.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000004','10000000-0000-4000-8000-000000000005','tent',4)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000004','zh-CN','会幕','旷野时期的中心是可迁移的会幕。','published'),
  ('82000000-0000-4000-8000-000000000004','en','Tabernacle','The wilderness centre is a tent that moves.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000005','10000000-0000-4000-8000-000000000005','shofar',5)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000005','zh-CN','羊角','士师叙事以号角召集支派。','published'),
  ('82000000-0000-4000-8000-000000000005','en','Ram''s horn','The horn gathers the tribes in the judges'' cycles.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('81000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000005','crown',6)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('81000000-0000-4000-8000-000000000003','zh-CN','冠冕','统一王国时期以王权为轴。','published'),
  ('81000000-0000-4000-8000-000000000003','en','Crown','The united monarchy turns on kingship.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000005','split-crown',7)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000007','zh-CN','裂开的冠冕','王国分裂为南北两国。','published'),
  ('82000000-0000-4000-8000-000000000007','en','Divided crown','One crown becomes two kingdoms.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('81000000-0000-4000-8000-000000000004','10000000-0000-4000-8000-000000000005','mantle',8)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('81000000-0000-4000-8000-000000000004','zh-CN','先知外衣','先知叙事以承接的外衣为记。','published'),
  ('81000000-0000-4000-8000-000000000004','en','Prophet''s mantle','The prophetic line is marked by a mantle handed on.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000009','10000000-0000-4000-8000-000000000005','broken-wall',9)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000009','zh-CN','破口的城墙','被掳时期以城墙被破为界。','published'),
  ('82000000-0000-4000-8000-000000000009','en','Breached wall','Exile begins at a breached wall.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000005','trowel',10)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000010','zh-CN','泥刀','归回时期以重建为主题。','published'),
  ('82000000-0000-4000-8000-000000000010','en','Trowel','The return is a rebuilding.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('81000000-0000-4000-8000-000000000005','10000000-0000-4000-8000-000000000005','chi-rho',11)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('81000000-0000-4000-8000-000000000005','zh-CN','基督符号','福音书时期以基督符号为记，不绘面容。','published'),
  ('81000000-0000-4000-8000-000000000005','en','Chi-Rho','The Gospels are marked by the monogram, never a face.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('81000000-0000-4000-8000-000000000006','10000000-0000-4000-8000-000000000005','flame-tongues',12)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('81000000-0000-4000-8000-000000000006','zh-CN','舌头如火焰','使徒行传以五旬节的火舌开篇。','published'),
  ('81000000-0000-4000-8000-000000000006','en','Tongues of fire','Acts opens with tongues as of fire.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

INSERT INTO chapter_emblems(chapter_id,work_id,symbol_key,sort_order) VALUES ('82000000-0000-4000-8000-000000000013','10000000-0000-4000-8000-000000000005','ship',13)
ON CONFLICT (chapter_id) DO UPDATE SET symbol_key=EXCLUDED.symbol_key,sort_order=EXCLUDED.sort_order;
INSERT INTO chapter_emblem_translations(chapter_id,locale,symbol_name,symbol_meaning,status) VALUES
  ('82000000-0000-4000-8000-000000000013','zh-CN','船','保罗宣教以地中海航行为骨架。','published'),
  ('82000000-0000-4000-8000-000000000013','en','Ship','The Pauline mission is built on Mediterranean voyages.','published')
ON CONFLICT (chapter_id,locale) DO UPDATE SET symbol_name=EXCLUDED.symbol_name,symbol_meaning=EXCLUDED.symbol_meaning,status=EXCLUDED.status;

COMMIT;
