BEGIN;

-- Bible ↔ European classical music reception links (track C1).
-- Generated by scripts/generate_bible_art_music.ts. No new audio is added:
-- these point at score fragments the music atlas already renders and
-- synthesises, which stay labelled as study audio, not historical sound.

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('806de912-9d0a-4bd7-8fc0-2ce8f0960c8a','10000000-0000-4000-8000-000000000005','character','21000000-0000-4000-8000-000000000007','10000000-0000-4000-8000-000000000010','composition','ae88045e-e9a9-4d35-b977-ec1b5383660d','musical_setting','high',1)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('806de912-9d0a-4bd7-8fc0-2ce8f0960c8a','zh-CN','许茨《大卫诗篇集》','1619 年出版的诗篇合唱集，所选文本为归于大卫的诗篇。','published'),
  ('806de912-9d0a-4bd7-8fc0-2ce8f0960c8a','en','Schütz, Psalmen Davids','The 1619 collection sets psalms ascribed to David.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('ca33a908-559f-4687-8b8f-c4d857004477','10000000-0000-4000-8000-000000000005','character','21000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','664b8f71-12dd-49e1-88d8-d23d7f29eaf7','musical_setting','high',2)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('ca33a908-559f-4687-8b8f-c4d857004477','zh-CN','若斯坎《圣母颂》','经文起句取自路加福音 1:28 天使的问安，其余为中世纪续祷文。','published'),
  ('ca33a908-559f-4687-8b8f-c4d857004477','en','Josquin, Ave Maria… virgo serena','The opening salutation is Luke 1:28; the rest is a medieval sequence text.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('8e941c6a-a96c-4b1e-857d-0fa4ebfa03b9','10000000-0000-4000-8000-000000000005','character','21000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','e5b4a449-eb9d-4b23-8e3c-93aac312e986','musical_reception','high',3)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('8e941c6a-a96c-4b1e-857d-0fa4ebfa03b9','zh-CN','希尔德加德《最青翠的枝》','十二世纪圣母交替圣歌，以枝子意象呼应以赛亚书 11:1 的传统解读。','published'),
  ('8e941c6a-a96c-4b1e-857d-0fa4ebfa03b9','en','Hildegard, O viridissima virga','A twelfth-century Marian antiphon whose branch imagery follows the traditional reading of Isaiah 11:1.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('f84eb71f-fbde-43d7-85a5-6d9eb9b0b061','10000000-0000-4000-8000-000000000005','character','21000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','d0ad2e6a-844c-4480-b375-b7f23568d8cd','musical_reception','high',4)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('f84eb71f-fbde-43d7-85a5-6d9eb9b0b061','zh-CN','马肖《圣母弥撒》','已知最早由单一作曲家完成的常规弥撒套曲，为圣母弥撒而作。','published'),
  ('f84eb71f-fbde-43d7-85a5-6d9eb9b0b061','en','Machaut, Messe de Nostre Dame','The earliest complete Mass Ordinary by one named composer, written for a Lady Mass.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('9e67119c-36f7-4a47-8993-43261039266d','10000000-0000-4000-8000-000000000005','event','41000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','02e00879-a3ba-4e4c-9cb1-5e5af275acc0','musical_setting','high',5)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('9e67119c-36f7-4a47-8993-43261039266d','zh-CN','维多利亚《何等伟大的奥秘》','圣诞晨祷应答圣歌的文本设置。','published'),
  ('9e67119c-36f7-4a47-8993-43261039266d','en','Victoria, O magnum mysterium','A setting of the Christmas Matins responsory.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('40aaebb5-41f6-45f5-8a1d-1ff97036a356','10000000-0000-4000-8000-000000000005','event','41000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','54f9cd11-1155-4f3f-b2e2-cb08b5a6693b','musical_reception','high',6)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('40aaebb5-41f6-45f5-8a1d-1ff97036a356','zh-CN','科雷利《圣诞协奏曲》','乐谱题献注明「为圣诞夜而作」。','published'),
  ('40aaebb5-41f6-45f5-8a1d-1ff97036a356','en','Corelli, Christmas Concerto','The score is inscribed as made for the night of the Nativity.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('134a0b3f-0f84-4dca-8b11-ba5d001ee709','10000000-0000-4000-8000-000000000005','event','41000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','97f0942a-e051-4ee3-b411-af9c53034ab0','musical_setting','high',7)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('134a0b3f-0f84-4dca-8b11-ba5d001ee709','zh-CN','莱奥南《普世看见》（二声部）','圣诞日弥撒升阶经，文本取自诗篇 98:3。','published'),
  ('134a0b3f-0f84-4dca-8b11-ba5d001ee709','en','Léonin, Viderunt omnes (two voices)','The gradual for Christmas Day, its text from Psalm 98:3.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('00fdd4cb-4e22-4492-87f0-2d87ab457f8d','10000000-0000-4000-8000-000000000005','event','41000000-0000-4000-8000-000000000010','10000000-0000-4000-8000-000000000010','composition','d8444d6c-347b-49d4-83b0-34cb71999b1d','musical_setting','high',8)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('00fdd4cb-4e22-4492-87f0-2d87ab457f8d','zh-CN','佩罗坦《普世看见》（四声部）','同一升阶经的四声部扩写，可与莱奥南版直接对听。','published'),
  ('00fdd4cb-4e22-4492-87f0-2d87ab457f8d','en','Pérotin, Viderunt omnes (four voices)','The four-voice expansion of the same gradual, made to be compared with Léonin''s.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('45d95c44-e5b1-4c0c-8bdb-818c1caad00e','10000000-0000-4000-8000-000000000005','event','62000000-0000-4000-8000-000000000012','10000000-0000-4000-8000-000000000010','composition','e60b1ad0-d7b1-42e7-870a-02b99a7e2998','musical_reception','high',9)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('45d95c44-e5b1-4c0c-8bdb-818c1caad00e','zh-CN','杜费《玫瑰花开》','定旋律取自「Terribilis est locus iste」，其经文出处为创世记 28:17 雅各在伯特利之言。','published'),
  ('45d95c44-e5b1-4c0c-8bdb-818c1caad00e','en','Dufay, Nuper rosarum flores','Its tenor is Terribilis est locus iste, whose text is Jacob''s words at Bethel in Genesis 28:17.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('4f94fa3d-b2eb-400b-87ac-534e42829938','10000000-0000-4000-8000-000000000005','event','63000000-0000-4000-8011-000000000006','10000000-0000-4000-8000-000000000010','composition','c53f19aa-f066-430c-879c-812b4d13335b','musical_reception','high',10)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('4f94fa3d-b2eb-400b-87ac-534e42829938','zh-CN','理查·施特劳斯《莎乐美》','取材自马太福音 14 与马可福音 6 的叙事，经王尔德剧本转手，属现代接受而非经文设置。「莎乐美」之名不见于圣经，马可福音只作「希罗底的女儿」，该名出自约瑟夫《犹太古史》。','published'),
  ('4f94fa3d-b2eb-400b-87ac-534e42829938','en','R. Strauss, Salome','Drawn from Matthew 14 and Mark 6 by way of Wilde''s play: modern reception, not a setting of the text. The name Salome is not in the Bible — Mark says only "the daughter of Herodias"; the name comes from Josephus.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('a92a57e3-8a26-44b0-8a48-93e213c8ccea','10000000-0000-4000-8000-000000000005','event','63000000-0000-4000-8001-000000000009','10000000-0000-4000-8000-000000000010','composition','821db903-82eb-4e68-8d6b-93064fbb729a','musical_reception','high',11)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('a92a57e3-8a26-44b0-8a48-93e213c8ccea','zh-CN','《亚当剧》','十二世纪盎格鲁-诺曼礼仪剧，搬演创世记 2–3 章的亚当夏娃叙事。','published'),
  ('a92a57e3-8a26-44b0-8a48-93e213c8ccea','en','Le Jeu d''Adam','A twelfth-century Anglo-Norman liturgical drama staging the Adam and Eve narrative of Genesis 2–3.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('2454e610-91b6-4b7b-8606-4a89829d851c','10000000-0000-4000-8000-000000000005','event','62000000-0000-4000-8000-000000000101','10000000-0000-4000-8000-000000000010','composition','82470619-50cc-4de9-a0b8-28bfa7b76cd2','musical_reception','high',12)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('2454e610-91b6-4b7b-8606-4a89829d851c','zh-CN','伯德《圣体颂》','十四世纪圣体文本，属拉丁礼传统的圣体崇敬，不是最后晚餐叙事的经文设置。伯德是伊丽莎白治下的天主教 recusant，此类作品为私下礼拜而写。','published'),
  ('2454e610-91b6-4b7b-8606-4a89829d851c','en','Byrd, Ave verum corpus','A fourteenth-century Eucharistic text belonging to Latin-rite devotion to the Body of Christ, not a setting of the supper narrative. Byrd was a Catholic recusant under Elizabeth I, writing such works for worship held in private.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

INSERT INTO cross_work_links(id,from_work_id,from_entity_kind,from_entity_id,to_work_id,to_entity_kind,to_entity_id,link_type,confidence,sort_order) VALUES
  ('17a51f22-ef04-486f-8429-443e97b83e9d','10000000-0000-4000-8000-000000000005','location','31000000-0000-4000-8000-000000000006','10000000-0000-4000-8000-000000000010','composition','98fa7492-e488-4c99-a610-b1ec084923eb','musical_setting','high',13)
ON CONFLICT (id) DO UPDATE SET link_type=EXCLUDED.link_type,confidence=EXCLUDED.confidence,sort_order=EXCLUDED.sort_order;
INSERT INTO cross_work_link_translations(link_id,locale,label,basis_note,status) VALUES
  ('17a51f22-ef04-486f-8429-443e97b83e9d','zh-CN','帕莱斯特里那《如鹿切慕溪水》','文本为诗篇 42:1–2；该诗超题归于可拉后裔而非大卫，说话者渴慕重回神的殿。','published'),
  ('17a51f22-ef04-486f-8429-443e97b83e9d','en','Palestrina, Sicut cervus','Its text is Psalm 42:1–2; the psalm is ascribed to the sons of Korah, not to David, and its speaker longs for God''s house.','published')
ON CONFLICT (link_id,locale) DO UPDATE SET label=EXCLUDED.label,basis_note=EXCLUDED.basis_note,status=EXCLUDED.status;

COMMIT;
