import{describe,expect,it}from"vitest";
import{AtlasResponseSchema}from"./types";

const meta={resolvedLocale:"zh-CN",fallbackUsed:false,translationStatus:"published"}as const;
const work={id:"10000000-0000-4000-8000-000000000005",slug:"the-bible",authorName:"Various authors and traditions",publicationYear:null,contentMode:"documented_record",mapLayer:"real",category:"mythic_epic",originRegion:"Ancient Near East",chronologyStartYear:-2100,chronologyEndYear:62,themeColor:"#c9972e",themeColorDark:"#6c4a13",themeColorLight:"#f3d78b",title:"圣经",summary:"摘要",default_locale:"en",...meta};
const fixture={requestedLocale:"zh-CN",work,characters:[{id:"21000000-0000-4000-8000-000000000005",slug:"moses",gender:"male",ageStage:"elder",roleType:"protagonist",realityType:"fictionalised_historical",birthYear:-1400,deathYear:-1200,birthPlaceSlug:"nile-delta",deathPlaceSlug:null,iconVariant:"lawgiver",importance:5,name:"摩西",summary:"摘要",aliases:[],detail:"详情",motivation:"动机",eventSlugs:["exodus"],locationSlugs:["nile-delta"],sourceTitles:["Exodus"],...meta}],locations:[{id:"31000000-0000-4000-8000-000000000004",slug:"nile-delta",layer:"real",locationType:"region",coordinateAccuracy:"approximate",preferredZoom:7,modernCountryCode:"EG",isInferred:true,stillExists:true,lng:31.1,lat:30.8,canvasX:null,canvasY:null,name:"尼罗河三角洲",summary:"摘要",aliases:["埃及"],detail:"详情",literarySignificance:"意义",historicalBackground:"背景",modernStatus:"现状",historicalRegionName:"古埃及",characterSlugs:["moses"],eventSlugs:["exodus"],routeSlugs:["exodus-route"],...meta}],events:[{id:"41000000-0000-4000-8000-000000000004",slug:"exodus",startDate:null,endDate:null,sequence:4,reality:"contested",eventType:"migration",timeType:"range",calendarSystem:"unknown",historicalStartYear:-1300,historicalEndYear:-1200,startMonth:null,startDay:null,confidence:"low",parentEventSlug:null,title:"离开埃及",summary:"摘要",detail:"详情",significance:"意义",timeLabel:"约公元前 1300–1200 年",locationSlugs:["nile-delta"],characterSlugs:["moses"],sourceTitles:["Exodus"],routeSlugs:["exodus-route"],...meta}],routes:[{id:"61000000-0000-4000-8000-000000000002",slug:"exodus-route",layer:"real",certainty:"inferred",name:"路线",summary:"摘要",waypoints:[{position:0,locationSlug:"nile-delta",eventSlug:"exodus"}],...meta}],relations:[{id:"71000000-0000-4000-8000-000000000006",fromSlug:"moses",toSlug:"aaron",relationType:"family",direction:"bidirectional",sentiment:"positive",strength:5,status:"active",startEventSlug:null,endEventSlug:null,label:"兄弟",summary:"摘要",sourceTitles:["Exodus"],...meta}],sources:[{id:"51000000-0000-4000-8000-000000000002",title:"Exodus",url:null,citation:"Exodus 1–24",evidenceGrade:"primary",sourceType:"primary_text"}],chronologies:[{id:"91000000-0000-4000-8000-000000000001",kind:"historical",label:"Sample",startYear:-2100,endYear:62,calendarSystem:"unknown",isDefault:true}],media:[]};

describe("v3.1 atlas runtime contract",()=>{
  it("accepts explicit complex chronology, identity, geography, and relation metadata",()=>expect(AtlasResponseSchema.parse(fixture).events[0]?.timeType).toBe("range"));
  it("rejects a silent entity fallback",()=>{const invalid=structuredClone(fixture)as Record<string,unknown>;const locations=invalid.locations as Array<Record<string,unknown>>;delete locations[0]?.fallbackUsed;expect(AtlasResponseSchema.safeParse(invalid).success).toBe(false)});
  it("rejects an approximate event encoded without time type",()=>{const invalid=structuredClone(fixture)as typeof fixture;delete(invalid.events[0]as Partial<typeof invalid.events[0]>).timeType;expect(AtlasResponseSchema.safeParse(invalid).success).toBe(false)});
});
