import type { SelectedEntity, SelectionSource, Tab } from "../state";
import type { Atlas, AtlasCharacter, Locale } from "../types";

interface Props{atlas:Atlas;entity:SelectedEntity;locale:Locale;onClose:()=>void;onSelect:(entity:SelectedEntity,source:SelectionSource)=>void;onTab:(tab:Tab)=>void}
const valueLabels={male:["男","Male"],female:["女","Female"],unknown:["未知","Unknown"],na:["不适用","N/A"],child:["儿童","Child"],youth:["青年","Youth"],adult:["成年","Adult"],elder:["老年","Elder"]} as const;
function localValue(value:string,locale:Locale):string{const labels=valueLabels[value as keyof typeof valueLabels];return labels?labels[locale==="zh-CN"?0:1]:value.replaceAll("_"," ")}
function PersonAvatar({person,color}:{person:AtlasCharacter;color:string}){return <span className={`person-avatar ${person.gender} ${person.ageStage}`} style={{background:color}} aria-hidden="true"><svg viewBox="0 0 48 48"><circle cx="24" cy={person.ageStage==="child"?17:15} r={person.ageStage==="child"?8:10}/><path d={person.gender==="female"?"M8 43c2-13 8-19 16-19s14 6 16 19z":"M9 43c1-12 6-18 15-18s14 6 15 18z"}/></svg><b>{person.roleType.slice(0,1).toUpperCase()}</b></span>}

/** Full-detail drawer for the shared selected entity. */
export function EntityDrawer({atlas,entity,locale,onClose,onSelect,onTab}:Props){
  const z=locale==="zh-CN";
  if(entity.type==="character"){
    const person=atlas.characters.find((item)=>item.slug===entity.id);if(!person)return null;
    const relations=atlas.relations.filter((item)=>item.fromSlug===person.slug||item.toSlug===person.slug);
    return <aside className="entity-drawer"><button className="close" aria-label="close" onClick={onClose}>×</button><header><PersonAvatar person={person} color={atlas.work.themeColor}/><div><small>{atlas.work.title}</small><h2>{person.name}</h2><p>{person.aliases.join(" · ")}</p></div></header><div className="identity-tags"><span>{localValue(person.gender,locale)}</span><span>{localValue(person.ageStage,locale)}</span><span>{localValue(person.roleType,locale)}</span><span>{localValue(person.realityType,locale)}</span></div><p>{person.summary}</p><p>{person.detail}</p>{person.motivation&&<section><h3>{z?"人物动机":"Motivation"}</h3><p>{person.motivation}</p></section>}<dl><dt>{z?"生卒年代":"Life range"}</dt><dd>{person.birthYear??"?"} — {person.deathYear??"?"}</dd><dt>{z?"关键事件":"Key events"}</dt><dd>{person.eventSlugs.length}</dd><dt>{z?"主要地点":"Main places"}</dt><dd>{person.locationSlugs.length}</dd></dl><div className="drawer-actions"><button onClick={()=>{const place=person.locationSlugs[0];if(place)onSelect({type:"location",workSlug:atlas.work.slug,id:place},"list")}}>{z?"在地图中定位":"Locate on map"}</button><button onClick={()=>onTab("relationships")}>{z?"查看关系图":"Relationship graph"}</button><button onClick={()=>onTab("events")}>{z?"相关事件":"Related events"}</button></div>{relations.length>0&&<section><h3>{z?"重要关系":"Important relations"}</h3>{relations.map((relation)=><button className="relation-row" key={relation.id} onClick={()=>onSelect({type:"relationship",workSlug:atlas.work.slug,id:relation.id},"list")}>{relation.label}<small>{relation.summary}</small></button>)}</section>}<Sources names={person.sourceTitles}/></aside>;
  }
  if(entity.type==="event"){
    const event=atlas.events.find((item)=>item.slug===entity.id);if(!event)return null;
    return <aside className="entity-drawer"><button className="close" aria-label="close" onClick={onClose}>×</button><small>{atlas.work.title} · {localValue(event.eventType,locale)}</small><h2>{event.title}</h2><div className="identity-tags"><span>{event.timeLabel||localValue(event.timeType,locale)}</span><span>{localValue(event.reality,locale)}</span><span>{event.confidence}</span></div><p>{event.summary}</p><p>{event.detail}</p>{event.significance&&<section><h3>{z?"意义":"Significance"}</h3><p>{event.significance}</p></section>}<div className="drawer-links"><h3>{z?"参与人物":"People"}</h3>{event.characterSlugs.map((slug)=>{const person=atlas.characters.find((item)=>item.slug===slug);return person?<button key={slug} onClick={()=>onSelect({type:"character",workSlug:atlas.work.slug,id:slug},"list")}>{person.name}</button>:null})}<h3>{z?"地点":"Places"}</h3>{event.locationSlugs.map((slug)=>{const place=atlas.locations.find((item)=>item.slug===slug);return place?<button key={slug} onClick={()=>onSelect({type:"location",workSlug:atlas.work.slug,id:slug},"list")}>{place.name}</button>:null})}</div><Sources names={event.sourceTitles}/></aside>;
  }
  if(entity.type==="location"){
    const place=atlas.locations.find((item)=>item.slug===entity.id);if(!place)return null;
    return <aside className="entity-drawer"><button className="close" aria-label="close" onClick={onClose}>×</button><small>{atlas.work.title}</small><h2>{place.name}</h2><div className="identity-tags"><span>{localValue(place.locationType,locale)}</span><span>{localValue(place.coordinateAccuracy,locale)}</span>{place.modernCountryCode&&<span>{place.modernCountryCode}</span>}</div><p>{place.summary}</p><p>{place.detail}</p>{place.literarySignificance&&<section><h3>{z?"文学意义":"Literary significance"}</h3><p>{place.literarySignificance}</p></section>}{place.historicalBackground&&<section><h3>{z?"历史背景":"Historical background"}</h3><p>{place.historicalBackground}</p></section>}{place.modernStatus&&<section><h3>{z?"现代状态":"Modern status"}</h3><p>{place.modernStatus}</p></section>}<dl><dt>{z?"坐标":"Coordinates"}</dt><dd>{place.lat?.toFixed(4)??"—"}, {place.lng?.toFixed(4)??"—"}</dd><dt>{z?"相关人物 / 事件 / 路线":"People / events / routes"}</dt><dd>{place.characterSlugs.length} / {place.eventSlugs.length} / {place.routeSlugs.length}</dd></dl><div className="drawer-actions"><button onClick={()=>onTab("events")}>{z?"查看相关事件":"Related events"}</button><button onClick={()=>onTab("routes")}>{z?"查看相关路线":"Related routes"}</button></div></aside>;
  }
  if(entity.type==="route"){
    const route=atlas.routes.find((item)=>item.slug===entity.id);if(!route)return null;
    return <aside className="entity-drawer"><button className="close" aria-label="close" onClick={onClose}>×</button><small>{atlas.work.title} · {route.certainty}</small><h2>{route.name}</h2><p>{route.summary}</p><ol>{route.waypoints.map((waypoint)=>{const place=atlas.locations.find((item)=>item.slug===waypoint.locationSlug);return <li key={waypoint.position}><button onClick={()=>onSelect({type:"location",workSlug:atlas.work.slug,id:waypoint.locationSlug},"list")}>{place?.name??waypoint.locationSlug}</button></li>})}</ol></aside>;
  }
  if(entity.type==="relationship"){
    const relation=atlas.relations.find((item)=>item.id===entity.id);if(!relation)return null;const from=atlas.characters.find((item)=>item.slug===relation.fromSlug);const to=atlas.characters.find((item)=>item.slug===relation.toSlug);
    return <aside className="entity-drawer"><button className="close" aria-label="close" onClick={onClose}>×</button><small>{atlas.work.title} · {relation.relationType}</small><h2>{relation.label}</h2><p>{relation.summary}</p><div className="relation-pair">{[from,to].map((person)=>person?<button key={person.slug} onClick={()=>onSelect({type:"character",workSlug:atlas.work.slug,id:person.slug},"relationship")}><PersonAvatar person={person} color={atlas.work.themeColor}/>{person.name}</button>:null)}</div><dl><dt>{z?"方向":"Direction"}</dt><dd>{relation.direction}</dd><dt>{z?"情感":"Sentiment"}</dt><dd>{relation.sentiment}</dd><dt>{z?"强度":"Strength"}</dt><dd>{relation.strength}/5</dd><dt>{z?"状态":"Status"}</dt><dd>{relation.status}</dd></dl><Sources names={relation.sourceTitles}/></aside>;
  }
  return null;
}

function Sources({names}:{names:string[]}){if(names.length===0)return null;return <section><h3>Sources</h3>{names.map((name)=><p key={name} className="source-name">{name}</p>)}</section>}
