export type ExpansionLocation = {
  slug: string; zh: string; en: string; lng: number; lat: number; country: string;
};

export type ExpansionArtist = {
  slug: string; zh: string; en: string; fullZh?: string; fullEn?: string;
  birth: number | null; death: number | null; chapter: string; importance: number;
  movements: string[]; mainLocation: string; gender?: "male" | "female";
};

export type ExpansionArtwork = {
  slug: string; zh: string; en: string; artists: string[];
  start: number; end: number; timeType?: "exact" | "range" | "approximate";
  medium: string; chapter: string; movements: string[];
  creationLocation: string | null; currentLocation: string | null;
  status?: "confirmed" | "attributed" | "workshop" | "lost" | "destroyed" | "unknown";
};

export type ExpansionRelation = {
  from: string; to: string; type: string; strength: number;
  zh: string; en: string; summaryZh: string; summaryEn: string;
};

export type ExpansionEvent = {
  slug: string; year: number; endYear?: number; location: string;
  titleZh: string; titleEn: string; summaryZh: string; summaryEn: string;
  significanceZh: string; significanceEn: string; sourceKey: string;
};

export const LOCATIONS: ExpansionLocation[] = [
  { slug: "naples", zh: "那不勒斯", en: "Naples", lng: 14.2681, lat: 40.8518, country: "IT" },
  { slug: "istanbul", zh: "伊斯坦布尔", en: "Istanbul", lng: 28.9784, lat: 41.0082, country: "TR" },
  { slug: "autun", zh: "欧坦", en: "Autun", lng: 4.2994, lat: 46.9517, country: "FR" },
  { slug: "pisa", zh: "比萨", en: "Pisa", lng: 10.4017, lat: 43.7228, country: "IT" },
  { slug: "dublin", zh: "都柏林", en: "Dublin", lng: -6.2603, lat: 53.3498, country: "IE" },
  { slug: "bayeux", zh: "巴约", en: "Bayeux", lng: -0.7039, lat: 49.2765, country: "FR" },
  { slug: "conques", zh: "孔克", en: "Conques", lng: 2.3961, lat: 44.5992, country: "FR" },
  { slug: "chartres", zh: "沙特尔", en: "Chartres", lng: 1.489, lat: 48.4472, country: "FR" },
  { slug: "olympia", zh: "奥林匹亚", en: "Olympia", lng: 21.63, lat: 37.638, country: "GR" },
  { slug: "oslo", zh: "奥斯陆", en: "Oslo", lng: 10.7522, lat: 59.9139, country: "NO" },
  { slug: "saint-petersburg", zh: "圣彼得堡", en: "Saint Petersburg", lng: 30.3351, lat: 59.9343, country: "RU" },
  { slug: "kassel", zh: "卡塞尔", en: "Kassel", lng: 9.4797, lat: 51.3127, country: "DE" },
  { slug: "the-hague", zh: "海牙", en: "The Hague", lng: 4.3007, lat: 52.0705, country: "NL" },
  { slug: "washington-dc", zh: "华盛顿", en: "Washington, D.C.", lng: -77.0369, lat: 38.9072, country: "US" },
  { slug: "haarlem", zh: "哈勒姆", en: "Haarlem", lng: 4.6462, lat: 52.3874, country: "NL" },
  { slug: "moscow", zh: "莫斯科", en: "Moscow", lng: 37.6173, lat: 55.7558, country: "RU" },
  { slug: "barcelona", zh: "巴塞罗那", en: "Barcelona", lng: 2.1734, lat: 41.3851, country: "ES" },
  { slug: "brussels", zh: "布鲁塞尔", en: "Brussels", lng: 4.3517, lat: 50.8503, country: "BE" },
  { slug: "stockholm", zh: "斯德哥尔摩", en: "Stockholm", lng: 18.0686, lat: 59.3293, country: "SE" },
  { slug: "boston", zh: "波士顿", en: "Boston", lng: -71.0589, lat: 42.3601, country: "US" },
  { slug: "philadelphia", zh: "费城", en: "Philadelphia", lng: -75.1652, lat: 39.9526, country: "US" },
  { slug: "chicago", zh: "芝加哥", en: "Chicago", lng: -87.6298, lat: 41.8781, country: "US" },
  { slug: "los-angeles", zh: "洛杉矶", en: "Los Angeles", lng: -118.2437, lat: 34.0522, country: "US" },
  { slug: "buffalo", zh: "布法罗", en: "Buffalo", lng: -78.8784, lat: 42.8864, country: "US" },
];

export const ARTISTS: ExpansionArtist[] = [
  { slug: "myron", zh: "米隆", en: "Myron", fullEn: "Myron of Eleutherae", birth: -480, death: -440, chapter: "classical-antiquity", importance: 4, movements: ["classicism"], mainLocation: "athens" },
  { slug: "praxiteles", zh: "普拉克西特列斯", en: "Praxiteles", fullEn: "Praxiteles of Athens", birth: null, death: null, chapter: "classical-antiquity", importance: 4, movements: ["classicism"], mainLocation: "athens" },
  { slug: "lysippos", zh: "利西波斯", en: "Lysippos", fullEn: "Lysippos of Sikyon", birth: null, death: null, chapter: "classical-antiquity", importance: 4, movements: ["classicism"], mainLocation: "athens" },
  { slug: "anthemius-of-tralles", zh: "特拉勒斯的安提米乌斯", en: "Anthemius of Tralles", birth: 474, death: 558, chapter: "medieval", importance: 4, movements: ["byzantine"], mainLocation: "istanbul" },
  { slug: "isidore-of-miletus", zh: "米利都的伊西多尔", en: "Isidore of Miletus", birth: 442, death: 537, chapter: "medieval", importance: 4, movements: ["byzantine"], mainLocation: "istanbul" },
  { slug: "gislebertus", zh: "吉斯勒贝尔图斯", en: "Gislebertus", birth: null, death: null, chapter: "medieval", importance: 4, movements: ["romanism"], mainLocation: "autun" },
  { slug: "nicola-pisano", zh: "尼古拉·皮萨诺", en: "Nicola Pisano", birth: 1220, death: 1284, chapter: "medieval", importance: 4, movements: ["gothic"], mainLocation: "pisa" },
  { slug: "simone-martini", zh: "西蒙娜·马蒂尼", en: "Simone Martini", birth: 1284, death: 1344, chapter: "medieval", importance: 4, movements: ["gothic"], mainLocation: "siena" },
  { slug: "donatello", zh: "多纳泰罗", en: "Donatello", fullEn: "Donato di Niccolò di Betto Bardi", birth: 1386, death: 1466, chapter: "renaissance", importance: 5, movements: ["renaissance-humanism"], mainLocation: "florence" },
  { slug: "andrea-mantegna", zh: "安德烈亚·曼特尼亚", en: "Andrea Mantegna", birth: 1431, death: 1506, chapter: "renaissance", importance: 4, movements: ["renaissance-humanism"], mainLocation: "padua" },
  { slug: "pieter-bruegel-elder", zh: "老彼得·勃鲁盖尔", en: "Pieter Bruegel the Elder", birth: 1525, death: 1569, chapter: "renaissance", importance: 5, movements: ["renaissance-humanism"], mainLocation: "antwerp" },
  { slug: "hans-holbein-younger", zh: "小汉斯·霍尔拜因", en: "Hans Holbein the Younger", birth: 1497, death: 1543, chapter: "renaissance", importance: 4, movements: ["renaissance-humanism"], mainLocation: "london" },
  { slug: "gian-lorenzo-bernini", zh: "吉安·洛伦佐·贝尼尼", en: "Gian Lorenzo Bernini", birth: 1598, death: 1680, chapter: "baroque", importance: 5, movements: ["baroque"], mainLocation: "rome" },
  { slug: "frans-hals", zh: "弗兰斯·哈尔斯", en: "Frans Hals", birth: 1582, death: 1666, chapter: "baroque", importance: 4, movements: ["baroque"], mainLocation: "haarlem" },
  { slug: "georges-de-la-tour", zh: "乔治·德·拉图尔", en: "Georges de La Tour", birth: 1593, death: 1652, chapter: "baroque", importance: 4, movements: ["baroque"], mainLocation: "paris" },
  { slug: "antoine-watteau", zh: "安托万·华托", en: "Antoine Watteau", fullEn: "Jean-Antoine Watteau", birth: 1684, death: 1721, chapter: "baroque", importance: 4, movements: ["rococo"], mainLocation: "paris" },
  { slug: "francois-boucher", zh: "弗朗索瓦·布歇", en: "François Boucher", birth: 1703, death: 1770, chapter: "baroque", importance: 4, movements: ["rococo"], mainLocation: "paris" },
  { slug: "jean-auguste-ingres", zh: "让-奥古斯特-多米尼克·安格尔", en: "Jean-Auguste-Dominique Ingres", birth: 1780, death: 1867, chapter: "neoclassicism-and-romanticism", importance: 4, movements: ["neoclassicism"], mainLocation: "paris" },
  { slug: "theodore-gericault", zh: "泰奥多尔·席里柯", en: "Théodore Géricault", fullEn: "Jean-Louis André Théodore Géricault", birth: 1791, death: 1824, chapter: "neoclassicism-and-romanticism", importance: 4, movements: ["romanticism"], mainLocation: "paris" },
  { slug: "john-constable", zh: "约翰·康斯特布尔", en: "John Constable", birth: 1776, death: 1837, chapter: "neoclassicism-and-romanticism", importance: 4, movements: ["romanticism"], mainLocation: "london" },
  { slug: "william-blake", zh: "威廉·布莱克", en: "William Blake", birth: 1757, death: 1827, chapter: "neoclassicism-and-romanticism", importance: 4, movements: ["romanticism"], mainLocation: "london" },
  { slug: "jean-francois-millet", zh: "让-弗朗索瓦·米勒", en: "Jean-François Millet", birth: 1814, death: 1875, chapter: "modernism", importance: 4, movements: ["realism"], mainLocation: "paris" },
  { slug: "honore-daumier", zh: "奥诺雷·杜米埃", en: "Honoré Daumier", birth: 1808, death: 1879, chapter: "modernism", importance: 4, movements: ["realism"], mainLocation: "paris" },
  { slug: "berthe-morisot", zh: "贝尔特·莫里索", en: "Berthe Morisot", fullEn: "Berthe Marie Pauline Morisot", birth: 1841, death: 1895, chapter: "modernism", importance: 4, movements: ["impressionism"], mainLocation: "paris", gender: "female" },
  { slug: "mary-cassatt", zh: "玛丽·卡萨特", en: "Mary Cassatt", fullEn: "Mary Stevenson Cassatt", birth: 1844, death: 1926, chapter: "modernism", importance: 4, movements: ["impressionism"], mainLocation: "paris", gender: "female" },
  { slug: "auguste-rodin", zh: "奥古斯特·罗丹", en: "Auguste Rodin", fullEn: "François-Auguste-René Rodin", birth: 1840, death: 1917, chapter: "modernism-early", importance: 5, movements: ["symbolism"], mainLocation: "paris" },
  { slug: "edvard-munch", zh: "爱德华·蒙克", en: "Edvard Munch", birth: 1863, death: 1944, chapter: "modernism-early", importance: 5, movements: ["symbolism", "expressionism"], mainLocation: "oslo" },
  { slug: "gustav-klimt", zh: "古斯塔夫·克里姆特", en: "Gustav Klimt", birth: 1862, death: 1918, chapter: "modernism-early", importance: 5, movements: ["symbolism"], mainLocation: "vienna" },
  { slug: "marcel-duchamp", zh: "马塞尔·杜尚", en: "Marcel Duchamp", fullEn: "Henri-Robert-Marcel Duchamp", birth: 1887, death: 1968, chapter: "modernism-and-war", importance: 5, movements: ["dada"], mainLocation: "paris" },
  { slug: "kazimir-malevich", zh: "卡济米尔·马列维奇", en: "Kazimir Malevich", fullEn: "Kazimir Severinovich Malevich", birth: 1879, death: 1935, chapter: "modernism-and-war", importance: 5, movements: ["suprematism"], mainLocation: "moscow" },
  { slug: "kathe-kollwitz", zh: "凯绥·柯勒惠支", en: "Käthe Kollwitz", fullEn: "Käthe Schmidt Kollwitz", birth: 1867, death: 1945, chapter: "modernism-and-war", importance: 5, movements: ["expressionism"], mainLocation: "berlin", gender: "female" },
  { slug: "salvador-dali", zh: "萨尔瓦多·达利", en: "Salvador Dalí", fullEn: "Salvador Domingo Felipe Jacinto Dalí i Domènech", birth: 1904, death: 1989, chapter: "modernism-and-war", importance: 5, movements: ["surrealism"], mainLocation: "madrid" },
  { slug: "rene-magritte", zh: "勒内·马格利特", en: "René Magritte", fullEn: "René François Ghislain Magritte", birth: 1898, death: 1967, chapter: "modernism-and-war", importance: 5, movements: ["surrealism"], mainLocation: "brussels" },
  { slug: "joan-miro", zh: "胡安·米罗", en: "Joan Miró", fullEn: "Joan Miró i Ferrà", birth: 1893, death: 1983, chapter: "modernism-and-war", importance: 5, movements: ["surrealism"], mainLocation: "barcelona" },
];

export const ARTWORKS: ExpansionArtwork[] = [
  { slug: "doryphoros", zh: "持矛者", en: "Doryphoros", artists: ["polykleitos"], start: -440, end: -440, timeType: "approximate", medium: "bronze original known through marble copies", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "naples", status: "attributed" },
  { slug: "discobolus", zh: "掷铁饼者", en: "Discobolus", artists: ["myron"], start: -460, end: -450, timeType: "approximate", medium: "bronze original known through marble copies", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "rome", status: "attributed" },
  { slug: "athena-and-marsyas", zh: "雅典娜与马尔叙阿斯", en: "Athena and Marsyas", artists: ["myron"], start: -450, end: -450, timeType: "approximate", medium: "bronze group known through later copies", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "rome", status: "attributed" },
  { slug: "aphrodite-of-knidos", zh: "克尼多斯的阿佛洛狄忒", en: "Aphrodite of Knidos", artists: ["praxiteles"], start: -350, end: -340, timeType: "approximate", medium: "marble sculpture known through Roman copies", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "rome", status: "attributed" },
  { slug: "hermes-infant-dionysus", zh: "赫尔墨斯与婴儿狄俄尼索斯", en: "Hermes and the Infant Dionysus", artists: ["praxiteles"], start: -340, end: -330, timeType: "approximate", medium: "marble sculpture", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "olympia", currentLocation: "olympia", status: "attributed" },
  { slug: "apoxyomenos", zh: "刮汗污者", en: "Apoxyomenos", artists: ["lysippos"], start: -330, end: -320, timeType: "approximate", medium: "bronze original known through marble copies", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "rome", status: "attributed" },
  { slug: "farnese-hercules", zh: "法尔内塞的赫拉克勒斯", en: "Farnese Hercules", artists: ["lysippos"], start: -320, end: -310, timeType: "approximate", medium: "bronze prototype known through a Roman marble copy", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "naples", status: "attributed" },
  { slug: "winged-victory-samothrace", zh: "萨莫色雷斯的胜利女神", en: "Winged Victory of Samothrace", artists: [], start: -190, end: -190, timeType: "approximate", medium: "marble sculpture", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "athens", currentLocation: "paris" },
  { slug: "laocoon-and-sons", zh: "拉奥孔与儿子们", en: "Laocoön and His Sons", artists: [], start: -40, end: -20, timeType: "range", medium: "marble sculpture", chapter: "classical-antiquity", movements: ["classicism"], creationLocation: "rome", currentLocation: "rome", status: "attributed" },

  { slug: "hagia-sophia", zh: "圣索菲亚大教堂", en: "Hagia Sophia", artists: ["anthemius-of-tralles", "isidore-of-miletus"], start: 532, end: 537, medium: "masonry, brick, marble and mosaic architecture", chapter: "medieval", movements: ["byzantine"], creationLocation: "istanbul", currentLocation: "istanbul" },
  { slug: "autun-last-judgment", zh: "欧坦主教座堂《最后的审判》门楣", en: "Last Judgment Tympanum at Autun Cathedral", artists: ["gislebertus"], start: 1120, end: 1135, medium: "limestone architectural sculpture", chapter: "medieval", movements: ["romanism"], creationLocation: "autun", currentLocation: "autun" },
  { slug: "eve-autun", zh: "欧坦的夏娃", en: "Eve from Autun Cathedral", artists: ["gislebertus"], start: 1130, end: 1130, timeType: "approximate", medium: "limestone relief", chapter: "medieval", movements: ["romanism"], creationLocation: "autun", currentLocation: "autun", status: "attributed" },
  { slug: "pisa-baptistery-pulpit", zh: "比萨洗礼堂讲道坛", en: "Pisa Baptistery Pulpit", artists: ["nicola-pisano"], start: 1255, end: 1260, medium: "marble sculpture and architecture", chapter: "medieval", movements: ["gothic"], creationLocation: "pisa", currentLocation: "pisa" },
  { slug: "siena-cathedral-pulpit", zh: "锡耶纳主教座堂讲道坛", en: "Siena Cathedral Pulpit", artists: ["nicola-pisano"], start: 1265, end: 1268, medium: "marble sculpture and architecture", chapter: "medieval", movements: ["gothic"], creationLocation: "siena", currentLocation: "siena" },
  { slug: "simone-martini-maesta", zh: "锡耶纳市政厅《圣母荣登宝座》", en: "Maestà in the Palazzo Pubblico", artists: ["simone-martini"], start: 1315, end: 1315, medium: "fresco", chapter: "medieval", movements: ["gothic"], creationLocation: "siena", currentLocation: "siena" },
  { slug: "simone-martini-annunciation", zh: "《圣告》与圣玛格丽特、圣安萨努斯", en: "Annunciation with Saint Margaret and Saint Ansanus", artists: ["simone-martini"], start: 1333, end: 1333, medium: "tempera and gold on panel", chapter: "medieval", movements: ["gothic"], creationLocation: "siena", currentLocation: "florence" },
  { slug: "duccio-maesta", zh: "杜乔《圣母荣登宝座》", en: "Duccio's Maestà", artists: ["duccio"], start: 1308, end: 1311, medium: "tempera and gold on panel", chapter: "medieval", movements: ["gothic"], creationLocation: "siena", currentLocation: "siena" },
  { slug: "rucellai-madonna", zh: "鲁切莱圣母", en: "Rucellai Madonna", artists: ["duccio"], start: 1285, end: 1285, timeType: "approximate", medium: "tempera and gold on panel", chapter: "medieval", movements: ["gothic"], creationLocation: "florence", currentLocation: "florence", status: "attributed" },
  { slug: "book-of-kells", zh: "凯尔经", en: "Book of Kells", artists: [], start: 800, end: 800, timeType: "approximate", medium: "illuminated manuscript on vellum", chapter: "medieval", movements: ["gothic"], creationLocation: "dublin", currentLocation: "dublin" },
  { slug: "bayeux-tapestry", zh: "巴约挂毯", en: "Bayeux Tapestry", artists: [], start: 1070, end: 1080, medium: "wool embroidery on linen", chapter: "medieval", movements: ["romanism"], creationLocation: "bayeux", currentLocation: "bayeux" },
  { slug: "sainte-foy-reliquary", zh: "圣福瓦圣髑匣", en: "Reliquary of Sainte-Foy", artists: [], start: 900, end: 1000, medium: "gold, gemstones and wood reliquary", chapter: "medieval", movements: ["romanism"], creationLocation: "conques", currentLocation: "conques" },
  { slug: "chartres-west-portals", zh: "沙特尔主教座堂西立面王室门", en: "Royal Portal of Chartres Cathedral", artists: [], start: 1145, end: 1155, medium: "limestone architectural sculpture", chapter: "medieval", movements: ["gothic"], creationLocation: "chartres", currentLocation: "chartres" },
  { slug: "wilton-diptych", zh: "威尔顿双联画", en: "Wilton Diptych", artists: [], start: 1395, end: 1399, medium: "tempera and gold leaf on oak", chapter: "medieval", movements: ["gothic"], creationLocation: "london", currentLocation: "london" },
  { slug: "daphni-pantocrator", zh: "达夫尼修道院基督全能者镶嵌画", en: "Christ Pantocrator at Daphni Monastery", artists: [], start: 1100, end: 1100, timeType: "approximate", medium: "mosaic", chapter: "medieval", movements: ["byzantine"], creationLocation: "athens", currentLocation: "athens" },

  { slug: "tribute-money-masaccio", zh: "纳税银", en: "The Tribute Money", artists: ["masaccio"], start: 1425, end: 1427, medium: "fresco", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "florence", currentLocation: "florence" },
  { slug: "holy-trinity-masaccio", zh: "圣三位一体", en: "The Holy Trinity", artists: ["masaccio"], start: 1425, end: 1428, medium: "fresco", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "florence", currentLocation: "florence" },
  { slug: "assumption-virgin-titian", zh: "圣母升天", en: "Assumption of the Virgin", artists: ["titian"], start: 1516, end: 1518, medium: "oil on panel", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "venice", currentLocation: "venice" },
  { slug: "venus-of-urbino", zh: "乌尔比诺的维纳斯", en: "Venus of Urbino", artists: ["titian"], start: 1538, end: 1538, medium: "oil on canvas", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "venice", currentLocation: "florence" },
  { slug: "david-donatello", zh: "多纳泰罗《大卫》", en: "David by Donatello", artists: ["donatello"], start: 1440, end: 1440, timeType: "approximate", medium: "bronze sculpture", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "florence", currentLocation: "florence" },
  { slug: "gattamelata", zh: "加塔梅拉塔骑马像", en: "Equestrian Monument of Gattamelata", artists: ["donatello"], start: 1447, end: 1453, medium: "bronze equestrian monument", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "padua", currentLocation: "padua" },
  { slug: "dead-christ-mantegna", zh: "哀悼死去的基督", en: "Lamentation over the Dead Christ", artists: ["andrea-mantegna"], start: 1480, end: 1480, timeType: "approximate", medium: "tempera on canvas", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "padua", currentLocation: "milan" },
  { slug: "hunters-in-snow", zh: "雪中猎人", en: "The Hunters in the Snow", artists: ["pieter-bruegel-elder"], start: 1565, end: 1565, medium: "oil on panel", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "antwerp", currentLocation: "vienna" },
  { slug: "the-ambassadors", zh: "大使们", en: "The Ambassadors", artists: ["hans-holbein-younger"], start: 1533, end: 1533, medium: "oil and tempera on oak", chapter: "renaissance", movements: ["renaissance-humanism"], creationLocation: "london", currentLocation: "london" },

  { slug: "calling-saint-matthew", zh: "圣马太蒙召", en: "The Calling of Saint Matthew", artists: ["caravaggio"], start: 1599, end: 1600, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "rome", currentLocation: "rome" },
  { slug: "supper-at-emmaus-caravaggio", zh: "以马忤斯的晚餐", en: "Supper at Emmaus", artists: ["caravaggio"], start: 1601, end: 1601, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "rome", currentLocation: "london" },
  { slug: "las-meninas", zh: "宫娥", en: "Las Meninas", artists: ["velazquez"], start: 1656, end: 1656, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "madrid", currentLocation: "madrid" },
  { slug: "surrender-of-breda", zh: "布雷达的投降", en: "The Surrender of Breda", artists: ["velazquez"], start: 1634, end: 1635, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "madrid", currentLocation: "madrid" },
  { slug: "anatomy-lesson-dr-tulp", zh: "杜普教授的解剖课", en: "The Anatomy Lesson of Dr Nicolaes Tulp", artists: ["rembrandt"], start: 1632, end: 1632, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "amsterdam", currentLocation: "the-hague" },
  { slug: "return-prodigal-son-rembrandt", zh: "浪子回头", en: "The Return of the Prodigal Son", artists: ["rembrandt"], start: 1668, end: 1669, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "amsterdam", currentLocation: "saint-petersburg" },
  { slug: "ecstasy-saint-teresa", zh: "圣德肋撒的神魂超拔", en: "The Ecstasy of Saint Teresa", artists: ["gian-lorenzo-bernini"], start: 1647, end: 1652, medium: "marble, stucco and architectural ensemble", chapter: "baroque", movements: ["baroque"], creationLocation: "rome", currentLocation: "rome" },
  { slug: "apollo-and-daphne", zh: "阿波罗与达芙妮", en: "Apollo and Daphne", artists: ["gian-lorenzo-bernini"], start: 1622, end: 1625, medium: "marble sculpture", chapter: "baroque", movements: ["baroque"], creationLocation: "rome", currentLocation: "rome" },
  { slug: "saint-peters-square", zh: "圣彼得广场柱廊", en: "Saint Peter's Square and Colonnade", artists: ["gian-lorenzo-bernini"], start: 1656, end: 1667, medium: "stone architecture and urban design", chapter: "baroque", movements: ["baroque"], creationLocation: "rome", currentLocation: "rome" },
  { slug: "laughing-cavalier", zh: "微笑的骑士", en: "The Laughing Cavalier", artists: ["frans-hals"], start: 1624, end: 1624, medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "haarlem", currentLocation: "london" },
  { slug: "magdalene-smoking-flame", zh: "烛光前的抹大拉的马利亚", en: "The Magdalen with the Smoking Flame", artists: ["georges-de-la-tour"], start: 1640, end: 1640, timeType: "approximate", medium: "oil on canvas", chapter: "baroque", movements: ["baroque"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "pilgrimage-cythera", zh: "舟发西苔岛", en: "Pilgrimage to Cythera", artists: ["antoine-watteau"], start: 1717, end: 1717, medium: "oil on canvas", chapter: "baroque", movements: ["rococo"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "pierrot-watteau", zh: "皮埃罗", en: "Pierrot", artists: ["antoine-watteau"], start: 1718, end: 1719, medium: "oil on canvas", chapter: "baroque", movements: ["rococo"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "triumph-of-venus-boucher", zh: "维纳斯的凯旋", en: "The Triumph of Venus", artists: ["francois-boucher"], start: 1740, end: 1740, medium: "oil on canvas", chapter: "baroque", movements: ["rococo"], creationLocation: "paris", currentLocation: "stockholm" },
  { slug: "diana-resting-boucher", zh: "沐浴后的狄安娜", en: "Diana Resting after Her Bath", artists: ["francois-boucher"], start: 1742, end: 1742, medium: "oil on canvas", chapter: "baroque", movements: ["rococo"], creationLocation: "paris", currentLocation: "paris" },

  { slug: "oath-of-horatii", zh: "荷拉斯兄弟之誓", en: "The Oath of the Horatii", artists: ["jacques-louis-david"], start: 1784, end: 1784, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["neoclassicism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "death-of-marat", zh: "马拉之死", en: "The Death of Marat", artists: ["jacques-louis-david"], start: 1793, end: 1793, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["neoclassicism"], creationLocation: "paris", currentLocation: "brussels" },
  { slug: "fighting-temeraire", zh: "战舰无畏号", en: "The Fighting Temeraire", artists: ["j-m-w-turner"], start: 1839, end: 1839, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },
  { slug: "snow-storm-hannibal", zh: "暴风雪：汉尼拔率军越过阿尔卑斯山", en: "Snow Storm: Hannibal and his Army Crossing the Alps", artists: ["j-m-w-turner"], start: 1812, end: 1812, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },
  { slug: "ulysses-deriding-polyphemus", zh: "尤利西斯嘲弄波吕斐摩斯", en: "Ulysses Deriding Polyphemus", artists: ["j-m-w-turner"], start: 1829, end: 1829, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },
  { slug: "grande-odalisque", zh: "大宫女", en: "Grande Odalisque", artists: ["jean-auguste-ingres"], start: 1814, end: 1814, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["neoclassicism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "apotheosis-of-homer", zh: "荷马的礼赞", en: "The Apotheosis of Homer", artists: ["jean-auguste-ingres"], start: 1827, end: 1827, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["neoclassicism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "raft-of-medusa", zh: "梅杜萨之筏", en: "The Raft of the Medusa", artists: ["theodore-gericault"], start: 1818, end: 1819, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "hay-wain-constable", zh: "干草车", en: "The Hay Wain", artists: ["john-constable"], start: 1821, end: 1821, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },
  { slug: "salisbury-cathedral-meadows", zh: "从草地望索尔兹伯里大教堂", en: "Salisbury Cathedral from the Meadows", artists: ["john-constable"], start: 1831, end: 1831, medium: "oil on canvas", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },
  { slug: "ancient-of-days", zh: "亘古常在者", en: "The Ancient of Days", artists: ["william-blake"], start: 1794, end: 1794, medium: "relief etching with watercolour", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },
  { slug: "newton-blake", zh: "牛顿", en: "Newton", artists: ["william-blake"], start: 1795, end: 1805, medium: "colour print with ink and watercolour", chapter: "neoclassicism-and-romanticism", movements: ["romanticism"], creationLocation: "london", currentLocation: "london" },

  { slug: "impression-sunrise", zh: "印象·日出", en: "Impression, Sunrise", artists: ["claude-monet"], start: 1872, end: 1872, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "boulevard-des-capucines", zh: "卡普辛大道", en: "Boulevard des Capucines", artists: ["claude-monet"], start: 1873, end: 1874, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "woman-with-parasol", zh: "撑阳伞的女人", en: "Woman with a Parasol", artists: ["claude-monet"], start: 1875, end: 1875, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "washington-dc" },
  { slug: "gare-saint-lazare", zh: "圣拉扎尔火车站", en: "The Gare Saint-Lazare", artists: ["claude-monet"], start: 1877, end: 1877, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "gleaners-millet", zh: "拾穗者", en: "The Gleaners", artists: ["jean-francois-millet"], start: 1857, end: 1857, medium: "oil on canvas", chapter: "modernism", movements: ["realism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "angelus-millet", zh: "晚钟", en: "The Angelus", artists: ["jean-francois-millet"], start: 1857, end: 1859, medium: "oil on canvas", chapter: "modernism", movements: ["realism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "third-class-carriage", zh: "三等车厢", en: "The Third-Class Carriage", artists: ["honore-daumier"], start: 1862, end: 1864, medium: "oil on canvas", chapter: "modernism", movements: ["realism"], creationLocation: "paris", currentLocation: "new-york" },
  { slug: "laundress-daumier", zh: "洗衣妇", en: "The Laundress", artists: ["honore-daumier"], start: 1863, end: 1863, timeType: "approximate", medium: "oil on panel", chapter: "modernism", movements: ["realism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "cradle-morisot", zh: "摇篮", en: "The Cradle", artists: ["berthe-morisot"], start: 1872, end: 1872, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "summers-day-morisot", zh: "夏日", en: "Summer's Day", artists: ["berthe-morisot"], start: 1879, end: 1879, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "london" },
  { slug: "in-the-loge-cassatt", zh: "包厢中", en: "In the Loge", artists: ["mary-cassatt"], start: 1878, end: 1878, medium: "oil on canvas", chapter: "modernism", movements: ["impressionism"], creationLocation: "paris", currentLocation: "boston" },

  { slug: "sunflowers-van-gogh", zh: "向日葵", en: "Sunflowers", artists: ["van-gogh"], start: 1888, end: 1888, medium: "oil on canvas", chapter: "modernism-early", movements: ["post-impressionism"], creationLocation: "saint-remy-de-provence", currentLocation: "london" },
  { slug: "bedroom-arles", zh: "阿尔勒的卧室", en: "The Bedroom", artists: ["van-gogh"], start: 1888, end: 1889, medium: "oil on canvas", chapter: "modernism-early", movements: ["post-impressionism"], creationLocation: "saint-remy-de-provence", currentLocation: "amsterdam" },
  { slug: "thinker-rodin", zh: "思想者", en: "The Thinker", artists: ["auguste-rodin"], start: 1880, end: 1904, medium: "bronze sculpture", chapter: "modernism-early", movements: ["symbolism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "kiss-rodin", zh: "吻", en: "The Kiss", artists: ["auguste-rodin"], start: 1882, end: 1889, medium: "marble sculpture", chapter: "modernism-early", movements: ["symbolism"], creationLocation: "paris", currentLocation: "paris" },
  { slug: "scream-munch", zh: "呐喊", en: "The Scream", artists: ["edvard-munch"], start: 1893, end: 1893, medium: "tempera and crayon on cardboard", chapter: "modernism-early", movements: ["symbolism", "expressionism"], creationLocation: "oslo", currentLocation: "oslo" },
  { slug: "madonna-munch", zh: "圣母", en: "Madonna", artists: ["edvard-munch"], start: 1894, end: 1895, medium: "oil on canvas", chapter: "modernism-early", movements: ["symbolism", "expressionism"], creationLocation: "oslo", currentLocation: "oslo" },
  { slug: "judith-i-klimt", zh: "朱迪思 I", en: "Judith I", artists: ["gustav-klimt"], start: 1901, end: 1901, medium: "oil and gold leaf on canvas", chapter: "modernism-early", movements: ["symbolism"], creationLocation: "vienna", currentLocation: "vienna" },

  { slug: "demoiselles-avignon", zh: "亚维农少女", en: "Les Demoiselles d'Avignon", artists: ["pablo-picasso"], start: 1907, end: 1907, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["cubism"], creationLocation: "paris", currentLocation: "new-york" },
  { slug: "guernica", zh: "格尔尼卡", en: "Guernica", artists: ["pablo-picasso"], start: 1937, end: 1937, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["cubism"], creationLocation: "paris", currentLocation: "madrid" },
  { slug: "three-musicians-picasso", zh: "三个音乐家", en: "Three Musicians", artists: ["pablo-picasso"], start: 1921, end: 1921, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["cubism"], creationLocation: "paris", currentLocation: "new-york" },
  { slug: "composition-vii", zh: "构图 VII", en: "Composition VII", artists: ["wassily-kandinsky"], start: 1913, end: 1913, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["expressionism"], creationLocation: "munich", currentLocation: "moscow" },
  { slug: "yellow-red-blue", zh: "黄-红-蓝", en: "Yellow-Red-Blue", artists: ["wassily-kandinsky"], start: 1925, end: 1925, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["bauhaus"], creationLocation: "munich", currentLocation: "paris" },
  { slug: "several-circles", zh: "几个圆", en: "Several Circles", artists: ["wassily-kandinsky"], start: 1926, end: 1926, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["bauhaus"], creationLocation: "munich", currentLocation: "new-york" },
  { slug: "nude-descending-staircase", zh: "下楼梯的裸女二号", en: "Nude Descending a Staircase, No. 2", artists: ["marcel-duchamp"], start: 1912, end: 1912, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["dada", "cubism"], creationLocation: "paris", currentLocation: "philadelphia" },
  { slug: "bicycle-wheel", zh: "自行车轮", en: "Bicycle Wheel", artists: ["marcel-duchamp"], start: 1913, end: 1913, medium: "bicycle wheel and stool readymade", chapter: "modernism-and-war", movements: ["dada"], creationLocation: "paris", currentLocation: "new-york", status: "lost" },
  { slug: "fountain-duchamp", zh: "泉", en: "Fountain", artists: ["marcel-duchamp"], start: 1917, end: 1917, medium: "porcelain urinal readymade", chapter: "modernism-and-war", movements: ["dada"], creationLocation: "new-york", currentLocation: "new-york", status: "lost" },
  { slug: "black-square", zh: "黑方块", en: "Black Square", artists: ["kazimir-malevich"], start: 1915, end: 1915, medium: "oil on linen", chapter: "modernism-and-war", movements: ["suprematism"], creationLocation: "moscow", currentLocation: "moscow" },
  { slug: "white-on-white", zh: "白上白", en: "White on White", artists: ["kazimir-malevich"], start: 1918, end: 1918, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["suprematism"], creationLocation: "moscow", currentLocation: "new-york" },
  { slug: "volunteers-kollwitz", zh: "志愿者", en: "The Volunteers", artists: ["kathe-kollwitz"], start: 1922, end: 1922, medium: "woodcut", chapter: "modernism-and-war", movements: ["expressionism"], creationLocation: "berlin", currentLocation: "berlin" },
  { slug: "never-again-war", zh: "不要再有战争", en: "Never Again War", artists: ["kathe-kollwitz"], start: 1924, end: 1924, medium: "lithographic poster", chapter: "modernism-and-war", movements: ["expressionism"], creationLocation: "berlin", currentLocation: "berlin" },
  { slug: "mothers-kollwitz", zh: "母亲们", en: "The Mothers", artists: ["kathe-kollwitz"], start: 1919, end: 1922, medium: "woodcut", chapter: "modernism-and-war", movements: ["expressionism"], creationLocation: "berlin", currentLocation: "berlin" },
  { slug: "persistence-of-memory", zh: "记忆的永恒", en: "The Persistence of Memory", artists: ["salvador-dali"], start: 1931, end: 1931, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "madrid", currentLocation: "new-york" },
  { slug: "metamorphosis-narcissus", zh: "纳西索斯的变形", en: "Metamorphosis of Narcissus", artists: ["salvador-dali"], start: 1937, end: 1937, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "madrid", currentLocation: "london" },
  { slug: "soft-construction-boiled-beans", zh: "内战的预感", en: "Soft Construction with Boiled Beans", artists: ["salvador-dali"], start: 1936, end: 1936, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "madrid", currentLocation: "philadelphia" },
  { slug: "treachery-of-images", zh: "形象的背叛", en: "The Treachery of Images", artists: ["rene-magritte"], start: 1929, end: 1929, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "brussels", currentLocation: "los-angeles" },
  { slug: "lovers-magritte", zh: "恋人", en: "The Lovers", artists: ["rene-magritte"], start: 1928, end: 1928, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "brussels", currentLocation: "new-york" },
  { slug: "false-mirror", zh: "虚假的镜子", en: "The False Mirror", artists: ["rene-magritte"], start: 1929, end: 1929, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "brussels", currentLocation: "new-york" },
  { slug: "harlequins-carnival", zh: "丑角的狂欢节", en: "Harlequin's Carnival", artists: ["joan-miro"], start: 1924, end: 1925, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "barcelona", currentLocation: "buffalo" },
  { slug: "dutch-interior-i", zh: "荷兰室内景一号", en: "Dutch Interior I", artists: ["joan-miro"], start: 1928, end: 1928, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "barcelona", currentLocation: "new-york" },
  { slug: "woman-bird-night", zh: "夜中的女人与鸟", en: "Woman and Bird in the Night", artists: ["joan-miro"], start: 1945, end: 1945, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["surrealism"], creationLocation: "barcelona", currentLocation: "barcelona" },
  { slug: "open-window-collioure", zh: "科利乌尔的开窗", en: "Open Window, Collioure", artists: ["henri-matisse"], start: 1905, end: 1905, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["fauvism"], creationLocation: "paris", currentLocation: "washington-dc" },
  { slug: "joy-of-life", zh: "生之喜悦", en: "The Joy of Life", artists: ["henri-matisse"], start: 1905, end: 1906, medium: "oil on canvas", chapter: "modernism-and-war", movements: ["fauvism"], creationLocation: "paris", currentLocation: "philadelphia" },
  { slug: "victory-boogie-woogie", zh: "胜利爵士乐", en: "Victory Boogie Woogie", artists: ["piet-mondrian"], start: 1942, end: 1944, medium: "oil, paper and tape on canvas", chapter: "modernism-and-war", movements: ["de-stijl"], creationLocation: "new-york", currentLocation: "the-hague" },
];

export const RELATIONS: ExpansionRelation[] = [
  { from: "polykleitos", to: "lysippos", type: "influence", strength: 4, zh: "古典雕塑比例传统", en: "Classical sculptural proportion", summaryZh: "利西波斯在古典人体比例传统上发展出更修长、动态的观看体系。", summaryEn: "Lysippos developed a more slender and dynamic system from the classical tradition of bodily proportion." },
  { from: "nicola-pisano", to: "giotto", type: "influence", strength: 3, zh: "意大利自然主义先声", en: "Italian naturalist precedent", summaryZh: "皮萨诺雕塑中的古典体量与叙事清晰度，为意大利后续自然主义图像提供先例。", summaryEn: "Pisano's classical volume and narrative clarity provided precedents for later Italian naturalism." },
  { from: "duccio", to: "simone-martini", type: "influence", strength: 4, zh: "锡耶纳画派传承", en: "Sienese school succession", summaryZh: "马蒂尼承接杜乔的金地、线性节奏与锡耶纳祭坛画传统。", summaryEn: "Martini carried forward Duccio's gold grounds, linear rhythm and Sienese altarpiece tradition." },
  { from: "donatello", to: "michelangelo", type: "influence", strength: 4, zh: "佛罗伦萨雕塑影响", en: "Florentine sculptural influence", summaryZh: "多纳泰罗对人体、古典姿态与公共雕塑的探索成为米开朗基罗的重要前例。", summaryEn: "Donatello's work with the body, classical pose and public sculpture formed an important precedent for Michelangelo." },
  { from: "andrea-mantegna", to: "albrecht-durer", type: "influence", strength: 3, zh: "版画与古典形式传播", en: "Print and classical-form transmission", summaryZh: "曼特尼亚的古典化构图和版画传播进入北方艺术家的视觉资源。", summaryEn: "Mantegna's classicising compositions and prints entered the visual resources available to northern artists." },
  { from: "caravaggio", to: "georges-de-la-tour", type: "influence", strength: 4, zh: "烛光与明暗法影响", en: "Candlelight and chiaroscuro influence", summaryZh: "德·拉图以更克制的烛光场景回应卡拉瓦乔式明暗与现实人物。", summaryEn: "La Tour answered Caravaggesque chiaroscuro and observed figures with more restrained candlelit scenes." },
  { from: "gian-lorenzo-bernini", to: "peter-paul-rubens", type: "parallel", strength: 3, zh: "巴洛克动态语言", en: "Baroque language of movement", summaryZh: "贝尼尼与鲁本斯分别在雕塑空间和绘画中发展巴洛克的动态、戏剧与身体能量。", summaryEn: "Bernini and Rubens developed Baroque movement, drama and bodily energy in sculpture and painting respectively." },
  { from: "antoine-watteau", to: "francois-boucher", type: "influence", strength: 4, zh: "洛可可宫廷绘画传承", en: "Rococo court-painting succession", summaryZh: "布歇继承并扩展华托的雅宴、舞台感与宫廷趣味。", summaryEn: "Boucher inherited and expanded Watteau's fêtes galantes, theatricality and courtly taste." },
  { from: "jacques-louis-david", to: "jean-auguste-ingres", type: "mentor", strength: 5, zh: "学院师承", en: "Academic mentorship", summaryZh: "安格尔在大卫的工作室训练中形成新古典主义素描与历史画基础。", summaryEn: "Ingres formed his Neoclassical foundation in drawing and history painting through training in David's studio." },
  { from: "theodore-gericault", to: "eugene-delacroix", type: "influence", strength: 4, zh: "浪漫主义历史画影响", en: "Romantic history-painting influence", summaryZh: "席里柯的巨大尺幅、现实灾难与动态构图成为德拉克罗瓦的重要参照。", summaryEn: "Géricault's scale, contemporary catastrophe and dynamic composition became an important reference for Delacroix." },
  { from: "john-constable", to: "eugene-delacroix", type: "influence", strength: 3, zh: "风景色彩影响", en: "Landscape-colour influence", summaryZh: "康斯特布尔的风景笔触与空气感影响了德拉克罗瓦对色彩的处理。", summaryEn: "Constable's landscape brushwork and atmosphere influenced Delacroix's treatment of colour." },
  { from: "jean-francois-millet", to: "van-gogh", type: "influence", strength: 5, zh: "劳动者题材影响", en: "Influence of labouring subjects", summaryZh: "梵高长期临摹并回应米勒的农民劳动题材与朴素人物造型。", summaryEn: "Van Gogh repeatedly copied and answered Millet's peasant labour subjects and plain figure types." },
  { from: "claude-monet", to: "berthe-morisot", type: "network", strength: 3, zh: "印象派展览网络", en: "Impressionist exhibition network", summaryZh: "莫奈与莫里索同属印象派独立展览和巴黎现代绘画网络。", summaryEn: "Monet and Morisot shared the independent Impressionist exhibitions and Parisian modern-painting network." },
  { from: "berthe-morisot", to: "mary-cassatt", type: "network", strength: 4, zh: "女性印象派同代网络", en: "Women Impressionists' network", summaryZh: "莫里索与卡萨特在印象派展览中共同扩展私人空间、家庭与现代女性观看经验。", summaryEn: "Morisot and Cassatt expanded private space, family subjects and modern women's experience within Impressionist exhibitions." },
  { from: "edvard-munch", to: "franz-marc", type: "influence", strength: 3, zh: "表现性图像影响", en: "Expressive-image influence", summaryZh: "蒙克以色彩、线条和心理紧张构成的图像成为德国表现主义的重要先声。", summaryEn: "Munch's use of colour, line and psychological tension became an important precedent for German Expressionism." },
  { from: "marcel-duchamp", to: "salvador-dali", type: "influence", strength: 3, zh: "观念与超现实主义影响", en: "Conceptual and Surrealist influence", summaryZh: "杜尚对艺术对象和展示制度的挑战进入超现实主义及其后续观念讨论。", summaryEn: "Duchamp's challenge to the art object and exhibition system entered Surrealism and later conceptual debates." },
  { from: "kazimir-malevich", to: "piet-mondrian", type: "parallel", strength: 4, zh: "几何抽象并行探索", en: "Parallel geometric abstraction", summaryZh: "马列维奇与蒙德里安以不同理论路径把绘画推进到几何抽象。", summaryEn: "Malevich and Mondrian advanced painting toward geometric abstraction through different theoretical paths." },
  { from: "rene-magritte", to: "salvador-dali", type: "network", strength: 3, zh: "超现实主义同代网络", en: "Surrealist contemporaries", summaryZh: "马格利特与达利以不同方法处理图像、语言、梦境和现实错位。", summaryEn: "Magritte and Dalí treated images, language, dream and displaced reality through distinct Surrealist methods." },
];

export const EVENT_SOURCES = [
  { key: "postwar-restitution", title: "National Archives: Holocaust-era assets and restitution", url: "https://www.archives.gov/research/holocaust", citationZh: "美国国家档案馆关于纳粹掠夺资产、档案与战后追索的专题资源。", citationEn: "U.S. National Archives resources on Nazi-looted assets, records and postwar restitution." },
  { key: "icom-history", title: "International Council of Museums history", url: "https://icom.museum/en/about-us/history-of-icom/", citationZh: "国际博物馆协会关于 1946 年成立及其博物馆合作使命的官方历史。", citationEn: "ICOM's official history of its 1946 foundation and museum-cooperation mission." },
  { key: "venice-history", title: "La Biennale di Venezia history", url: "https://www.labiennale.org/en/history", citationZh: "威尼斯双年展官方历史。", citationEn: "Official history of La Biennale di Venezia." },
  { key: "documenta-history", title: "documenta timeline", url: "https://www.documenta.de/en/timeline", citationZh: "documenta 官方时间线，记录 1955 年第一届展览。", citationEn: "Official documenta timeline recording the first exhibition in 1955." },
  { key: "florence-flood", title: "Uffizi Galleries: Florence flood and restoration", url: "https://www.uffizi.it/en/events", citationZh: "乌菲齐美术馆关于佛罗伦萨文化遗产与修复的机构记录。", citationEn: "Uffizi institutional records on Florentine heritage and conservation." },
  { key: "unesco-1970", title: "UNESCO 1970 Convention", url: "https://www.unesco.org/en/fight-illicit-trafficking/1970", citationZh: "联合国教科文组织 1970 年打击文化财产非法进出口与所有权转让公约。", citationEn: "UNESCO's 1970 Convention against illicit import, export and transfer of cultural property." },
  { key: "pompidou-history", title: "Centre Pompidou: history of the building", url: "https://www.centrepompidou.fr/en/collection/our-building", citationZh: "蓬皮杜中心关于建筑与 1977 年开放的官方介绍。", citationEn: "Centre Pompidou's official account of the building and its 1977 opening." },
  { key: "orsay-history", title: "Musée d'Orsay history", url: "https://www.musee-orsay.fr/en/articles/history-museum-197959", citationZh: "奥赛博物馆关于车站改造与 1986 年开馆的官方历史。", citationEn: "Musée d'Orsay's official history of the station conversion and 1986 opening." },
  { key: "berlin-museums", title: "Staatliche Museen zu Berlin history", url: "https://www.smb.museum/en/about-us/history/", citationZh: "柏林国立博物馆关于馆群历史、战争分裂与重组的官方资料。", citationEn: "Official history of the Berlin State Museums, including division and reorganisation." },
  { key: "washington-principles", title: "Washington Conference Principles on Nazi-Confiscated Art", url: "https://www.state.gov/washington-conference-principles-on-nazi-confiscated-art", citationZh: "美国国务院公布的 1998 年华盛顿原则。", citationEn: "The U.S. Department of State text of the 1998 Washington Conference Principles." },
  { key: "tate-modern", title: "Tate buildings history", url: "https://www.tate.org.uk/art/archive/tate-history/tate-buildings", citationZh: "泰特档案关于泰特现代美术馆于 2000 年开放的馆史。", citationEn: "Tate Archive history of Tate Modern's opening in 2000." },
  { key: "europeana", title: "Europeana mission and history", url: "https://pro.europeana.eu/about-us/mission", citationZh: "Europeana 关于 2008 年原型上线与数字文化遗产使命的官方介绍。", citationEn: "Europeana's official account of its 2008 prototype and digital-cultural-heritage mission." },
  { key: "neues-museum", title: "Neues Museum history", url: "https://www.smb.museum/en/museums-institutions/neues-museum/about-us/history/", citationZh: "柏林新博物馆关于战争损毁、修复与 2009 年重新开放的官方历史。", citationEn: "Official history of the Neues Museum's war damage, restoration and 2009 reopening." },
  { key: "ghent-restoration", title: "Closer to Van Eyck: Ghent Altarpiece restoration", url: "https://closertovaneyck.kikirpa.be/", citationZh: "根特祭坛画研究与修复项目的官方数字资源。", citationEn: "Official digital resource for the research and conservation of the Ghent Altarpiece." },
  { key: "rijksmuseum-history", title: "Rijksmuseum history", url: "https://www.rijksmuseum.nl/en/about-us/what-we-do/history", citationZh: "国立博物馆关于馆史与 2013 年重新开放的官方资料。", citationEn: "Rijksmuseum's official history, including the 2013 reopening." },
  { key: "notre-dame", title: "Notre-Dame de Paris restoration and reopening", url: "https://www.notredamedeparis.fr/en/reopening-ceremonies/", citationZh: "巴黎圣母院关于火灾后修复与 2024 年重新开放的官方记录。", citationEn: "Official Notre-Dame de Paris record of post-fire restoration and the 2024 reopening." },
  { key: "unesco-museums-covid", title: "UNESCO: museums around the world face COVID-19", url: "https://www.unesco.org/en/articles/museums-around-world-face-covid-19", citationZh: "联合国教科文组织关于 2020 年博物馆闭馆与数字转向的调查。", citationEn: "UNESCO survey of museum closures and digital responses in 2020." },
] as const;

export const POSTWAR_EVENTS: ExpansionEvent[] = [
  { slug: "postwar-restitution-programs", year: 1945, endYear: 1951, location: "berlin", titleZh: "战后欧洲藏品清点与追索展开", titleEn: "Postwar inventory and restitution programmes begin", summaryZh: "战争结束后，盟军、政府与博物馆开始清点、归还和追索被掠夺或转移的文化财产。", summaryEn: "After the war, Allied authorities, governments and museums began inventorying, returning and tracing looted or displaced cultural property.", significanceZh: "该过程把来源研究、返还和馆藏责任带入现代博物馆制度。", significanceEn: "The process made provenance research, restitution and collection responsibility central to modern museum practice.", sourceKey: "postwar-restitution" },
  { slug: "icom-founded", year: 1946, location: "paris", titleZh: "国际博物馆协会成立", titleEn: "International Council of Museums is founded", summaryZh: "国际博物馆协会在巴黎成立，为博物馆专业伦理、合作与文化遗产保护建立国际网络。", summaryEn: "The International Council of Museums was founded in Paris, creating an international network for museum ethics, cooperation and heritage protection.", significanceZh: "博物馆从国家收藏机构进一步进入跨国专业治理框架。", significanceEn: "Museums increasingly entered a transnational framework of professional governance.", sourceKey: "icom-history" },
  { slug: "venice-biennale-postwar-resumes", year: 1948, location: "venice", titleZh: "威尼斯双年展战后恢复", titleEn: "Venice Biennale resumes after the war", summaryZh: "威尼斯双年展在战后恢复举办，再次成为欧洲与国际现代艺术交流的重要平台。", summaryEn: "The Venice Biennale resumed after the war and again became a major platform for European and international modern-art exchange.", significanceZh: "它连接了战前先锋传统、战后国家馆体系和新的国际艺术网络。", significanceEn: "It connected prewar avant-garde traditions, postwar national pavilions and new international art networks.", sourceKey: "venice-history" },
  { slug: "documenta-one", year: 1955, location: "kassel", titleZh: "第一届 documenta 举办", titleEn: "The first documenta opens", summaryZh: "第一届 documenta 在卡塞尔举办，以战后展览重新连接被纳粹压制的现代艺术传统。", summaryEn: "The first documenta opened in Kassel, using a postwar exhibition to reconnect with modern-art traditions suppressed under National Socialism.", significanceZh: "documenta 由此成为战后欧洲艺术史叙事与大型周期展的重要节点。", significanceEn: "documenta became a major node in postwar European art history and the model of the large periodic exhibition.", sourceKey: "documenta-history" },
  { slug: "florence-flood-art-rescue", year: 1966, location: "florence", titleZh: "佛罗伦萨洪水引发大规模艺术抢救", titleEn: "Florence flood prompts large-scale art rescue", summaryZh: "洪水损害教堂、图书馆和博物馆中的大量作品，国际修复人员和志愿者参与抢救。", summaryEn: "Flooding damaged large numbers of works in churches, libraries and museums, prompting an international conservation response.", significanceZh: "灾难推动了纸张、壁画和板上绘画修复方法及应急保护网络的发展。", significanceEn: "The disaster advanced conservation methods for paper, fresco and panel painting and strengthened emergency heritage networks.", sourceKey: "florence-flood" },
  { slug: "unesco-1970-convention", year: 1970, location: "paris", titleZh: "UNESCO 通过 1970 年文化财产公约", titleEn: "UNESCO adopts the 1970 cultural-property convention", summaryZh: "公约建立打击文化财产非法进出口和所有权转让的国际合作框架。", summaryEn: "The convention established an international framework against illicit import, export and transfer of cultural property.", significanceZh: "来源、合法流通和返还成为博物馆收藏政策的重要约束。", significanceEn: "Provenance, lawful circulation and return became major constraints on museum collecting policy.", sourceKey: "unesco-1970" },
  { slug: "centre-pompidou-opens", year: 1977, location: "paris", titleZh: "蓬皮杜中心开放", titleEn: "Centre Pompidou opens", summaryZh: "蓬皮杜中心以跨学科文化机构和外露结构建筑在巴黎开放。", summaryEn: "Centre Pompidou opened in Paris as an interdisciplinary cultural institution in a building with exposed structural systems.", significanceZh: "现代艺术、设计、表演和公共文化空间被置于同一机构框架。", significanceEn: "Modern art, design, performance and public cultural space were brought into a single institutional framework.", sourceKey: "pompidou-history" },
  { slug: "musee-orsay-opens", year: 1986, location: "paris", titleZh: "奥赛博物馆开放", titleEn: "Musée d'Orsay opens", summaryZh: "由火车站改造的奥赛博物馆开放，集中展示 1848 至 1914 年的艺术。", summaryEn: "Musée d'Orsay opened in a converted railway station, concentrating on art from 1848 to 1914.", significanceZh: "现实主义、印象派与世纪末艺术获得新的专门展示与叙事空间。", significanceEn: "Realism, Impressionism and fin-de-siècle art gained a dedicated space and new narrative framework.", sourceKey: "orsay-history" },
  { slug: "berlin-museum-reunification", year: 1989, endYear: 1992, location: "berlin", titleZh: "柏林博物馆体系进入重新整合", titleEn: "Berlin museum collections enter reunification", summaryZh: "柏林墙倒塌和德国统一后，分处东西柏林的馆藏、档案与机构开始重新协调。", summaryEn: "After the fall of the Berlin Wall and German reunification, collections, archives and institutions divided between East and West Berlin began to be coordinated anew.", significanceZh: "政治边界变化直接改变了欧洲馆藏、建筑和艺术史展示的组织方式。", significanceEn: "Political change directly reshaped the organisation of European collections, buildings and art-historical display.", sourceKey: "berlin-museums" },
  { slug: "washington-principles-1998", year: 1998, location: "washington-dc", titleZh: "华盛顿原则通过", titleEn: "Washington Conference Principles are adopted", summaryZh: "44 个国家认可关于纳粹没收艺术品识别、档案开放和公正解决方案的非约束性原则。", summaryEn: "Forty-four governments endorsed non-binding principles on identifying Nazi-confiscated art, opening records and seeking just and fair solutions.", significanceZh: "来源研究与追索返还成为国际博物馆治理的持续责任。", significanceEn: "Provenance research and restitution became continuing responsibilities of international museum governance.", sourceKey: "washington-principles" },
  { slug: "tate-modern-opens", year: 2000, location: "london", titleZh: "泰特现代美术馆开放", titleEn: "Tate Modern opens", summaryZh: "由班克赛德发电站改造的泰特现代美术馆向公众开放。", summaryEn: "Tate Modern opened to the public in the converted Bankside Power Station.", significanceZh: "工业建筑再利用与大型现代艺术展示成为城市文化更新的重要模式。", significanceEn: "Industrial reuse and large-scale modern-art display became a major model of urban cultural regeneration.", sourceKey: "tate-modern" },
  { slug: "europeana-prototype-launch", year: 2008, location: "the-hague", titleZh: "Europeana 原型上线", titleEn: "Europeana prototype launches", summaryZh: "Europeana 原型上线，聚合欧洲博物馆、图书馆、档案馆和视听机构的数字文化遗产。", summaryEn: "The Europeana prototype launched, aggregating digital cultural heritage from European museums, libraries, archives and audiovisual collections.", significanceZh: "作品的跨机构检索、开放元数据与数字公众访问进入基础设施层面。", significanceEn: "Cross-institution discovery, open metadata and public digital access became infrastructure-level concerns.", sourceKey: "europeana" },
  { slug: "neues-museum-reopens", year: 2009, location: "berlin", titleZh: "柏林新博物馆重新开放", titleEn: "Neues Museum reopens", summaryZh: "经历战争损毁和长期修复后，柏林新博物馆重新开放。", summaryEn: "After wartime destruction and a long conservation campaign, Berlin's Neues Museum reopened.", significanceZh: "修复方案以保留战争痕迹和历史层累为核心，影响当代博物馆建筑讨论。", significanceEn: "Its conservation strategy retained traces of war and historical layering, influencing contemporary museum-architecture debates.", sourceKey: "neues-museum" },
  { slug: "ghent-altarpiece-restoration", year: 2012, location: "ghent", titleZh: "根特祭坛画大型修复启动", titleEn: "Major conservation of the Ghent Altarpiece begins", summaryZh: "根特祭坛画进入分阶段研究与修复，技术成像和开放数字资源同步推进。", summaryEn: "The Ghent Altarpiece entered a phased research and conservation campaign supported by technical imaging and open digital resources.", significanceZh: "修复改变了对凡·艾克材料、后期覆盖层和原始色彩的认识。", significanceEn: "The campaign changed understanding of Van Eyck's materials, later overpaint and original colour.", sourceKey: "ghent-restoration" },
  { slug: "rijksmuseum-reopens", year: 2013, location: "amsterdam", titleZh: "阿姆斯特丹国立博物馆重新开放", titleEn: "Rijksmuseum reopens", summaryZh: "经过长期改造，国立博物馆重新开放并重组荷兰艺术与历史的综合展示。", summaryEn: "After a long renovation, the Rijksmuseum reopened with an integrated presentation of Dutch art and history.", significanceZh: "《夜巡》等核心作品进入新的建筑、公众动线和国家叙事关系。", significanceEn: "Major works including The Night Watch entered a new relationship with architecture, visitor circulation and national narrative.", sourceKey: "rijksmuseum-history" },
  { slug: "notre-dame-fire", year: 2019, location: "paris", titleZh: "巴黎圣母院火灾", titleEn: "Fire at Notre-Dame de Paris", summaryZh: "火灾严重损坏巴黎圣母院屋顶和尖塔，并启动国际关注下的紧急保护与修复。", summaryEn: "Fire severely damaged the roof and spire of Notre-Dame de Paris and prompted emergency protection and restoration under international attention.", significanceZh: "建筑遗产、修复伦理、材料技术和公众捐助成为同一历史事件的组成部分。", significanceEn: "Architectural heritage, conservation ethics, material technology and public funding became parts of the same historical event.", sourceKey: "notre-dame" },
  { slug: "museum-closures-covid", year: 2020, location: "paris", titleZh: "疫情导致全球博物馆大规模闭馆", titleEn: "Pandemic causes widespread museum closures", summaryZh: "疫情期间博物馆广泛闭馆，展览、教育和公众访问快速转向线上。", summaryEn: "During the pandemic, museums closed widely and rapidly shifted exhibitions, education and public access online.", significanceZh: "数字收藏、虚拟展览和机构韧性从辅助功能转变为核心能力。", significanceEn: "Digital collections, virtual exhibitions and institutional resilience shifted from auxiliary functions to core capacities.", sourceKey: "unesco-museums-covid" },
  { slug: "notre-dame-reopens", year: 2024, location: "paris", titleZh: "巴黎圣母院重新开放", titleEn: "Notre-Dame de Paris reopens", summaryZh: "经过五年修复，巴黎圣母院于 2024 年 12 月重新开放。", summaryEn: "After five years of restoration, Notre-Dame de Paris reopened in December 2024.", significanceZh: "重新开放把灾后修复、传统工艺、数字记录和公众遗产意识连接起来。", significanceEn: "The reopening connected post-disaster conservation, traditional craft, digital documentation and public heritage awareness.", sourceKey: "notre-dame" },
];
